Merge Benchmark
PaddlePaddle/PaddleSeg pull request #1090
Opened 2021-06-16 12:05 UTC by wuyefeilin

Merge benchmark;
1 Models: hrnet_w18, deelpabv3p_resnet50_vd
2 add fleet and amp

2021-06-17 03:56 UTC, michaelowenliu requested changes

2021-06-17 03:56 UTC, michaelowenliu commented on legacy/pdseg/utils/timer.py
> +    remaining_time = int(remaining_step * speed)
double check the calculation.

2021-06-17 03:56 UTC, michaelowenliu commented on paddleseg/core/train.py
> +        fp16 (bool, optional): Whther to use amp.
Whther 写错了

2021-06-17 03:56 UTC, michaelowenliu commented on paddleseg/core/train.py
> +    # if nranks > 1:
注释部分可以删掉

2021-06-18 09:00 UTC, wuyefeilin commented on legacy/pdseg/utils/timer.py
> +    remaining_time = int(remaining_step * speed)
it is right.

2021-06-18 09:05 UTC, wuyefeilin commented on paddleseg/core/train.py
> +        fp16 (bool, optional): Whther to use amp.
已修复

2021-06-18 09:05 UTC, wuyefeilin commented on paddleseg/core/train.py
> +    # if nranks > 1:
已修复

2021-06-18 09:12 UTC, michaelowenliu approved these changes, later dismissed

2021-06-22 03:19 UTC, nepeplwu approved these changes

2021-06-22 03:33 UTC, merged