Add PortraitNet.
PaddlePaddle/PaddleSeg pull request #1132
Opened 2021-07-08 01:24 UTC by txyugood

1. Add portraitNet model.
2. Add RandomAffine in transform.py for data augmentation.
3. Add kl_loss and focal_loss for PortraintNet.
4. Modify train.py for PortraintNet.
5. Add EG1800 and Supervisely dataset.
6. Add stepdecay in config.py for training strategy.

2021-07-09 07:29 UTC, LutaoChu requested changes

2021-07-09 07:29 UTC, LutaoChu commented on paddleseg/transforms/transforms.py
> +class RandomAffine:
这个指缩放+旋转吧？是否可以通过已有的StepScaling+Rotation组合就好了，不用另外开发？

2021-07-09 07:29 UTC, LutaoChu commented on paddleseg/datasets/eg1800.py
> +def padding(img_ori, mask_ori, size=224, padding_color=128):
这些transform之前不是说可以复用的复用原来的transform，没有的新增到transform.py中吗？

2021-07-09 07:29 UTC, LutaoChu commented on paddleseg/datasets/supervisely.py
> +class SUPERVISELY(EG1800):
尽量继承DataSet吧，数据集间解耦

2021-07-09 07:29 UTC, LutaoChu commented on paddleseg/datasets/eg1800.py
> +    # myImg[myImg==1] = 255
删掉注释

2021-07-09 07:29 UTC, LutaoChu commented on paddleseg/models/portraitnet.py
> +class MobileNetV2(nn.Layer):
准确的讲，mobilenetv2是作为portraitnet的backbone吧
建议单独放一个文件，和mobilnetv3一样，放到paddleseg/models/backbone下

2021-07-09 07:29 UTC, LutaoChu commented on paddleseg/models/portraitnet.py
> +        self.deconv1 = nn.Conv2DTranspose(self.depth(96),
decode的部分放到portraitnet中

2021-07-09 07:29 UTC, LutaoChu commented on paddleseg/models/portraitnet.py
> +class PortraitNet(nn.Layer):
这段放在文件的前面吧

2021-07-09 07:35 UTC, txyugood commented on paddleseg/transforms/transforms.py
> +class RandomAffine:
这个是平移、缩放和旋转。我之前试过通过StepScaling+Rotation但是效果完全不一样。所以按照论文实现了RandomAffine。

2021-07-09 07:35 UTC, txyugood commented on paddleseg/datasets/eg1800.py
> +def padding(img_ori, mask_ori, size=224, padding_color=128):
这个padding跟transform中的padding略微有点区别，这个是居中的，transform里面的是是靠左的，而且不能设置。那我修改一下transform里的padding?

2021-07-09 07:35 UTC, txyugood commented on paddleseg/datasets/supervisely.py
> +class SUPERVISELY(EG1800):
好的，我改下这个。

2021-07-13 11:11 UTC, LutaoChu submitted a review, later dismissed

2021-07-13 11:38 UTC, LutaoChu commented on paddleseg/core/train.py
> -        train_dataset, batch_size=batch_size, shuffle=True, drop_last=True)
yapf版本改为0.26.0，所有文件重新格式化一下吧

2021-07-13 11:38 UTC, LutaoChu commented on paddleseg/datasets/eg1800.py
> +# Copyright (c) 2020 PaddlePaddle Authors. All Rights Reserved.
所有文件license里的2020改成2021

2021-07-13 11:38 UTC, LutaoChu commented on paddleseg/datasets/eg1800.py
> +import copy
所有文件的import顺序应该符合PEP8规范

2021-07-20 08:34 UTC, LutaoChu requested changes

2021-07-20 08:34 UTC, LutaoChu commented on configs/portraitnet/portraitnet_eg8000_224x224_46k.yml
> +learning_rate:
最新用lr_scheduler，learning_rate要被废弃了

2021-07-20 08:34 UTC, LutaoChu commented on paddleseg/datasets/eg1800.py
> +        transforms (list): A list of image transformations.
缺少transforms2的注释

2021-07-20 08:34 UTC, LutaoChu commented on paddleseg/datasets/supervisely.py
> +            im_aug = im * std + mean
这个地方逻辑有点别扭。最好是经过共同的transform后，出来两个分支transform，分别处理im和im_aug。
EG1800也是一样

2021-07-20 08:34 UTC, LutaoChu commented on paddleseg/models/losses/focal_loss.py
> +    def forward(self, inp, target):
inp, target改成logit，label吧

2021-07-20 08:34 UTC, LutaoChu commented on paddleseg/models/backbones/mobilenetv2.py
> +        Song-Hai Zhanga, Xin Donga, Jia Lib, Ruilong Lia, Yong-Liang Yangc
Reference改成mobilenetv2

2021-07-20 08:34 UTC, LutaoChu commented on paddleseg/models/losses/focal_loss.py
> +
改成
'''
Focal Loss.

Code referenced from: 
https://github.com/clcarwin/focal_loss_pytorch/blob/master/focalloss.py
'''

2021-07-20 08:34 UTC, LutaoChu commented on paddleseg/models/losses/focal_loss.py
> +        pt = paddle.to_tensor(np.exp(logpt.numpy()))
为什么不用paddle.exp呢？

2021-07-20 08:34 UTC, LutaoChu commented on paddleseg/models/losses/focal_loss.py
> +        inp = paddle.reshape(inp, [-1, 2])
应该是inp = paddle.reshape(inp, [-1, inp.shape[2])吧，用的时候不一定是二分类

2021-07-20 08:34 UTC, LutaoChu commented on paddleseg/models/losses/focal_loss.py
> +        inp = paddle.reshape(inp, [inp.shape[0], inp.shape[1], -1])
加上注释   ```# N,C,H,W => N,C,H*W```

2021-07-20 08:34 UTC, LutaoChu commented on paddleseg/models/losses/focal_loss.py
> +        inp = paddle.transpose(inp, [0, 2, 1])
加上注释 ```# N,C,H*W => N,H*W,C```

2021-07-20 08:34 UTC, LutaoChu commented on paddleseg/models/losses/focal_loss.py
> +        inp = paddle.reshape(inp, [-1, 2])
加上注释  ```# N,H*W,C => N*H*W,C```

2021-07-20 08:34 UTC, LutaoChu commented on paddleseg/models/losses/kl_loss.py
> +    def forward(self, inp, target):
inp, target改成logit，label

2021-07-20 08:34 UTC, LutaoChu commented on paddleseg/models/losses/kl_loss.py
> +    The Kullback-Leibler divergence Loss implement of Portrait Net.
去掉portraitnet
加上
```
    Code referenced from: 
    https://github.com/peterliht/knowledge-distillation-pytorch/blob/master/model/net.py
    
    Compute the knowledge-distillation (KD) loss given outputs, labels.
    "Hyperparameters": temperature and alpha
```

2021-07-20 09:57 UTC, LutaoChu requested changes

2021-07-20 09:57 UTC, LutaoChu commented on paddleseg/models/losses/focal_loss.py
> +    def __init__(self, gamma=2.0, ignore_index=255):
为了能让focal loss更通用，加上edge_label=False参数，通过edge_label判断是不是用edge监督

2021-07-20 09:57 UTC, LutaoChu commented on paddleseg/models/losses/focal_loss.py
> +        self.ignore_index = ignore_index
加上self.edge_label = edge_label

2021-07-20 09:57 UTC, LutaoChu commented on paddleseg/core/train.py
>          if loss_i.__class__.__name__ in ('BCELoss', ) and loss_i.edge_label:
改成 if loss_i.__class__.__name__ in ('BCELoss',  "FocalLoss") and loss_i.edge_label:

2021-07-20 09:57 UTC, LutaoChu commented on paddleseg/core/train.py
> +            loss_list.append(losses['coef'][i] * loss_i(logits, edges))
去掉上面两行

2021-07-22 08:51 UTC, LutaoChu commented on paddleseg/models/portraitnet.py
> +    def __init__(self, num_classes, add_edge=False):
开放参数min_channel，channel_ratio吧

2021-07-22 08:51 UTC, LutaoChu commented on paddleseg/models/portraitnet.py
> +    def __init__(self, num_classes, backbone, add_edge=False, pretrained=None):
开放参数min_channel，channel_ratio吧

2021-07-22 08:51 UTC, LutaoChu commented on paddleseg/models/backbones/mobilenetv2.py
> +class MobileNetV2(nn.Layer):
提到文件最前头吧

2021-07-22 09:24 UTC, LutaoChu submitted a review, later dismissed

2021-07-30 06:48 UTC, michaelowenliu approved these changes

2021-08-04 07:13 UTC, merged