Fix RMI Loss
PaddlePaddle/PaddleSeg pull request #1192
Opened 2021-07-22 09:23 UTC by shiyutang

2021-07-22 09:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/PaddleSeg?pullRequest=1192) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/PaddleSeg?pullRequest=1192) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/PaddleSeg?pullRequest=1192) it.</sub>

2021-07-22 11:25 UTC, michaelowenliu requested changes
some comments

2021-07-22 11:25 UTC, michaelowenliu commented on paddleseg/models/losses/rmi_loss.py
> +if __name__ == '__main__':
去掉这里的测试代码

2021-07-22 11:25 UTC, michaelowenliu commented on paddleseg/models/losses/rmi_loss.py
> +    Implements the Region Mutual Information(RMI) Loss for Semantic Segmentation.
增加原论文出处

2021-07-22 11:25 UTC, michaelowenliu commented on configs/deeplabv3p/deeplabv3p_resnet50_os8_cityscapes_1024x512_80k_rmiloss.yml
> +_base_: '../_base_/cityscapes.yml'
base改为deeplabv3p_resnet50_os8_cityscapes_1024x512_80k.yml，然后这个yml文件只需要写loss部分配置

2021-07-22 11:25 UTC, michaelowenliu commented on .gitignore
>  # js
这个文件不提交

2021-07-23 01:10 UTC, michaelowenliu approved these changes, later dismissed

2021-07-26 03:42 UTC, shiyutang commented
加入了RMILoss在flip和flip+ms增强下的对比readme效果

2021-07-28 07:24 UTC, michaelowenliu approved these changes

2021-07-28 07:25 UTC, merged