Update docs.
PaddlePaddle/PaddleSeg pull request #1208
Opened 2021-07-27 09:14 UTC by KazusaW1999

1.Update 'installation' instruction. Add English version.
2.Update 'quick start' instruction. Add English version.
3.Modify title of the third part in README file.
4.Update 'preparation of annotation data' instruction. Add English version.
5.Update 'annotating tutorial' instruction. Add English version.
6.Update 'custom dataset' instruction. Add English version.
7.Modify hyperlinks corresponding to above changes.

2021-07-30 03:24 UTC, LutaoChu requested changes

2021-07-30 03:24 UTC, LutaoChu commented on README_CN.md
> +*  PaddleSeg模块解读
改成 PaddleSeg自定义使用教程 好一点

2021-07-30 03:24 UTC, LutaoChu commented on README.md
> +*  Interpretation of PaddleSeg's Modules
改成PaddleSeg Custom Tutorial 比较好

2021-07-30 03:24 UTC, LutaoChu commented on docs/data/custom/data_prepare.md
> +## 2、Segment Custom Dataset
Segment 改成 Split

2021-07-30 03:24 UTC, LutaoChu commented on docs/data/custom/data_prepare_cn.md
> +标注图像必须为单通道图像，像素值即为对应的类别,像素标注类别需要从0开始递增。
补充说明 标注图格式为png格式

2021-07-30 03:24 UTC, LutaoChu commented on docs/data/custom/data_prepare_cn.md
> +|  |--xxx1.tif
tif改成jpg or png

2021-07-30 03:24 UTC, LutaoChu commented on docs/data/custom/data_prepare_cn.md
> +|  └--...
所有修改要记得中英文文档同步修改

2021-07-30 03:24 UTC, LutaoChu commented on docs/data/custom/data_prepare.md
> +### 2.3 Custom Dataset Segmentation and File List Generation
改成 Spilit Custom Dataset and Generate File List

2021-07-30 03:24 UTC, LutaoChu commented on docs/data/custom/data_prepare_cn.md
> +## 1、PaddleSeg如何使用数据集
去掉PaddleSeg

2021-07-30 03:24 UTC, LutaoChu commented on docs/data/custom/data_prepare.md
> +## 1、How PaddleSeg Use Datasets
改为 How to Use Datasets

2021-07-30 03:24 UTC, LutaoChu commented on docs/data/marker/marker.md
> +## 3、Segment a custom dataset
Segment 改为 Split

2021-07-30 03:24 UTC, LutaoChu commented on docs/data/marker/marker_cn.md
> +images/xxx1.tif annotations/xxx1.png
tif 改成 jpg

2021-07-30 03:24 UTC, LutaoChu commented on docs/data/marker/marker_cn.md
> +- [精灵数据标注工具教程](https://github.com/PaddlePaddle/PaddleSeg/blob/release/v0.8.0/docs/annotation/jingling2seg.md)
精灵标注是旧版的链接，现在就不要放精灵标注了
同时把tools/jingling2seg.py删了吧

2021-07-30 03:24 UTC, LutaoChu commented on docs/data/marker/marker_cn.md
> +python tools/split_dataset_list.py <dataset_root> images annotations --split 0.6 0.2 0.2 --format tif png
所有的tif都改成jpg吧

2021-07-30 03:24 UTC, LutaoChu commented on docs/data/marker/marker_cn.md
> +|--format|图片和标签集的数据格式|"tif"  "png"|2|
tif 改成 jpg

2021-07-30 03:24 UTC, LutaoChu commented on docs/data/marker/marker_cn.md
> +|  |--xxx1.tif
tif改成jpg

2021-07-30 03:24 UTC, LutaoChu commented on docs/data/marker/marker_cn.md
> +其中`[SEP]`是文件路径分割符，可以在`DATASET.SEPARATOR`配置项中修改, 默认为空格。文件列表的路径以数据集根目录作为相对路径起始点，`DATASET.DATA_DIR`即为数据集根目录。
DATASET.xxx是旧版的写法了，改成新版config写法吧

2021-07-30 03:24 UTC, LutaoChu commented on docs/data/marker/marker_cn.md
> +不可在`DATASET.TRAIN_FILE_LIST`和`DATASET.VAL_FILE_LIST`配置项中使用。
改成新版配置项

2021-07-30 03:24 UTC, LutaoChu commented on docs/data/marker/marker_cn.md
> +此时的文件列表仅可在调用`legacy/pdseg/vis.py`进行可视化展示时使用，
legacy/pdseg/vis.py 改成 predict.py

新版教程不要出现再用legacy的代码、文档

2021-07-30 03:24 UTC, LutaoChu commented on docs/data/marker/marker_cn.md
> +请参考[目录](https://github.com/PaddlePaddle/PaddleSeg/blob/release/v0.8.0/docs/annotation/cityscapes_demo)。
如果要用旧版的demo，要重新拷到新版里添加

2021-07-30 03:24 UTC, LutaoChu commented on docs/data/transform/transform_cn.md
> +- 本文档将提供3种标注工具的使用教程：[EISeg](#一、EISeg)、[LabelMe](#二、LabelMe)、[精灵标注](#三、精灵标注)。
去掉精灵标注

2021-07-30 03:24 UTC, LutaoChu commented on docs/quick_start_cn.md
> +learning_rate: #设定学习率
改成lr_schedule的写法，这是最新的

2021-07-30 03:37 UTC, KazusaW1999 commented on docs/data/custom/data_prepare.md
> +## 2、Segment Custom Dataset
Done.

2021-07-30 03:41 UTC, KazusaW1999 commented on README_CN.md
> +*  PaddleSeg模块解读
Done

2021-07-30 03:41 UTC, KazusaW1999 commented on README.md
> +*  Interpretation of PaddleSeg's Modules
Done

2021-07-30 03:44 UTC, KazusaW1999 commented on docs/data/transform/transform_cn.md
> +- 本文档将提供3种标注工具的使用教程：[EISeg](#一、EISeg)、[LabelMe](#二、LabelMe)、[精灵标注](#三、精灵标注)。
Done

2021-07-30 03:51 UTC, KazusaW1999 commented on docs/data/custom/data_prepare_cn.md
> +标注图像必须为单通道图像，像素值即为对应的类别,像素标注类别需要从0开始递增。
Done

2021-07-30 03:54 UTC, KazusaW1999 commented on docs/data/custom/data_prepare_cn.md
> +|  |--xxx1.tif
Done

2021-07-30 03:55 UTC, KazusaW1999 commented on docs/data/custom/data_prepare.md
> +### 2.3 Custom Dataset Segmentation and File List Generation
Done

2021-07-30 03:55 UTC, KazusaW1999 commented on docs/data/custom/data_prepare.md
> +## 1、How PaddleSeg Use Datasets
Done

2021-07-30 03:58 UTC, KazusaW1999 commented on docs/data/custom/data_prepare_cn.md
> +## 1、PaddleSeg如何使用数据集
Done

2021-07-30 03:59 UTC, KazusaW1999 commented on docs/data/custom/data_prepare_cn.md
> +|  └--...
Done

2021-07-30 05:00 UTC, KazusaW1999 commented on docs/data/marker/marker_cn.md
> +images/xxx1.tif annotations/xxx1.png
Done

2021-07-30 05:04 UTC, KazusaW1999 commented on docs/data/marker/marker_cn.md
> +此时的文件列表仅可在调用`legacy/pdseg/vis.py`进行可视化展示时使用，
Done

2021-07-30 05:04 UTC, KazusaW1999 commented on docs/data/marker/marker.md
> +## 3、Segment a custom dataset
Done

2021-07-30 05:07 UTC, KazusaW1999 commented on docs/data/marker/marker_cn.md
> +- [精灵数据标注工具教程](https://github.com/PaddlePaddle/PaddleSeg/blob/release/v0.8.0/docs/annotation/jingling2seg.md)
Done

2021-07-30 05:11 UTC, KazusaW1999 commented on docs/data/marker/marker_cn.md
> +python tools/split_dataset_list.py <dataset_root> images annotations --split 0.6 0.2 0.2 --format tif png
Done

2021-07-30 05:11 UTC, KazusaW1999 commented on docs/data/marker/marker_cn.md
> +|--format|图片和标签集的数据格式|"tif"  "png"|2|
Done

2021-07-30 05:12 UTC, KazusaW1999 commented on docs/data/marker/marker_cn.md
> +|  |--xxx1.tif
Done

2021-07-30 05:20 UTC, KazusaW1999 commented on docs/data/marker/marker_cn.md
> +其中`[SEP]`是文件路径分割符，可以在`DATASET.SEPARATOR`配置项中修改, 默认为空格。文件列表的路径以数据集根目录作为相对路径起始点，`DATASET.DATA_DIR`即为数据集根目录。
Done

2021-07-30 05:33 UTC, KazusaW1999 commented on docs/quick_start_cn.md
> +learning_rate: #设定学习率
Done

2021-07-30 06:16 UTC, KazusaW1999 commented on docs/data/marker/marker_cn.md
> +不可在`DATASET.TRAIN_FILE_LIST`和`DATASET.VAL_FILE_LIST`配置项中使用。
Done

2021-07-30 06:41 UTC, KazusaW1999 commented on docs/data/marker/marker_cn.md
> +请参考[目录](https://github.com/PaddlePaddle/PaddleSeg/blob/release/v0.8.0/docs/annotation/cityscapes_demo)。
Done. 添加了docs中的示例文件

2021-07-30 09:02 UTC, LutaoChu commented on docs/data/marker/marker.md
> +images/xxx2.jpg (xx2.png) annotations/xxx2.png
还是去掉括号这块吧。在原图要求里说明可以是jpg、png等opencv支持的格式

其他文件也都相应修改一下

2021-07-30 09:02 UTC, LutaoChu commented on docs/data/marker/marker.md
> +|  |--xxx1.jpg (xx1.png)
同上

2021-07-30 09:02 UTC, LutaoChu commented on docs/data/marker/marker_cn.md
> +分割符请使用空格（与[Dataset](../../../paddleseg/datasets/dataset.py)类中保持一致），即train.txt和val.txt的内容整理为：
改成 需要保证文件列表的分割符与你的Dataset类保持一致，默认分割符为空格。

2021-07-30 09:02 UTC, LutaoChu commented on docs/data/marker/marker_cn.md
> +    ...
删掉这三行

2021-07-30 09:02 UTC, LutaoChu commented on docs/data/marker/marker_cn.md
图片改成

    images/image1.jpg
    images/image2.jpg

2021-07-30 10:18 UTC, KazusaW1999 commented on docs/data/marker/marker_cn.md
> +    ...
Done

2021-07-30 10:18 UTC, KazusaW1999 commented on docs/data/marker/marker.md
> +images/xxx2.jpg (xx2.png) annotations/xxx2.png
Done

2021-07-30 10:18 UTC, KazusaW1999 commented on docs/data/marker/marker.md
> +|  |--xxx1.jpg (xx1.png)
Done

2021-07-30 10:19 UTC, KazusaW1999 commented on docs/data/marker/marker_cn.md
> +分割符请使用空格（与[Dataset](../../../paddleseg/datasets/dataset.py)类中保持一致），即train.txt和val.txt的内容整理为：
Done

2021-07-30 10:20 UTC, KazusaW1999 commented on docs/data/marker/marker_cn.md
Done

2021-08-02 12:28 UTC, LutaoChu commented on docs/data/marker/marker_cn.md
> +    images/image2.jpg
train和val应该有label

2021-08-02 12:28 UTC, LutaoChu commented on docs/data/marker/marker_cn.md
>  **注意事项**
train和test的file list示例保持一致，要么都用文字，要么都用图片吧

2021-08-02 12:50 UTC, KazusaW1999 commented on docs/data/marker/marker_cn.md
> +    images/image2.jpg
Done

2021-08-03 06:37 UTC, LutaoChu submitted a review, later dismissed

2021-08-04 14:28 UTC, LutaoChu approved these changes

2021-08-04 14:28 UTC, merged