add Rethinking BiSeNet (STDCSeg) to paddleseg
PaddlePaddle/PaddleSeg pull request #1305
Opened 2021-08-30 10:42 UTC by CuberrChen

百度第四届论文复现大赛Rethinking BiSeNet CVPR2021 (STDCSeg) 方案。
已经集成到paddleseg。
configs/stdcseg/中包含样例yml以及项目简要说明。

2021-09-01 04:02 UTC, shiyutang requested changes
修改提出的问题，待我这边本地验证可以之后进行合入

2021-09-01 04:02 UTC, shiyutang commented on configs/stdcseg/README.md
> +| Model      |Resolution | Training Iters | mIOU | Links1 |Links2 |log|
表格删去link1，link2，直接在最后一列links加上 model|log|vdl 即可

2021-09-01 04:02 UTC, shiyutang commented on configs/stdcseg/README.md
> +| Model      |Resolution | Training Iters | mIOU | Links1 |Links2 |log|
model 中包含训练好模型的下载链接，log为log下载链接，backbone可以不用加入到这部分

2021-09-01 04:02 UTC, shiyutang commented on configs/stdcseg/stdc2_seg_cityscapes_1024x512_80k.yml
> +    pretrained: '/home/path/STDCNet1446_76.47.pdiparams'
backbone不应当是本地索引，应当是一个网址

2021-09-01 04:02 UTC, shiyutang commented on configs/stdcseg/stdc2_seg_cityscapes_1024x512_80k.yml
config 间隔只需要一个空行，其他地方也相应改一下

2021-09-01 04:02 UTC, shiyutang commented on paddleseg/models/backbones/stdcnet.py
> +class ConvX(nn.Layer):
名字反映内容原则，可以修改成ConvBNRelu

2021-09-01 04:02 UTC, shiyutang commented on paddleseg/models/stdcseg.py
单独的语句之间可以不用有空行，类之间包含两行空行，函数和不同的逻辑块之间一个空行

2021-09-10 06:56 UTC, michaelowenliu submitted a review, later dismissed

2021-09-10 06:56 UTC, michaelowenliu commented on configs/stdcseg/README.md
> +> Fan, Mingyuan, et al. "Rethinking BiSeNet For Real-time Semantic Segmentation." Proceedings of the IEEE/CVF Conference on Computer Vision and Pattern Recognition. 2021.
Fan, Mingyuan, Shenqi Lai, Junshi Huang, Xiaoming Wei, Zhenhua Chai, Junfeng Luo, and Xiaolin Wei. "Rethinking BiSeNet For Real-time Semantic Segmentation." In Proceedings of the IEEE/CVF Conference on Computer Vision and Pattern Recognition, pp. 9716-9725. 2021.

2021-09-10 07:21 UTC, shiyutang commented on configs/stdcseg/README.md
> +|STDC2-Seg50|STDC1446|1024x512|80000|74.62%|-|-|[backbone提取码：tss7](https://pan.baidu.com/s/16kh3aHTBBX6wfKiIG-y3yA) [model+log提取码：nchx](https://pan.baidu.com/s/1sFHqZWhcl8hFzGCrXu_c7Q) [vdl](https://
使用模型评估（https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.2/docs/evaluation/evaluate/evaluate_cn.md），评估一下在不同数据增强之后的结果。

2021-09-10 07:21 UTC, shiyutang commented on paddleseg/models/backbones/stdcnet.py
> +        return out
这个部分在其他部分没有使用，确实是否需要使用，不使用就删除了吧

2021-09-10 07:21 UTC, shiyutang commented on paddleseg/models/stdcseg.py
> +
类间定义增加一行空行

2021-09-13 03:47 UTC, shiyutang approved these changes

2021-09-13 06:44 UTC, merged