Add LaneNet and weighted cross entropy
PaddlePaddle/PaddleSeg pull request #146
Opened 2020-01-07 11:13 UTC by LielinJiang

Add LaneNet and weighted cross entropy.

2020-01-07 11:32 UTC, ZeyuChen requested changes
需要减少代码冗余。
例如backbone和utils文件是否可以尽量复用
保留特殊的preprocess和核心特殊网络结构代码

2020-01-07 11:32 UTC, ZeyuChen commented on contrib/LaneNet/configs/lanenet.yaml
> +MEAN: [0.5, 0.5, 0.5]
配置文件中可以考虑屏蔽MEAN和STD，减少用户配置文件理解负担。

2020-01-07 11:32 UTC, ZeyuChen commented on contrib/LaneNet/eval.py
> +os.environ['FLAGS_eager_delete_tensor_gb'] = "0.0"
1.7版本的垃圾回收机制是否为默认策略？

2020-01-07 11:32 UTC, ZeyuChen commented on contrib/LaneNet/models/backbone/vgg.py
> +#copyright (c) 2019 PaddlePaddle Authors. All Rights Reserve.
这里的注释#与后面需要一个空格。
另外这一个文件是否可以与pdseg的backbone目录复用。

2020-01-07 11:32 UTC, ZeyuChen commented on contrib/LaneNet/models/libs/model_libs.py
> +# coding: utf8
这个代码是否也可以考虑与pdseg主框架复用？

2020-01-07 11:32 UTC, ZeyuChen commented on contrib/LaneNet/models/model_builder.py
> +def get_func(func_name):
这里新版本的代码我们做了简化，去除了动态加载。
使用动态加载会导致后面客户集成打包的时候查找不到文件出错。
后续一律改用静态显示加载的方式。

2020-01-07 11:32 UTC, ZeyuChen commented on contrib/LaneNet/utils/collect.py
> +#   Copyright (c) 2019  PaddlePaddle Authors. All Rights Reserved.
这个文件也冗余了

2020-01-07 11:32 UTC, ZeyuChen commented on contrib/LaneNet/utils/timer.py
> +#   Copyright (c) 2019  PaddlePaddle Authors. All Rights Reserved.
这个文件似乎完全冗余，是否可以复用pdseg目录的代码

2020-01-08 03:08 UTC, nepeplwu commented on pdseg/utils/config.py
> +# cross entropy weight, 如果不为None，会根据每个batch中各个类别的数目，动态调整类别权重。
```python
cfg.SOLVER.CROSS_ENTROPY_WEIGHT = "lanenet"
```
这种使用方式会让用户觉得困惑，建议改进下，例如新增一个配置项用于配置是否选择动态weight

2020-01-08 03:08 UTC, nepeplwu commented on contrib/LaneNet/vis.py
> +def visualize(cfg,
v0.3.0版本中增加了伪彩色图的支持，建议同步下对应的代码

2020-01-08 03:08 UTC, nepeplwu commented on contrib/LaneNet/solver.py
> +    def lr_warmup(self, learning_rate, warmup_steps, start_lr, end_lr):
这里的warmup逻辑存在bug，需要更新到v0.3.0的代码

2020-01-08 03:53 UTC, LielinJiang commented on contrib/LaneNet/configs/lanenet.yaml
> +MEAN: [0.5, 0.5, 0.5]
removed

2020-01-08 03:54 UTC, LielinJiang commented on contrib/LaneNet/eval.py
> +os.environ['FLAGS_eager_delete_tensor_gb'] = "0.0"
在develop上测试ok

2020-01-08 03:54 UTC, LielinJiang commented on contrib/LaneNet/models/backbone/vgg.py
> +#copyright (c) 2019 PaddlePaddle Authors. All Rights Reserve.
done

2020-01-08 03:55 UTC, LielinJiang commented on contrib/LaneNet/models/libs/model_libs.py
> +# coding: utf8
done

2020-01-08 03:55 UTC, LielinJiang commented on contrib/LaneNet/models/model_builder.py
> +def get_func(func_name):
done

2020-01-08 03:55 UTC, LielinJiang commented on contrib/LaneNet/utils/collect.py
> +#   Copyright (c) 2019  PaddlePaddle Authors. All Rights Reserved.
removed

2020-01-08 03:55 UTC, LielinJiang commented on contrib/LaneNet/utils/timer.py
> +#   Copyright (c) 2019  PaddlePaddle Authors. All Rights Reserved.
removed

2020-01-08 03:56 UTC, LielinJiang commented on pdseg/utils/config.py
> +# cross entropy weight, 如果不为None，会根据每个batch中各个类别的数目，动态调整类别权重。
removed，use method like conv，"dynamic" or a list

2020-01-08 03:57 UTC, LielinJiang commented on contrib/LaneNet/vis.py
> +def visualize(cfg,
已删除这个函数，车道线用了自己的可视化。效果可参考readme

2020-01-08 03:58 UTC, LielinJiang commented on contrib/LaneNet/solver.py
> +    def lr_warmup(self, learning_rate, warmup_steps, start_lr, end_lr):
removed, use solver in pdseg.

2020-01-10 03:16 UTC, merged