[Feature] Add HRNet_W48_Contrast Model
PaddlePaddle/PaddleSeg pull request #1484
Opened 2021-10-29 13:05 UTC by justld

添加Exploring Cross-Image Pixel Contrast for Semantic Segmentation论文的模型到paddleseg中，并添加了对应的config文件。
1、添加model，HRNetW48Contrast
2、添加PixelContrastCrossEntropyLoss损失函数

2021-11-02 08:29 UTC, shiyutang requested changes

2021-11-02 08:29 UTC, shiyutang commented on configs/hrnet_w48_contrast/HRNet_W48_contrast_cityscapes_1024x512_60k.yml
> +  mode: val
请进行cityscapes.yml继承，并调整顺序，详见：https://github.com/PaddlePaddle/PaddleSeg/pull/1490#discussion_r740768500

2021-11-02 08:29 UTC, shiyutang commented on paddleseg/models/losses/pixel_contrast_cross_entropy_loss.py
> +            this_classes = paddle.unique(this_y)
可以合并成一行

2021-11-02 08:29 UTC, shiyutang commented on paddleseg/models/losses/pixel_contrast_cross_entropy_loss.py
> +        assert "embed" in preds
assert加上详细报错信息～

2021-11-02 08:29 UTC, shiyutang commented on paddleseg/models/losses/pixel_contrast_cross_entropy_loss.py
> +        n_view = min(n_view, self.max_views)
这两行同时给n_view进行赋值，66行会被67行覆盖

2021-11-02 08:29 UTC, shiyutang commented on paddleseg/models/losses/pixel_contrast_cross_entropy_loss.py
> +                    raise UserWarning("error happened, please check your code!")
说明什么问题，提供debug的信息～

2021-11-02 08:29 UTC, shiyutang commented on paddleseg/models/losses/pixel_contrast_cross_entropy_loss.py
> +        assert labels.shape[-1] == feats.shape[-1], '{} {}'.format(labels.shape, feats.shape)
assert信息完善

2021-11-02 08:30 UTC, shiyutang commented
precommit 修改格式：https://github.com/PaddlePaddle/PaddleSeg/pull/1490#issuecomment-957180794

2021-11-02 13:00 UTC, justld commented on configs/hrnet_w48_contrast/HRNet_W48_contrast_cityscapes_1024x512_60k.yml
> +  mode: val
已调整

2021-11-02 13:01 UTC, justld commented on paddleseg/models/losses/pixel_contrast_cross_entropy_loss.py
> +            this_classes = paddle.unique(this_y)
你好，后续需要用到58的别名，为了后续代码方便才这么写的。下面第三行用到了。

2021-11-02 13:01 UTC, justld commented on paddleseg/models/losses/pixel_contrast_cross_entropy_loss.py
> +        assert "embed" in preds
已添加

2021-11-02 13:02 UTC, justld commented on paddleseg/models/losses/pixel_contrast_cross_entropy_loss.py
> +        n_view = min(n_view, self.max_views)
你好，这里不会被覆盖。这里是将计算每个类别的采样数目与设置的阈值对比，选择较小的值作为采样数目。

2021-11-02 13:02 UTC, justld commented on paddleseg/models/losses/pixel_contrast_cross_entropy_loss.py
> +                    raise UserWarning("error happened, please check your code!")
已修改。

else部分是多余的，已删除。

2021-11-02 13:02 UTC, justld commented on paddleseg/models/losses/pixel_contrast_cross_entropy_loss.py
> +        assert labels.shape[-1] == feats.shape[-1], '{} {}'.format(labels.shape, feats.shape)
以完善

2021-11-03 07:59 UTC, shiyutang commented on paddleseg/models/losses/pixel_contrast_cross_entropy_loss.py
> +            this_classes = paddle.unique(this_y)
好的

2021-11-03 08:01 UTC, shiyutang commented
所有修改已经完善，我会重新训练达到精度之后进行合入。Good job～

2021-11-03 08:11 UTC, shiyutang reviewed
要求的修改已经完善，等待训练达到精度后即可合入，Good job～

2021-11-09 10:02 UTC, shiyutang submitted a review, later dismissed

2021-11-10 03:55 UTC, michaelowenliu requested changes

2021-11-10 03:55 UTC, michaelowenliu commented on paddleseg/models/hrnet_contrast.py
> +class HRNetW48Contrast(nn.Layer):
把主模型放在最开始部分

2021-11-10 03:55 UTC, michaelowenliu commented on paddleseg/models/hrnet_contrast.py
> +        proj_dim (int|optional): The output dimensions of projection head. Default: 256.
int, optional

2021-11-10 03:55 UTC, michaelowenliu commented on paddleseg/models/hrnet_contrast.py
> +        proj (str|optional): The type of projection head, only support 'linear' and 'convmlp'. Default: 'convmlp'
Default: 'convmlp'.

2021-11-10 03:55 UTC, michaelowenliu commented on paddleseg/models/hrnet_contrast.py
> +            )
如果linear和convmlp都不是呢？forward里面的self.proj会变成none吗？

2021-11-10 03:55 UTC, michaelowenliu commented on paddleseg/models/hrnet_contrast.py
> +                nn.Conv2D(dim_in, dim_in, kernel_size=1),
这里的conv，bn，relu可以直接复用layers.ConvBNReLU吗？

2021-11-10 03:55 UTC, michaelowenliu commented on configs/hrnet_w48_contrast/HRNet_W48_contrast_cityscapes_1024x512_60k.yml
> +  num_classes: 19
去掉num_classes

2021-11-10 03:55 UTC, michaelowenliu commented on paddleseg/models/hrnet_contrast.py
> +            nn.Conv2D(in_channels,
ConvBnRelu?

2021-11-10 03:55 UTC, michaelowenliu commented on paddleseg/models/hrnet_contrast.py
> +            return [
logit_list = [], logit_list.append(xxx), return logit_list

2021-11-10 03:55 UTC, michaelowenliu commented on paddleseg/models/losses/pixel_contrast_cross_entropy_loss.py
> +        temperature (float|optional): Controling the numerical similarity of features. Default: 0.1.
float, optional

2021-11-10 03:55 UTC, michaelowenliu commented on paddleseg/models/losses/pixel_contrast_cross_entropy_loss.py
> +        super(PixelContrastCrossEntropyLoss, self).__init__()
super().__init__()

2021-11-10 03:55 UTC, michaelowenliu commented on paddleseg/models/losses/pixel_contrast_cross_entropy_loss.py
> +            X(Tensor): reshaped feats, shape = [N, H*W, feat_channels]
X(Tensor) -> X (Tensor), [N, H*W, feat_channels] -> [N, H * W, feat_channels]

2021-11-10 03:55 UTC, michaelowenliu commented on paddleseg/models/losses/pixel_contrast_cross_entropy_loss.py
> +        batch_size, feat_dim = X.shape[0], X.shape[-1]
建议用paddle.shape(X)来获取，否则可能在导出模型出错

2021-11-10 03:55 UTC, michaelowenliu commented on paddleseg/models/losses/pixel_contrast_cross_entropy_loss.py
> +        for ii in range(batch_size):
ii -> i

2021-11-10 03:55 UTC, michaelowenliu commented on paddleseg/models/losses/pixel_contrast_cross_entropy_loss.py
> +            this_y = y_hat[ii]
this_y和this_classes命名修改下，比如current_y或者current_classes

2021-11-10 13:26 UTC, justld commented on paddleseg/models/hrnet_contrast.py
> +class HRNetW48Contrast(nn.Layer):
已修改

2021-11-10 13:26 UTC, justld commented on paddleseg/models/hrnet_contrast.py
> +class HRNetW48Contrast(nn.Layer):
已修改

2021-11-10 13:26 UTC, justld commented on paddleseg/models/hrnet_contrast.py
> +        proj_dim (int|optional): The output dimensions of projection head. Default: 256.
已修改

2021-11-10 13:26 UTC, justld commented on paddleseg/models/hrnet_contrast.py
> +            )
已修改，添加异常

2021-11-10 13:27 UTC, justld commented on paddleseg/models/hrnet_contrast.py
> +                nn.Conv2D(dim_in, dim_in, kernel_size=1),
已修改，使用layers.ConvBNReLU

2021-11-10 13:27 UTC, justld commented on paddleseg/models/losses/pixel_contrast_cross_entropy_loss.py
> +        super(PixelContrastCrossEntropyLoss, self).__init__()
已修改

2021-11-10 13:27 UTC, justld commented on configs/hrnet_w48_contrast/HRNet_W48_contrast_cityscapes_1024x512_60k.yml
> +  num_classes: 19
已修改

2021-11-10 13:27 UTC, justld commented on paddleseg/models/hrnet_contrast.py
> +            nn.Conv2D(in_channels,
已修改

2021-11-10 13:27 UTC, justld commented on paddleseg/models/losses/pixel_contrast_cross_entropy_loss.py
> +        temperature (float|optional): Controling the numerical similarity of features. Default: 0.1.
已修改

2021-11-10 13:27 UTC, justld commented on paddleseg/models/losses/pixel_contrast_cross_entropy_loss.py
> +        batch_size, feat_dim = X.shape[0], X.shape[-1]
已修改

2021-11-10 13:27 UTC, justld commented on paddleseg/models/losses/pixel_contrast_cross_entropy_loss.py
> +            this_y = y_hat[ii]
已修改

2021-11-10 13:27 UTC, justld commented on paddleseg/models/losses/pixel_contrast_cross_entropy_loss.py
> +        for ii in range(batch_size):
已修改

2021-11-10 13:28 UTC, justld commented on paddleseg/models/hrnet_contrast.py
> +            return [
已修改

2021-11-11 07:15 UTC, michaelowenliu approved these changes, later dismissed
@shiyutang 已review完，验证导出功能后可以合入

2021-11-16 07:03 UTC, michaelowenliu approved these changes

2021-11-16 08:13 UTC, merged