百度论文复现赛第四期Espnetv2
PaddlePaddle/PaddleSeg pull request #1490
Opened 2021-11-01 09:01 UTC by justld

百度论文复现赛第四期Espnetv2

1、添加了espnet backbone(paddleseg\models\backbones\espnet.py);
2、添加了espnet head(paddleseg\models\espnet.py);
3、添加了espnet cityscapes config(PaddleSeg\configs\espnet\espnet_cityscapes_1024_512_120k_x2.yml);

其他说明：
1、由于paddlepaddle==2.1.2 交叉熵损失函数的bug，需要在paddlepaddle-develop环境下才能跑通；
2、paddleseg-develop交叉熵损失函数有bug，需要更换为paddleseg-release/2.2的交叉熵损失。

2021-11-02 07:59 UTC, shiyutang requested changes

2021-11-02 07:59 UTC, shiyutang commented on configs/espnet/espnet_cityscapes_1024_512_120k_x2.yml
> +
这部分可以和cityscapes.yml相同，可以增加 _base_: '../_base_/cityscapes.yml' ，将不相同的部分重写，减少出错和冗余。

其他参考：https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.3/configs/ann/ann_resnet50_os8_cityscapes_1024x512_80k.yml

cityscapes.yml：https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.3/configs/_base_/cityscapes.yml

2021-11-02 07:59 UTC, shiyutang commented on configs/espnet/espnet_cityscapes_1024_512_120k_x2.yml
> +batch_size: 8
这个参考上一条中链接，写在最上方，同意格式方便修改

2021-11-02 07:59 UTC, shiyutang commented on paddleseg/models/backbones/espnet.py
> +                    break
这一段是不是可以写成：
```
while w2 != w1:
    inputs = F.avg_pool2d(inputs, kernel_size=3, padding=1, stride=2)
    w2 = inputs.shape[2]
```

2021-11-02 07:59 UTC, shiyutang commented on paddleseg/models/backbones/espnet.py
> +        assert eesp_down_channels >= 0, "DownSampler"
assert 的注释信息应当尽量明晰，例如“The out_channes for DownSampler should be bigger than in_channels, but got in_channles={}, out_channels={}”.format(in_channels, out_channles)

2021-11-02 07:59 UTC, shiyutang commented on paddleseg/models/backbones/espnet.py
> +        assert eesp_down_channels >= 0, "DownSampler"
更好的，可以改成：
```
if out_channles< in_channles:
   raise RuntimeError(“The out_channes for DownSampler should be bigger than in_channels, but got in_channles={}, out_channels={}”.format(in_channels, out_channles))
```

2021-11-02 07:59 UTC, shiyutang commented on paddleseg/models/backbones/espnet.py
> +                                eesp_down_channels,
这里可以改成out_channles-in_channels，减少暴露对数据的操作

2021-11-02 07:59 UTC, shiyutang commented on paddleseg/models/backbones/espnet.py
> +        if inputs is not None:
改成 if inputs 就可以

2021-11-02 07:59 UTC, shiyutang commented on paddleseg/models/backbones/espnet.py
> +class EESPNet(nn.Layer):
名字可以都改相应成ESPNet_backbone，明确类的含义。

2021-11-02 07:59 UTC, shiyutang commented on paddleseg/models/backbones/espnet.py
> +
不必要的空行删去

2021-11-02 07:59 UTC, shiyutang commented on paddleseg/models/backbones/espnet.py
> +        channels = 0
后面有channels的初始化，这里不用初始化了

2021-11-02 07:59 UTC, shiyutang commented on paddleseg/models/backbones/espnet.py
> +                out_l3 = layer(out_l3)
这里是不是可以替换为：
```
out_l3 = self.level3_0(out_l2, x)
for i, layer in enumerate(self.level3): 
    out_l3 = layer(out_l3)
```

2021-11-02 07:59 UTC, shiyutang commented on paddleseg/models/backbones/espnet.py
> +                out_l4 = layer(out_l4)
这里和上一条同理，减少代码量

2021-11-02 07:59 UTC, shiyutang commented on paddleseg/models/espnet.py
> +        )
这里没有用到size，是不是写错了呢？

2021-11-02 07:59 UTC, shiyutang commented on paddleseg/models/espnet.py
> +
空行删除～

2021-11-02 07:59 UTC, shiyutang commented on paddleseg/models/layers/layer_libs.py
> +        assert down_method in ['avg', 'esp'], "down_method only support 'avg' or 'esp'."
可以和之前的comment一样改成判断，变成输入检查的形式，并补充出错时的变量信息，例如，out_channels、branches等于多少

2021-11-02 07:59 UTC, shiyutang commented on paddleseg/models/layers/layer_libs.py
> +        self.downAvg = True if down_method == 'avg' else False
替换为
```
self.down_method = down_method
```
后面将`if self.stride == 2 and self.downAvg:`替换为：
```
if down_method==‘avg’：
```
这样代码更加可读

2021-11-02 07:59 UTC, shiyutang commented on paddleseg/models/layers/layer_libs.py
> +        del output
在这里删除output差异大么，差异不大可以删除这句，有些突兀

2021-11-02 08:00 UTC, shiyutang commented
修改后请使用precommit工具进行格式调整，详见：https://github.com/PaddlePaddle/PaddleSeg/blob/develop/docs/pr/pr/pr.md#4-%E4%BD%BF%E7%94%A8pre-commit%E5%8B%BE%E5%AD%90

2021-11-02 08:05 UTC, shiyutang commented on configs/espnet/README.md
> +|---|---|---|---|---|---|
| :---: | :---: | :---: | :---: | :---: | :---: |

替换

2021-11-03 07:26 UTC, justld commented on configs/espnet/espnet_cityscapes_1024_512_120k_x2.yml
> +
已修改

2021-11-03 07:26 UTC, justld commented on paddleseg/models/backbones/espnet.py
> +        assert eesp_down_channels >= 0, "DownSampler"
已修改

2021-11-03 07:26 UTC, justld commented on paddleseg/models/backbones/espnet.py
> +                                eesp_down_channels,
已修改

2021-11-03 07:26 UTC, justld commented on paddleseg/models/espnet.py
> +
已删除

2021-11-03 07:27 UTC, justld commented on paddleseg/models/backbones/espnet.py
> +        if inputs is not None:
你好，这里inputs是多维tensor，直接使用if inputs会报错。

2021-11-03 07:27 UTC, justld commented on paddleseg/models/backbones/espnet.py
> +class EESPNet(nn.Layer):
已修改

2021-11-03 07:27 UTC, justld commented on paddleseg/models/backbones/espnet.py
> +
已删除

2021-11-03 07:27 UTC, justld commented on paddleseg/models/backbones/espnet.py
> +        channels = 0
已删除

2021-11-03 07:28 UTC, justld commented on paddleseg/models/backbones/espnet.py
> +                out_l3 = layer(out_l3)
已修改

2021-11-03 07:28 UTC, justld commented on paddleseg/models/backbones/espnet.py
> +                out_l4 = layer(out_l4)
已修改

2021-11-03 07:29 UTC, justld commented on paddleseg/models/espnet.py
> +        )
这里sizes其实表示的是一个下采样的比例的意思，没有实际意义，已经修改相关代码。

2021-11-03 07:29 UTC, justld commented on paddleseg/models/layers/layer_libs.py
> +        assert down_method in ['avg', 'esp'], "down_method only support 'avg' or 'esp'."
已修改

2021-11-03 07:29 UTC, justld commented on paddleseg/models/layers/layer_libs.py
> +        self.downAvg = True if down_method == 'avg' else False
已修改

2021-11-03 07:29 UTC, justld commented on paddleseg/models/layers/layer_libs.py
> +        del output
已删除

2021-11-03 07:30 UTC, justld commented on configs/espnet/espnet_cityscapes_1024_512_120k_x2.yml
> +batch_size: 8
> 修改后请使用precommit工具进行格式调整，详见：https://github.com/PaddlePaddle/PaddleSeg/blob/develop/docs/pr/pr/pr.md#4-%E4%BD%BF%E7%94%A8pre-commit%E5%8B%BE%E5%AD%90

已使用pre-commit检查，不好意思，之前没在意pre-commit竟然没安装。

2021-11-03 07:30 UTC, justld commented on configs/espnet/README.md
> +|---|---|---|---|---|---|
已修改

2021-11-03 07:30 UTC, justld commented on paddleseg/models/backbones/espnet.py
> +                    break
已修改

2021-11-03 07:51 UTC, shiyutang commented on paddleseg/models/backbones/espnet.py
> +        if inputs is not None:
好的～

2021-11-03 08:03 UTC, shiyutang commented on configs/espnet/espnet_cityscapes_1024_512_120k_x2.yml
> +batch_size: 8
没关系～～

2021-11-03 08:10 UTC, shiyutang commented
要求的修改已经完善，等待训练达到精度后即可合入，Good job～

2021-11-03 08:10 UTC, shiyutang reviewed
要求的修改已经完善，等待训练达到精度后即可合入，Good job～

2021-11-03 08:48 UTC, shiyutang commented on configs/espnet/espnet_cityscapes_1024_512_120k_x2.yml
> +  type: adam
需要增加一行：
```_inherited_: False``` 避免对 cityscapes 的 optimizer sgd 里的 momentum 的继承

2021-11-03 08:59 UTC, justld commented on configs/espnet/espnet_cityscapes_1024_512_120k_x2.yml
> +  type: adam
已添加

2021-11-04 11:11 UTC, michaelowenliu requested changes

2021-11-04 11:11 UTC, michaelowenliu commented on configs/espnet/README.md
> +> Sachin Mehta, Mohammad Rastegari, Linda Shapiro, and Hannaneh Hajishirzi. "ESPNetv2: A Light-weight, Power Efficient, and General Purpose Convolutional Neural Network."
引用完整

2021-11-04 11:11 UTC, michaelowenliu commented on paddleseg/models/backbones/espnet.py
> +        kernel_size_maximum (int): A maximum value of kernel_size for EESP block.
optional

2021-11-04 11:30 UTC, shiyutang commented on configs/espnet/README.md
> +> Sachin Mehta, Mohammad Rastegari, Linda Shapiro, and Hannaneh Hajishirzi. "ESPNetv2: A Light-weight, Power Efficient, and General Purpose Convolutional Neural Network."
引用需要完整会议等信息，可替换为：
Mehta, Sachin, Mohammad Rastegari, Linda Shapiro, and Hannaneh Hajishirzi. "Espnetv2: A light-weight, power efficient, and general purpose convolutional neural network." In Proceedings of the IEEE/CVF Conference on Computer Vision and Pattern Recognition, pp. 9190-9200. 2019.

2021-11-04 11:31 UTC, shiyutang commented on paddleseg/models/backbones/espnet.py
> +        kernel_size_maximum (int): A maximum value of kernel_size for EESP block.
可以在有默认参数的位置加上optinal的注释，例如kernel_size_maximum (int, optional)

2021-11-04 11:44 UTC, shiyutang commented on paddleseg/models/__init__.py
> +from .espnet import EESPNetV2
为了更加明确命名含义，可以修改为ESPNetV2

2021-11-04 11:44 UTC, shiyutang commented on paddleseg/models/backbones/__init__.py
> +from .espnet import *
由于EESPNet_backbone 并不能作为常用 backbone 复用，而是处于代码简洁性出发形成，建议放入models/espnet.py，DownSampler 同理。

2021-11-04 11:44 UTC, shiyutang commented on paddleseg/models/layers/layer_libs.py
> +        self.in_channels = in_channels
由于 EESP 不是常用基础组件，不符合layer_libs设立初衷，建议将其放入models/espnet.py，BNPReLU同理。

2021-11-04 11:44 UTC, shiyutang commented on paddleseg/models/layers/layer_libs.py
> +
由于BNPReLU 不是常用基础组件，不符合layer_libs设立初衷，建议将其放入models/espnet.py。

2021-11-04 11:44 UTC, shiyutang commented on paddleseg/models/layers/__init__.py
> +from .layer_libs import ConvBNReLU, ConvBN, SeparableConvBNReLU, DepthwiseConvBN, AuxLayer, SyncBatchNorm, JPU, ConvBNPReLU, BNPReLU, EESP
根据加入layerlibs的模块，可以将, BNPReLU, EESP删去

2021-11-04 13:09 UTC, justld commented on configs/espnet/README.md
> +> Sachin Mehta, Mohammad Rastegari, Linda Shapiro, and Hannaneh Hajishirzi. "ESPNetv2: A Light-weight, Power Efficient, and General Purpose Convolutional Neural Network."
已修改

2021-11-04 13:10 UTC, justld commented on paddleseg/models/__init__.py
> +from .espnet import EESPNetV2
已修改

2021-11-04 13:10 UTC, justld commented on paddleseg/models/backbones/__init__.py
> +from .espnet import *
已修改，删除backbones文件夹内的espnet.py，内容移动到models/espnet.py

2021-11-04 13:10 UTC, justld commented on paddleseg/models/layers/layer_libs.py
> +        self.in_channels = in_channels
已经移动到models/espnet.py

2021-11-04 13:11 UTC, justld commented on paddleseg/models/layers/layer_libs.py
> +
已修改

2021-11-04 13:11 UTC, justld commented on paddleseg/models/layers/__init__.py
> +from .layer_libs import ConvBNReLU, ConvBN, SeparableConvBNReLU, DepthwiseConvBN, AuxLayer, SyncBatchNorm, JPU, ConvBNPReLU, BNPReLU, EESP
已删除

2021-11-04 13:11 UTC, justld commented on paddleseg/models/backbones/espnet.py
> +        kernel_size_maximum (int): A maximum value of kernel_size for EESP block.
已修改注释

2021-11-05 03:30 UTC, shiyutang commented on paddleseg/models/espnet.py
> +                 drop_prob=0.1,
这个可以放到最前面，处于格式统一需要～

2021-11-05 08:07 UTC, justld commented on paddleseg/models/espnet.py
> +                 drop_prob=0.1,
你好，已修改

2021-11-09 09:44 UTC, shiyutang approved these changes, later dismissed

2021-11-09 11:50 UTC, michaelowenliu requested changes

2021-11-09 11:50 UTC, michaelowenliu commented on paddleseg/models/espnet.py
> +class PSPModule(nn.Layer):
是否可以直接复用已有的PPModule，https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.3/paddleseg/models/layers/pyramid_pool.py

2021-11-09 11:50 UTC, michaelowenliu commented on paddleseg/models/espnet.py
> +    def hierarchicalUpsample(self, x, factor=3):
hierarchical_upsample

2021-11-09 11:50 UTC, michaelowenliu commented on paddleseg/models/espnet.py
> +class EESPNet_backbone(nn.Layer):
class命名采用驼峰命名法，这里可以用EESPNetBackbone，如果觉得名字太长，直接使用Backbone也不影响在该文件下的表意

2021-11-09 11:50 UTC, michaelowenliu commented on paddleseg/models/espnet.py
> +        drop_prob (float|optional): The probability of dropout. Default: 3.
float, optional

2021-11-09 12:10 UTC, justld commented on paddleseg/models/espnet.py
> +class PSPModule(nn.Layer):
你好，ESPNet是一个轻量级的模型，它设计的PSPModule为了减少参数数量，和paddleseg内置的PPModule有些区别。

2021-11-09 13:44 UTC, justld commented on paddleseg/models/espnet.py
> +    def hierarchicalUpsample(self, x, factor=3):
已修改

2021-11-09 13:44 UTC, justld commented on paddleseg/models/espnet.py
> +class EESPNet_backbone(nn.Layer):
已修改

2021-11-09 13:44 UTC, justld commented on paddleseg/models/espnet.py
> +        drop_prob (float|optional): The probability of dropout. Default: 3.
已修改

2021-11-10 02:30 UTC, shiyutang commented
将最新代码拉取后进行 validation，评估结果为mIOU=70.88%，预期精度为 mIOU=70.88%，符合预期，详细日志如下：
![image](https://user-images.githubusercontent.com/34859558/141038630-b68f7f88-9c8b-4b50-8659-0f8ae56b8347.png)

2021-11-10 02:45 UTC, michaelowenliu requested changes
@shiyutang 再测试下导出功能https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.3/docs/pr/pr/style_cn.md#%E5%9B%9B%E5%AF%BC%E5%87%BA%E5%92%8C%E6%B5%8B%E8%AF%95%E9%A2%84%E6%B5%8B%E6%A8%A1%E5%9E%8B

2021-11-12 03:32 UTC, michaelowenliu approved these changes

2021-11-12 06:12 UTC, merged