add quantization demo
PaddlePaddle/PaddleSeg pull request #151
Opened 2020-01-13 09:39 UTC by slf12

add quantization demo

2020-01-14 04:08 UTC, LielinJiang commented
> add quantization demo

建议把.sh里的配置加到config里，然后删除.sh文件

2020-01-15 03:44 UTC, ZeyuChen requested changes
1. 修改下文档中对外部用户感受不好的点。
2. 1.7会默认开启AutoGrowth策略，如果需要develop分支才能跑的话，可以不用设置0.98的显存占用
3. 显存垃圾回收下一个版本应该为默认开启策略，无需配置。

2020-01-15 03:44 UTC, ZeyuChen commented on slim/quantization/README.md
> +因为量化要对Program做修改，所以一些会修改Program的训练策略需要关闭。``sync_batch_norm`` 和量化多卡训练同时使用时会出错，原因暂不知，因此也需要将其关闭。
我认为这句『原因暂不知，因此也需要将其关闭』描述对外部用户印象不好，建议直接表述需要关闭即可。

2020-01-15 03:44 UTC, ZeyuChen commented on slim/quantization/eval.sh
> +export FLAGS_eager_delete_tensor_gb=0.0
我理解1.7后默认开启垃圾回收策略了，不需要再显示指定。

2020-01-15 03:44 UTC, ZeyuChen commented on slim/quantization/eval.sh
> +MODEL.ICNET.DEPTH_MULTIPLIER 1.0 \
为什么这里有ICNet的配置

2020-01-15 03:44 UTC, ZeyuChen commented on slim/quantization/eval.sh
> +DATASET.SEPARATOR " " \
走配置文件吧，一些默认的配置不需要再这里暴露给用户。

2020-01-15 03:44 UTC, ZeyuChen commented on slim/quantization/train.sh
> +export FLAGS_fraction_of_gpu_memory_to_use=0.98
设置这种配置对windows用户会有影响，会导致windows用户跑不起来。
1.7已经走AutoGrowth显存策略了，不需要再指定这个显存占用配置

2020-01-15 03:44 UTC, ZeyuChen commented on slim/quantization/train_quant.py
> +os.environ['FLAGS_eager_delete_tensor_gb'] = "0.0"
是否可以去掉？

2020-01-15 03:44 UTC, ZeyuChen commented on slim/quantization/eval_quant.py
> +os.environ['FLAGS_eager_delete_tensor_gb'] = "0.0"
1.7应该为默认策略，可以考虑去掉。

2020-01-16 03:05 UTC, slf12 commented
> > add quantization demo
> 
> 建议把.sh里的配置加到config里，然后删除.sh文件

done

2020-01-16 03:05 UTC, slf12 commented on slim/quantization/README.md
> +因为量化要对Program做修改，所以一些会修改Program的训练策略需要关闭。``sync_batch_norm`` 和量化多卡训练同时使用时会出错，原因暂不知，因此也需要将其关闭。
done

2020-01-16 03:05 UTC, slf12 commented on slim/quantization/eval.sh
> +export FLAGS_eager_delete_tensor_gb=0.0
done

2020-01-16 03:05 UTC, slf12 commented on slim/quantization/eval.sh
> +MODEL.ICNET.DEPTH_MULTIPLIER 1.0 \
已删除

2020-01-16 03:05 UTC, slf12 commented on slim/quantization/eval.sh
> +DATASET.SEPARATOR " " \
done

2020-01-16 03:06 UTC, slf12 commented on slim/quantization/train.sh
> +export FLAGS_fraction_of_gpu_memory_to_use=0.98
done

2020-01-16 03:06 UTC, slf12 commented on slim/quantization/train_quant.py
> +os.environ['FLAGS_eager_delete_tensor_gb'] = "0.0"
已删除

2020-01-16 03:06 UTC, slf12 commented on slim/quantization/eval_quant.py
> +os.environ['FLAGS_eager_delete_tensor_gb'] = "0.0"
done

2020-01-17 02:56 UTC, ZeyuChen commented
LGTM

2020-01-17 02:57 UTC, merged