[New feature] add Lane detection
PaddlePaddle/PaddleSeg pull request #1535
Opened 2021-11-15 02:48 UTC by neonhuang

add lane detection feature: this lane detection is based on semantic Segmentation, the model we use is bisenetV2； we has finished a pipeline for lane detection for this project

2021-11-15 03:39 UTC, michaelowenliu requested changes

2021-11-15 03:39 UTC, michaelowenliu commented on contrib/LaneSeg/transforms/transforms.py
> +@manager.TRANSFORMS.add_component
增加的transform方法并没特殊性，应该优先考虑合入paddleseg主目录。

2021-11-15 03:39 UTC, michaelowenliu commented on contrib/LaneSeg/README.md
> +接着我们需要确定相关配置，从本教程的角度，配置分为三部分：
第二部分删掉。

2021-11-15 03:39 UTC, michaelowenliu commented on contrib/LaneSeg/README.md
> +* 本教程旨在介绍如何通过使用PaddleSeg进行车道线检测
车道线背景？参考其他项目介绍。

2021-11-15 03:39 UTC, michaelowenliu commented on contrib/LaneSeg/README.md
> +       --save_dir output/result
可视化效果呢？后面的导出部署？

2021-11-15 03:39 UTC, michaelowenliu commented on contrib/LaneSeg/datasets/tusimple.py
> +import paddle
import规范参考https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.3/docs/pr/pr/style_cn.md

2021-11-15 03:39 UTC, michaelowenliu commented on contrib/LaneSeg/datasets/tusimple.py
> +        self.cut_height = cut_height
cut_height此处作用？

2021-11-15 03:39 UTC, michaelowenliu commented on contrib/LaneSeg/models/bisenet_lane.py
> +        logit_list = [seg_logit]
seg_logit没有使用

2021-11-15 03:39 UTC, michaelowenliu commented on contrib/LaneSeg/models/bisenet_lane.py
> +        C1, C2, C3 = 64, 64, 128
若与BiSeNetV2基本相同，采用import的方式调用paddleseg自带的BiSeNetV2

2021-11-15 03:39 UTC, michaelowenliu commented on contrib/LaneSeg/models/bisenet_lane.py
> +class SegHead(nn.Layer):
是否可以复用已有的，https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.3/paddleseg/models/layers/layer_libs.py#L156

2021-11-15 03:39 UTC, michaelowenliu commented on contrib/LaneSeg/utils/tusimple.py
> +import paddle.nn as nn
与dataset里面的tusimple.py重名

2021-11-15 03:39 UTC, michaelowenliu commented on contrib/LaneSeg/utils/generate_gif.py
> +import numpy as np
这个文件的使用方式在readme文档里没有体现。

2021-11-15 03:39 UTC, michaelowenliu commented on contrib/LaneSeg/utils/generate_seg_tusimple.py
> +SEG_WIDTH = 30
SEG_WIDTH含义？

2021-11-15 11:35 UTC, neonhuang commented on contrib/LaneSeg/transforms/transforms.py
> +@manager.TRANSFORMS.add_component
已经修复

2021-11-15 11:35 UTC, neonhuang commented on contrib/LaneSeg/README.md
> +接着我们需要确定相关配置，从本教程的角度，配置分为三部分：
已经删除

2021-11-15 11:36 UTC, neonhuang commented on contrib/LaneSeg/README.md
> +* 本教程旨在介绍如何通过使用PaddleSeg进行车道线检测
添加了部分，后面还有待完善

2021-11-15 11:36 UTC, neonhuang commented on contrib/LaneSeg/README.md
> +       --save_dir output/result
已经添加，部署也加上去了

2021-11-15 11:36 UTC, neonhuang commented on contrib/LaneSeg/datasets/tusimple.py
> +import paddle
已经修复

2021-11-15 11:37 UTC, neonhuang commented on contrib/LaneSeg/models/bisenet_lane.py
> +        C1, C2, C3 = 64, 64, 128
已经直接导入BiseNetV2的模型了，不过模型需要重新训练

2021-11-15 11:37 UTC, neonhuang commented on contrib/LaneSeg/models/bisenet_lane.py
> +class SegHead(nn.Layer):
已经按BiseNet V2直接导入

2021-11-15 11:37 UTC, neonhuang commented on contrib/LaneSeg/utils/tusimple.py
> +import paddle.nn as nn
已经修复了

2021-11-15 11:38 UTC, neonhuang commented on contrib/LaneSeg/utils/generate_gif.py
> +import numpy as np
这个文件已经删除

2021-11-15 11:38 UTC, neonhuang commented on contrib/LaneSeg/utils/generate_seg_tusimple.py
> +SEG_WIDTH = 30
已经修复

2021-11-16 02:46 UTC, michaelowenliu requested changes

2021-11-16 02:46 UTC, michaelowenliu commented on contrib/LaneSeg/README.md
> +* 车道线检测是属于自动驾驶算法范畴的一部分，可以用来辅助进行车辆定位和进行决策，本教程旨在介绍如何通过使用PaddleSeg进行车道线检测，本项目主要参考了[resa](https://github.com/ZJULearning/resa)
参考PaddleSeg其他项目完善车道线背景介绍。

2021-11-16 08:47 UTC, LutaoChu commented on contrib/LaneSeg/README.md
> +* PaddlePaddle >= 2.1.2 或develop版本
dev版本一直在变，建议去掉develop版本

2021-11-16 08:47 UTC, LutaoChu commented on contrib/LaneSeg/README.md
> +### python端部署
改成 ### Paddle Inference部署（Python）

2021-11-16 08:47 UTC, LutaoChu commented on contrib/LaneSeg/models/bisenet_lane.py
> +    The BiSeNetLane use BiseNet V2 to process lane task .
lane 改成 lane detection

2021-11-16 08:47 UTC, LutaoChu commented on contrib/LaneSeg/models/losses/lane_cross_entropy_loss.py
> +        self.weights = paddle.to_tensor([0.4, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0])
weights作为一个用户可输入的参数吧

2021-11-16 08:47 UTC, LutaoChu commented on contrib/LaneSeg/third_party/tusimple_processor.py
> +# this code heavily base on
is based on

2021-11-16 11:07 UTC, neonhuang commented on contrib/LaneSeg/third_party/tusimple_processor.py
> +# this code heavily base on
fix

2021-11-16 11:12 UTC, neonhuang commented on contrib/LaneSeg/models/losses/lane_cross_entropy_loss.py
> +        self.weights = paddle.to_tensor([0.4, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0])
fix

2021-11-16 11:14 UTC, neonhuang commented on contrib/LaneSeg/models/bisenet_lane.py
> +    The BiSeNetLane use BiseNet V2 to process lane task .
fix

2021-11-16 11:15 UTC, neonhuang commented on contrib/LaneSeg/README.md
> +### python端部署
fix

2021-11-29 07:30 UTC, michaelowenliu requested changes

2021-11-29 07:30 UTC, michaelowenliu commented on contrib/LaneSeg/README.md
> +[BiseNetLane](https://paddleseg.bj.bcebos.com/lane_seg/bisenet_lan.pdparams)
这里和第49行的链接重复。

2021-11-29 07:30 UTC, michaelowenliu commented on contrib/LaneSeg/README.md
> +Using Tusimple's open source [Tusimple](https://github.com/TuSimple/tusimple-benchmark/issues/3) dataset as our demo dataset for the tutorial.
下载哪些文件？这里可以直接提供下载脚本。

2021-11-29 07:30 UTC, michaelowenliu commented on contrib/LaneSeg/README.md
> +python third_party/generate_tusimple_dataset.py.py --root path/to/your/unzipped/file
.py.py？？

2021-11-29 07:30 UTC, michaelowenliu commented on contrib/LaneSeg/README_CN.md
> +车道线检测是自动驾驶算法的一个范畴，可以用来辅助进行车辆定位和进行决策，早期已有基于传统图像处理的车道线检测方法，但是随着技术的演进，车道线检测任务所应对的场景越来越多样化，目前更多的方式是寻求在语义上对车道线存在位置的检测。本项目主要使用PaddleSeg进行车道线检测
最后少一个句号

2021-11-29 07:30 UTC, michaelowenliu commented on contrib/LaneSeg/README_CN.md
> +[BiseNetLane](https://paddleseg.bj.bcebos.com/lane_seg/bisenet_lan.pdparams)
和52行重复

2021-12-05 03:08 UTC, neonhuang commented on contrib/LaneSeg/README.md
> +python third_party/generate_tusimple_dataset.py.py --root path/to/your/unzipped/file
done

2021-12-05 03:09 UTC, neonhuang commented on contrib/LaneSeg/README_CN.md
> +车道线检测是自动驾驶算法的一个范畴，可以用来辅助进行车辆定位和进行决策，早期已有基于传统图像处理的车道线检测方法，但是随着技术的演进，车道线检测任务所应对的场景越来越多样化，目前更多的方式是寻求在语义上对车道线存在位置的检测。本项目主要使用PaddleSeg进行车道线检测
done

2021-12-05 03:10 UTC, neonhuang commented on contrib/LaneSeg/README_CN.md
> +[BiseNetLane](https://paddleseg.bj.bcebos.com/lane_seg/bisenet_lan.pdparams)
done

2021-12-05 03:36 UTC, neonhuang commented on contrib/LaneSeg/README.md
> +Using Tusimple's open source [Tusimple](https://github.com/TuSimple/tusimple-benchmark/issues/3) dataset as our demo dataset for the tutorial.
done

2021-12-05 03:36 UTC, neonhuang commented on contrib/LaneSeg/README.md
> +[BiseNetLane](https://paddleseg.bj.bcebos.com/lane_seg/bisenet_lan.pdparams)
done

2022-01-05 03:58 UTC, michaelowenliu requested changes

2022-01-05 03:58 UTC, michaelowenliu commented on contrib/LaneSeg/README.md
> +pip install scikit-image
还需要scikit-learn

2022-01-05 03:58 UTC, michaelowenliu commented on contrib/LaneSeg/README_CN.md
> +pip install scikit-image
还需要scikit-learn

2022-01-05 03:58 UTC, michaelowenliu commented on contrib/LaneSeg/README.md
> +    --config configs/modnet/bisenetV2_tusimple_640x368_300k.yml \
config modnet?

2022-01-05 03:58 UTC, michaelowenliu commented on contrib/LaneSeg/README_CN.md
> +       --config configs/modnet/bisenetV2_tusimple_640x368_300k.yml \
config modnet?

2022-01-05 04:10 UTC, neonhuang commented on contrib/LaneSeg/README.md
> +pip install scikit-image
done

2022-01-05 04:10 UTC, neonhuang commented on contrib/LaneSeg/README.md
> +    --config configs/modnet/bisenetV2_tusimple_640x368_300k.yml \
done

2022-01-05 04:11 UTC, neonhuang commented on contrib/LaneSeg/README_CN.md
> +pip install scikit-image
done

2022-01-05 04:11 UTC, neonhuang commented on contrib/LaneSeg/README_CN.md
> +       --config configs/modnet/bisenetV2_tusimple_640x368_300k.yml \
done

2022-01-11 05:57 UTC, michaelowenliu requested changes

2022-01-11 05:57 UTC, michaelowenliu commented on contrib/LaneSeg/datasets/tusimple.py
> +        dataset_root (str): Cityscapes dataset directory.
Cityscapes？

2022-01-11 05:57 UTC, michaelowenliu commented on contrib/LaneSeg/export.py
> +from models import *
避免import *，把import的具体包写出来

2022-01-11 05:57 UTC, michaelowenliu commented on contrib/LaneSeg/predict.py
> +from datasets import *
避免import *，把import的具体包写出来。

2022-01-11 05:57 UTC, michaelowenliu commented on contrib/LaneSeg/export.py
> +        default='/Users/huangshenghui/Downloads/bisenet_lan.pdparams')
路径改成None

2022-01-11 05:57 UTC, michaelowenliu commented on contrib/LaneSeg/deploy/cpp/src/lane_postprocess.cpp
> +//
copyright参考：https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/imperative/all_reduce.cc#L1

2022-01-11 05:57 UTC, michaelowenliu commented on contrib/LaneSeg/deploy/cpp/src/lane_postprocess.hpp
> +//
copyright参考：https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/imperative/all_reduce.cc#L1

2022-01-11 05:57 UTC, michaelowenliu commented on contrib/LaneSeg/deploy/cpp/src/test_seg.cc
> +#include <algorithm>
copyright参考：https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/imperative/all_reduce.cc#L1

2022-01-11 05:57 UTC, michaelowenliu commented on contrib/LaneSeg/README.md
> +wget https://s3.us-east-2.amazonaws.com/benchmark-frontend/truth/1/test_label.json
网盘里已经有test_label.json，不需要通过wget下载

2022-01-11 05:57 UTC, michaelowenliu commented on contrib/LaneSeg/README_CN.md
> +wget https://s3.us-east-2.amazonaws.com/benchmark-frontend/truth/1/test_label.json
网盘里已经有test_label.json，不需要通过wget下载

2022-01-11 06:49 UTC, neonhuang commented on contrib/LaneSeg/datasets/tusimple.py
> +        dataset_root (str): Cityscapes dataset directory.
done

2022-01-11 06:52 UTC, neonhuang commented on contrib/LaneSeg/export.py
> +from models import *
done

2022-01-11 06:52 UTC, neonhuang commented on contrib/LaneSeg/predict.py
> +from datasets import *
done

2022-01-11 06:52 UTC, neonhuang commented on contrib/LaneSeg/export.py
> +        default='/Users/huangshenghui/Downloads/bisenet_lan.pdparams')
done

2022-01-11 06:53 UTC, neonhuang commented on contrib/LaneSeg/deploy/cpp/src/lane_postprocess.cpp
> +//
done

2022-01-11 06:54 UTC, neonhuang commented on contrib/LaneSeg/deploy/cpp/src/lane_postprocess.hpp
> +//
done

2022-01-11 06:54 UTC, neonhuang commented on contrib/LaneSeg/deploy/cpp/src/test_seg.cc
> +#include <algorithm>
done

2022-01-11 06:59 UTC, neonhuang commented on contrib/LaneSeg/README.md
> +wget https://s3.us-east-2.amazonaws.com/benchmark-frontend/truth/1/test_label.json
done

2022-01-11 06:59 UTC, neonhuang commented on contrib/LaneSeg/README_CN.md
> +wget https://s3.us-east-2.amazonaws.com/benchmark-frontend/truth/1/test_label.json
done

2022-01-11 09:27 UTC, michaelowenliu approved these changes

2022-01-12 01:29 UTC, merged