add android demo for human matting
PaddlePaddle/PaddleSeg pull request #1538
Opened 2021-11-15 08:21 UTC by qianbin1989228

人像抠图添加了安卓版demo，精简了代码（钱彬）

2021-11-15 08:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/PaddleSeg?pullRequest=1538) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/PaddleSeg?pullRequest=1538) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/PaddleSeg?pullRequest=1538) it.</sub>

2021-11-15 09:26 UTC, michaelowenliu requested changes

2021-11-15 09:26 UTC, michaelowenliu commented on contrib/Matting/deploy/human_matting_android_demo/app/local.properties
> +sdk.dir=/Users/chenlingchi/Library/Android/sdk
这里的路径名正确吗？

2021-11-15 09:26 UTC, michaelowenliu commented on contrib/Matting/deploy/human_matting_android_demo/README.md
> +* git clone https://github.com/qianbin1989228/human_matting_android_demo.git ;
还需要clone？

2021-11-16 00:47 UTC, qianbin1989228 commented on contrib/Matting/deploy/human_matting_android_demo/app/local.properties
> +sdk.dir=/Users/chenlingchi/Library/Android/sdk
这个路径不影响    之前官网人像分割的安卓demo下下来就是这样的（这里我没有改），build的时候不影响    因为不会用到app里面的local.properties

2021-11-16 00:48 UTC, qianbin1989228 commented on contrib/Matting/deploy/human_matting_android_demo/README.md
> +* git clone https://github.com/qianbin1989228/human_matting_android_demo.git ;
不需要了   这个demo现在合并到paddleseg中来了    我马上修改下readme

2021-11-16 02:56 UTC, michaelowenliu submitted a review, later dismissed

2021-11-16 03:48 UTC, michaelowenliu approved these changes, later dismissed

2021-11-16 03:53 UTC, wuyefeilin approved these changes, later dismissed
LGTM

2021-11-16 06:41 UTC, michaelowenliu approved these changes

2021-11-16 06:41 UTC, merged