[Add Model] Add model DMNet
PaddlePaddle/PaddleSeg pull request #1606
Opened 2021-12-09 09:15 UTC by justld

添加DMNet模型（Dynamic Multi-scale Filters for Semantic Segmentation）

添加内容：
configs/dmnet/dmnet_resnet101_os8_cityscapes_1024_512_100k.yml
configs/dmnet/README.md
paddleseg/models/dmnet.py

2021-12-10 06:44 UTC, shiyutang requested changes

2021-12-10 06:44 UTC, shiyutang commented on configs/dmnet/dmnet_resnet101_os8_cityscapes_1024x512_100k.yml
> +iters: 100000
plz put these configs at lines 3-4

2021-12-10 06:44 UTC, shiyutang commented on paddleseg/models/dmnet.py
> +            pad = (pad + 1, pad, pad + 1, pad)
move these data manipulation to __init__, since you only need to generate it once.

2021-12-10 06:44 UTC, shiyutang commented on paddleseg/models/dmnet.py
> +        output = F.conv2d(x, weight=generated_filter, groups=b * c)
Why do you want to use function rather than nn.layer here?
you can remove the annotations.

2021-12-10 08:41 UTC, justld commented on configs/dmnet/dmnet_resnet101_os8_cityscapes_1024x512_100k.yml
> +iters: 100000
fixed

2021-12-10 08:41 UTC, justld commented on paddleseg/models/dmnet.py
> +            pad = (pad + 1, pad, pad + 1, pad)
fixed

2021-12-10 08:43 UTC, justld commented on paddleseg/models/dmnet.py
> +        output = F.conv2d(x, weight=generated_filter, groups=b * c)
generatted_filter be used as weight of convolution and only funcional.conv2d can implement.

2021-12-10 08:43 UTC, justld commented on paddleseg/models/dmnet.py
> +        output = F.conv2d(x, weight=generated_filter, groups=b * c)
annotations are removed.

2021-12-14 03:09 UTC, shiyutang commented
Thank you for your effort. I will train it and merge it after validating the result.

2021-12-15 03:52 UTC, shiyutang commented
The validation result met the expectation.
![image](https://user-images.githubusercontent.com/34859558/146120049-4984fcf9-2927-4d18-a0cf-36602dec4f7f.png)

2021-12-17 07:32 UTC, shiyutang commented
基于修改后代码训练模型验证，jie'guo结果符合预期：
![image](https://user-images.githubusercontent.com/34859558/146506786-841e3148-9ebf-4bf8-92b4-f1e08b557a96.png)

2021-12-17 07:47 UTC, shiyutang submitted a review, later dismissed
LGTM

2021-12-20 06:14 UTC, shiyutang approved these changes
LGTM

2021-12-20 08:03 UTC, merged