Pfpn tipc
PaddlePaddle/PaddleSeg pull request #1681
Opened 2022-01-04 07:28 UTC by ETTR123

2022-01-05 06:27 UTC, LutaoChu requested changes

2022-01-05 06:27 UTC, LutaoChu commented on test_tipc/README.md
> +| PFPNNet | pfpnnet | 支持 | - | - | - |
pfpnnet需要大写

2022-01-05 06:27 UTC, LutaoChu commented on test_tipc/README.md
>  | MODNet | PP-Matting | 支持 | - | - | - |
基础训练预测是否自测过能跑通？

2022-01-05 06:27 UTC, LutaoChu commented on test_tipc/README.md
https://github.com/PaddlePaddle/PaddleSeg/blob/develop/test_tipc/docs/test_train_inference_python.md#1-%E6%B5%8B%E8%AF%95%E7%BB%93%E8%AE%BA%E6%B1%87%E6%80%BB   这个表格同步更新模型列表

2022-01-05 06:53 UTC, ETTR123 commented on test_tipc/README.md
>  | MODNet | PP-Matting | 支持 | - | - | - |
可以

2022-01-05 07:00 UTC, ETTR123 commented on test_tipc/README.md
> +| PFPNNet | pfpnnet | 支持 | - | - | - |
fix.

2022-01-05 07:00 UTC, ETTR123 commented on test_tipc/README.md
fix

2022-01-05 11:47 UTC, LutaoChu commented on test_tipc/docs/test_train_inference_python.md
> +| PFPNNet | PFPNNet | 正常训练 |  |  |  |
单机多卡最好也测试一下

2022-01-05 11:57 UTC, ETTR123 commented on test_tipc/docs/test_train_inference_python.md
> +| PFPNNet | PFPNNet | 正常训练 |  |  |  |
没有单机多卡环境唉，可以帮忙测试以下吗

2022-01-06 03:53 UTC, ETTR123 commented on test_tipc/docs/test_train_inference_python.md
> +| PFPNNet | PFPNNet | 正常训练 |  |  |  |
测试过了

2022-01-06 06:21 UTC, LutaoChu approved these changes

2022-01-06 09:04 UTC, merged