[TIPC] Merge benchmark to TIPC. Add 5 models.
PaddlePaddle/PaddleSeg pull request #1787
Opened 2022-02-21 11:53 UTC by LutaoChu

2022-02-21 11:59 UTC, mmglove commented on test_tipc/benchmark_train.sh
> +export model_commit=$(git log|head -n1|awk '{print $2}')
这两行可以删掉，模型commit会有公共的脚本获取，在PDC上这里是吧库给拷贝过来，这个时候拿不到commit

2022-02-21 11:59 UTC, mmglove commented on test_tipc/configs/deeplabv3p_resnet50_cityscapes/train_infer_python.txt
> +epoch:50
epoch:50  是否能够在5min内结束呢

2022-02-21 12:04 UTC, LutaoChu commented on test_tipc/benchmark_train.sh
> +export model_commit=$(git log|head -n1|awk '{print $2}')
done

2022-02-21 12:08 UTC, LutaoChu commented on test_tipc/configs/deeplabv3p_resnet50_cityscapes/train_infer_python.txt
> +epoch:50
这里的epoch其实在分割里是iter，50个iter很快的

2022-02-22 10:17 UTC, mmglove reviewed
LGTM

2022-02-24 00:32 UTC, michaelowenliu requested changes

2022-02-24 00:32 UTC, michaelowenliu commented on train.py
> +        default="precision",
default是"precision"？

2022-02-24 01:53 UTC, wuyefeilin commented on test_tipc/configs/deeplabv3p_resnet50/train_infer_python.txt
> +--precision:null
为null是不是就没必要输入这一项了

2022-02-24 01:56 UTC, wuyefeilin commented on train.py
> +        "--precision",
只要--precision不是fp16就是fp32， 是否增加一下提示或报错，不然用户输入FP16等其实也是运行的fp32

2022-02-24 06:37 UTC, LutaoChu commented on test_tipc/configs/deeplabv3p_resnet50/train_infer_python.txt
> +--precision:null
这是tipc的默认格式，实际跑的时候会替换掉

2022-02-24 06:38 UTC, LutaoChu commented on train.py
> +        default="precision",
我改一下

2022-02-24 06:44 UTC, LutaoChu commented on train.py
> +        "--precision",
不会的，已经有检查了
![image](https://user-images.githubusercontent.com/30695251/155472129-a839efc1-3a55-437e-a1c3-ccf367ad3cf0.png)

2022-02-24 06:48 UTC, juncaipeng approved these changes
lgtm

2022-02-24 10:49 UTC, michaelowenliu approved these changes

2022-02-24 10:49 UTC, wuyefeilin approved these changes
LGTM

2022-02-24 10:53 UTC, merged