[Enhance] Val Dataset Transform Decoupled
PaddlePaddle/PaddleSeg pull request #1816
Opened 2022-03-01 07:59 UTC by wuyefeilin

The val_dataset and val_transform is decoupled. 
When prediting, can get transform but not compose val_dataset.

2022-03-02 12:41 UTC, michaelowenliu requested changes

2022-03-02 12:41 UTC, michaelowenliu commented on paddleseg/cvlibs/config.py
> +            except FileNotFoundError:
不处理exception吗？

2022-03-02 16:11 UTC, wuyefeilin commented on paddleseg/cvlibs/config.py
> +            except FileNotFoundError:
因为matting里面没有num_classes, 不跳过的话还是会存在FileNotFoundError报错信息

2022-03-21 09:36 UTC, michaelowenliu approved these changes

2022-03-21 09:36 UTC, merged