[Fix] Fix Enet export and infer problem.
PaddlePaddle/PaddleSeg pull request #1919
Opened 2022-03-24 12:25 UTC by shiyutang

- Add docs about set input_shape.
- Add cityscape_val.list to decrease the infer time of enet.

2022-03-24 12:27 UTC, shiyutang commented
The inference time is as follows by running prepare.sh and test_train_infer_python.sh
<img width="917" alt="A4 Interene feafes) 3e1t2 m2," src="https://user-images.githubusercontent.com/34859558/159916095-fd7a1404-9e5f-4136-aa4b-0ae321c7e20a.png">

2022-03-25 03:48 UTC, LutaoChu commented
一次cpu预测就要2.5min，整个lite_train_lite_infer跑下来需要多长时间呢？会不会超过15min呢？

2022-03-25 03:57 UTC, LutaoChu requested changes

2022-03-25 03:57 UTC, LutaoChu commented on docs/deployment/inference/inference_cn.md
> +python deploy/python/infer.py --config /path/to/deploy.yaml --image_path # 如果导出指定了input_shape， 此处的图片大小需要和 input_shape 保持一致
如果deploy.yml的transform可以保证输入图片尺寸一样也是可以的。『此处的图片大小』写得有点模糊，到底是哪处呢

2022-03-25 03:57 UTC, LutaoChu commented on docs/model_export.md
> +       --input_shape 1 3 512 1024
bisenet模型导出为什么要固定shape呢

2022-03-25 03:57 UTC, LutaoChu commented on docs/model_export_cn.md
> +|input_shape| 设置导出模型的输入shape，比如传入`--input_shape 1 3 1024 1024`。如果不设置input_shape，默认导出模型的输入shape是[-1, 3, -1, -1] | 否（最好指定） | None |
改成 如果预测shape固定，建议指定input_shape参数

2022-03-25 03:57 UTC, LutaoChu commented on test_tipc/prepare.sh
> +    mv ./test_tipc/data/cityscapes_val_5.list ./test_tipc/data/cityscapes
mv改成cp

2022-03-25 09:16 UTC, shiyutang commented on docs/model_export.md
> +       --input_shape 1 3 512 1024
这个是通过示例说明固定输入尺寸的方式，不代表bisenet需要固定

2022-03-25 09:19 UTC, shiyutang commented
训练、评估、导出都比较快，单个 infer 时间2.5分钟。

2022-03-25 09:23 UTC, shiyutang commented on docs/model_export_cn.md
> +|input_shape| 设置导出模型的输入shape，比如传入`--input_shape 1 3 1024 1024`。如果不设置input_shape，默认导出模型的输入shape是[-1, 3, -1, -1] | 否（最好指定） | None |
done

2022-03-25 09:23 UTC, shiyutang commented on docs/deployment/inference/inference_cn.md
> +python deploy/python/infer.py --config /path/to/deploy.yaml --image_path # 如果导出指定了input_shape， 此处的图片大小需要和 input_shape 保持一致
done

2022-03-25 09:23 UTC, shiyutang commented on test_tipc/prepare.sh
> +    mv ./test_tipc/data/cityscapes_val_5.list ./test_tipc/data/cityscapes
done

2022-03-28 02:41 UTC, LutaoChu commented
> 训练、评估、导出都比较快，单个 infer 时间2.5分钟。

整个流程还包括多个cpu infer和gpu infer，看下整体耗时满不满足15min把

2022-03-28 02:42 UTC, LutaoChu commented
> > 训练、评估、导出都比较快，单个 infer 时间2.5分钟。
> 
> 整个流程还包括多个cpu infer和gpu infer，看下整体耗时满不满足15min把

cpu infer比较慢，gpu快很多

2022-03-29 02:26 UTC, shiyutang commented
根据日志，训练到最后一次预测，一共耗时十分钟：
<img width="1229" alt="image" src="https://user-images.githubusercontent.com/34859558/160520247-f231ead8-aef8-4912-baee-d56df4d3a4f6.png">
<img width="1327" alt="image" src="https://user-images.githubusercontent.com/34859558/160520386-f6eb5fc4-c1cc-4040-9aad-3f62a572ec07.png">

2022-03-29 03:17 UTC, LutaoChu approved these changes

2022-03-29 03:17 UTC, merged