[Feature] Add DDRNet
PaddlePaddle/PaddleSeg pull request #1984
Opened 2022-04-08 10:02 UTC by justld

添加DDRNet及其配置文件、test_tipc。
DDRNet23 cityscapes val miou： 79.79%.
aistudio：https://aistudio.baidu.com/aistudio/projectdetail/3755861?contributionType=1

说明：使用官方提供的imagenet预训练模型转换为paddlepaddle后训练。代码有点丑陋没用layers里面的一些封装好的函数，是因为不好直接加载转换后的imagenet预训练权重。

2022-04-11 03:34 UTC, shiyutang requested changes
rerun 
```
pre-commit run --files configs/ddrnet/README.md configs/ddrnet/ddrnet23_cityscapes_1024x1024_120k.yml paddleseg/models/__init__.py paddleseg/models/ddrnet.py test_tipc/configs/ddrnet/ddrnet23_cityscapes_1024x1024_120k.yml test_tipc/configs/ddrnet/train_infer_python.txt
```
to pass the codestyle CI

2022-04-11 03:34 UTC, shiyutang commented on configs/ddrnet/ddrnet23_cityscapes_1024x1024_120k.yml
> +  pretrained: DDRNet23_imagenet.pdparams
修改后的预训练模型发过来，我来上传

2022-04-11 03:34 UTC, shiyutang commented on paddleseg/models/ddrnet.py
> +            nn.ReLU(),
可以先用[transfer.py](https://github.com/shiyutang/files/blob/main/param_transfer.py)把预训练模型的参数名称对应修改，并转换成paddle模型。

2022-04-11 03:34 UTC, shiyutang commented on paddleseg/models/ddrnet.py
> +        x_ = x_ + F.interpolate(self.compression4(self.relu(feats[3])),
下划线命名容易混淆，最好替换成有含义的名字

2022-04-11 03:34 UTC, shiyutang commented on paddleseg/models/ddrnet.py
> +class SegmentHead(nn.Layer):
名字可以换成DDRNetHead

2022-04-11 03:34 UTC, shiyutang commented on paddleseg/models/ddrnet.py
> +    expansion = 1
写到__init__里面会更整洁。

2022-04-11 03:34 UTC, shiyutang commented on paddleseg/models/ddrnet.py
> +    expansion = 2
写到__init__里面会更整洁。

2022-04-11 10:16 UTC, justld commented on paddleseg/models/ddrnet.py
> +        x_ = x_ + F.interpolate(self.compression4(self.relu(feats[3])),
已修改

2022-04-11 10:17 UTC, justld commented on paddleseg/models/ddrnet.py
> +class SegmentHead(nn.Layer):
已修改

2022-04-11 10:17 UTC, justld commented on paddleseg/models/ddrnet.py
> +    expansion = 2
后续需要用到Bottleneck.expansion，而不是Bottleneck().expansion

2022-04-13 13:14 UTC, justld commented
<img width="781" alt="845959e17cbffbc300ac9712fa623c3" src="https://user-images.githubusercontent.com/41244687/163188071-5691a3dc-a142-42d0-8457-cec09f3096ee.png">

<img width="660" alt="ad7dde0b7ce1c59c6af443b616d6c5e" src="https://user-images.githubusercontent.com/41244687/163188111-436cb502-9fda-4e4e-8d95-2b622fe2c0a0.png">

<img width="731" alt="811d5ed8a18ad5372473dc37a68bb83" src="https://user-images.githubusercontent.com/41244687/163188130-368a278c-44c9-47c4-a0e6-16f2849bd361.png">
tipc 6分钟

2022-04-14 07:02 UTC, shiyutang commented
validate result:
![image](https://user-images.githubusercontent.com/34859558/163331743-893419b6-2e83-49ca-9e76-70ef34b6b5fa.png)
![image](https://user-images.githubusercontent.com/34859558/163331719-1b82ada3-9b3b-4d44-ade8-cc85e2106da2.png)

2022-04-14 07:05 UTC, shiyutang approved these changes, later dismissed
LGTM

2022-04-14 07:13 UTC, shiyutang commented on test_tipc/configs/ddrnet/train_infer_python.txt
> +python:python3.7
python3.7>python3

2022-04-14 07:31 UTC, justld commented on test_tipc/configs/ddrnet/train_infer_python.txt
> +python:python3.7
Done

2022-04-15 01:33 UTC, michaelowenliu commented on configs/ddrnet/README.md
> +> Hong, Yuanduo, et al. "Deep dual-resolution networks for real-time and accurate semantic segmentation of road scenes." arXiv preprint arXiv:2101.06085 (2021).
Full authors list

2022-04-15 01:41 UTC, justld commented on configs/ddrnet/README.md
> +> Hong, Yuanduo, et al. "Deep dual-resolution networks for real-time and accurate semantic segmentation of road scenes." arXiv preprint arXiv:2101.06085 (2021).
Done

2022-04-15 07:39 UTC, LutaoChu commented on test_tipc/prepare.sh
> +        "fastscnn" "fcn_hrnetw18" "pp_liteseg_stdc1" "pp_liteseg_stdc2" "ddrnet")
好像执行时没有用到cityscapes_val_5.list吧
没有的话不需要添加

2022-04-15 07:43 UTC, LutaoChu commented
在tipc首页文档和基础链条文档里补充下这个模型

2022-04-15 07:49 UTC, justld commented on test_tipc/prepare.sh
> +        "fastscnn" "fcn_hrnetw18" "pp_liteseg_stdc1" "pp_liteseg_stdc2" "ddrnet")
已移除

2022-04-15 07:50 UTC, justld commented
已补充

2022-04-15 07:54 UTC, LutaoChu approved these changes

2022-04-15 08:00 UTC, merged