[TIPC] Add TIPC AMP training function
PaddlePaddle/PaddleSeg pull request #2004
Opened 2022-04-13 03:58 UTC by LutaoChu

1 新增TIPC混合精度全链条测试功能
2 PaddleSeg支持混合精度O2模式训练、边训边评估

2022-04-13 07:34 UTC, michaelowenliu requested changes

2022-04-13 07:34 UTC, michaelowenliu commented on paddleseg/core/train.py
> +        amp_level (str, optional): Auto mixed precision level. Accepted values are “O1” and “O2”: O1 represent mixed precision, the input data type of each operator will be casted by white_list and b
这句注释太长了，换行写。

2022-04-13 07:34 UTC, michaelowenliu commented on paddleseg/core/val.py
> +        amp_level (str, optional): Auto mixed precision level. Accepted values are “O1” and “O2”: O1 represent mixed precision, the input data type of each operator will be casted by white_list and b
长注释换行

2022-04-13 07:34 UTC, michaelowenliu commented on paddleseg/core/train.py
> +          amp_level='O1',
是否需要在parser.add_argument里面添加amp_level

2022-04-13 08:13 UTC, LutaoChu commented on paddleseg/core/train.py
> +          amp_level='O1',
在左下面的train.py里加了

2022-04-13 08:13 UTC, LutaoChu commented on paddleseg/core/train.py
> +        amp_level (str, optional): Auto mixed precision level. Accepted values are “O1” and “O2”: O1 represent mixed precision, the input data type of each operator will be casted by white_list and b
done

2022-04-13 08:13 UTC, LutaoChu commented on paddleseg/core/val.py
> +        amp_level (str, optional): Auto mixed precision level. Accepted values are “O1” and “O2”: O1 represent mixed precision, the input data type of each operator will be casted by white_list and b
done

2022-04-14 02:00 UTC, wuyefeilin approved these changes
LGTM

2022-04-15 06:12 UTC, michaelowenliu approved these changes

2022-04-15 06:12 UTC, merged