[Feature] Add CCNet
PaddlePaddle/PaddleSeg pull request #2005
Opened 2022-04-13 05:36 UTC by justld

添加CCNet及其配置文件、test_tipc。
CCNet cityscapes val miou： 80.95%.

2022-04-13 12:34 UTC, shiyutang requested changes
tipc需要按照review comment更新下再测试时间

2022-04-13 12:34 UTC, shiyutang commented on configs/ccnet/README.md
> +# Ccnet: Criss-cross attention for semantic segmentation
CCnet

2022-04-13 12:34 UTC, shiyutang commented on configs/ccnet/ccnet_resnet101_os8_cityscapes_769x769_60k.yml
> +  coef: [1, 0.4]
这两部分在model配置后

2022-04-13 12:34 UTC, shiyutang commented on test_tipc/configs/ccnet/ccnet_resnet101_os8_cityscapes_769x769_60k.yml
> +  coef: [1, 0.4]
同理

2022-04-13 12:34 UTC, shiyutang commented on test_tipc/configs/ccnet/train_infer_python.txt
> +random_infer_input:[{float32,[3,1024,2048]}]
这两部分不需要

2022-04-13 14:02 UTC, justld commented
<img width="769" alt="875aa4ed132ca2a792f520e6cf2356f" src="https://user-images.githubusercontent.com/41244687/163197952-e042877a-396d-4308-8d15-3bf8b4ac6519.png">


<img width="821" alt="b56e066320c5a279b6f1da545611623" src="https://user-images.githubusercontent.com/41244687/163197970-4f01d38a-3913-44cc-9d66-7e50b34e9601.png">

tipc 约5分钟

2022-04-13 14:03 UTC, justld commented on test_tipc/configs/ccnet/ccnet_resnet101_os8_cityscapes_769x769_60k.yml
> +  coef: [1, 0.4]
Done

2022-04-13 14:03 UTC, justld commented on configs/ccnet/README.md
> +# Ccnet: Criss-cross attention for semantic segmentation
Done

2022-04-13 14:03 UTC, justld commented on configs/ccnet/ccnet_resnet101_os8_cityscapes_769x769_60k.yml
> +  coef: [1, 0.4]
Done

2022-04-14 07:12 UTC, shiyutang commented on test_tipc/configs/ccnet/train_infer_python.txt
> +python:python3.7
python3.7->python3

2022-04-14 07:26 UTC, shiyutang commented
Validate result：
![image](https://user-images.githubusercontent.com/34859558/163334102-718a3973-5d90-4de7-bb6c-3be454e8ad3f.png)
![image](https://user-images.githubusercontent.com/34859558/163334152-7e66a659-e539-4478-b156-481077b55248.png)
![image](https://user-images.githubusercontent.com/34859558/163334291-f6941100-b1fc-41f4-9d94-cb6d89b6f4ff.png)

2022-04-14 07:26 UTC, shiyutang submitted a review, later dismissed
LGTM

2022-04-14 07:32 UTC, justld commented on test_tipc/configs/ccnet/train_infer_python.txt
> +python:python3.7
Donw

2022-04-15 01:32 UTC, michaelowenliu commented on configs/ccnet/README.md
> +> Huang, Zilong, et al. "CCNet: Criss-cross attention for semantic segmentation." Proceedings of the IEEE/CVF International Conference on Computer Vision. 2019.
Full authors list

2022-04-15 01:41 UTC, justld commented on configs/ccnet/README.md
> +> Huang, Zilong, et al. "CCNet: Criss-cross attention for semantic segmentation." Proceedings of the IEEE/CVF International Conference on Computer Vision. 2019.
Done

2022-04-15 03:33 UTC, shiyutang commented on test_tipc/configs/ccnet/train_infer_python.txt
> +random_infer_input:[{float32,[3,1024,2048]}]
benchmark参数可以删去

2022-04-15 03:36 UTC, justld commented on test_tipc/configs/ccnet/train_infer_python.txt
> +random_infer_input:[{float32,[3,1024,2048]}]
Done

2022-04-15 06:11 UTC, michaelowenliu approved these changes, later dismissed

2022-04-15 07:50 UTC, LutaoChu commented
同样需要在文档里补充模型信息

2022-04-15 07:55 UTC, justld commented
已添加

2022-04-15 08:08 UTC, michaelowenliu approved these changes

2022-04-15 08:08 UTC, merged