[Feature] Add PSANet
PaddlePaddle/PaddleSeg pull request #2022
Opened 2022-04-18 03:22 UTC by justld

添加PSANet，psamask C++外部算子
说明：自定义外部算子多卡训练时不知道为啥编译不通过（也没有日志），无奈使用单卡训练，约50个小时。psanet导出需要固定input_shape，否则psamask算子输出维度会丢失。故tipc中添加input_shape参数

2022-04-24 12:13 UTC, shiyutang requested changes
细节可以完善一下

2022-04-24 12:13 UTC, shiyutang commented on paddleseg/models/ops/__init__.py
> +from paddle.autograd import PyLayer
这两个似乎没有用上？

2022-04-24 12:13 UTC, shiyutang commented on paddleseg/models/psanet.py
> +import paddle
这一行上移带14吧

2022-04-24 12:13 UTC, shiyutang commented on paddleseg/models/psanet.py
> +            mask_h, mask_w)
这个格式看上去比较奇怪，重新用pre-commit跑一下？

2022-04-24 12:13 UTC, shiyutang commented on paddleseg/models/psanet.py
> +            normalization_factor = mask_h * mask_w
这一行直接self.normalization_factor = mask_h*mask_w?

2022-04-24 12:13 UTC, shiyutang commented on paddleseg/models/ops/psamask.cu
> +#define max(a,b) (((a) > (b)) ? (a) : (b))
@michaelowenliu 需要查看下增加op的位置和方式是否合理。

2022-04-24 12:38 UTC, shiyutang commented on paddleseg/models/ops/psamask.cu
> +#define max(a,b) (((a) > (b)) ? (a) : (b))
@juncaipeng 看下新增算子的实现方式呢？

2022-04-25 00:31 UTC, justld commented on paddleseg/models/psanet.py
> +            normalization_factor = mask_h * mask_w
这里和参考代码一致：https://github.com/hszhao/semseg/blob/4f274c3f276778228bc14a4565822d46359f0cc8/model/psanet.py#L20

2022-04-25 00:40 UTC, justld commented on paddleseg/models/ops/__init__.py
> +from paddle.autograd import PyLayer
已删除

2022-04-25 00:40 UTC, justld commented on paddleseg/models/psanet.py
> +            mask_h, mask_w)
跑过了，就是这样

2022-04-25 00:45 UTC, justld commented
训练：单卡Tesla V100 约50小时

2022-04-25 01:41 UTC, justld commented
![image](https://user-images.githubusercontent.com/41244687/165007036-c52625b8-ad89-4746-9047-142778f0860e.png)
![image](https://user-images.githubusercontent.com/41244687/165007053-45d0d80e-d518-49af-8d20-caaba10e4952.png)
![image](https://user-images.githubusercontent.com/41244687/165007089-8e2698e7-e6fa-4ef0-8c62-b7ae9dcadf0f.png)
![image](https://user-images.githubusercontent.com/41244687/165007111-1f3c0a5b-4750-468e-a1c3-6946feb6bc0b.png)
![image](https://user-images.githubusercontent.com/41244687/165007116-66ab48c8-9135-4994-b926-8480b15986d7.png)

test_tipc约3分钟，（导出的静态图预测与动态图不一致，见上方issue连接）

2022-04-25 01:43 UTC, justld commented
aistudio测试连接：https://aistudio.baidu.com/aistudio/projectdetail/3851842?contributionType=1

2022-04-25 01:44 UTC, justld commented on paddleseg/models/psanet.py
> +import paddle
已修改

2022-05-16 10:27 UTC, closed without merging