[Eager] Support all_reduce under eager mode
PaddlePaddle/PaddleSeg pull request #2170
Opened 2022-05-30 11:58 UTC by veyron95

paddle.distributed.all_reduce() 接口 在新老动态图行为不完全一致。

2022-05-30 12:39 UTC, JiabinYang submitted a review, later dismissed
LGTM

2022-05-30 13:02 UTC, michaelowenliu requested changes

2022-05-30 13:02 UTC, michaelowenliu commented on paddleseg/models/emanet.py
> +from paddle.fluid.framework import in_dygraph_mode, _in_legacy_dygraph
各套件已经禁止使用fluid api接口了

2022-05-31 06:12 UTC, veyron95 commented on paddleseg/models/emanet.py
> +from paddle.fluid.framework import in_dygraph_mode, _in_legacy_dygraph
已经移除 fluid 相关引入，Thx.

2022-05-31 07:20 UTC, haoyuying approved these changes
LGTM

2022-05-31 08:01 UTC, michaelowenliu approved these changes

2022-05-31 08:01 UTC, merged