论文复现34
PaddlePaddle/PaddleSeg pull request #2173
Opened 2022-05-30 13:43 UTC by marshall-dteach

2022-05-31 07:51 UTC, shiyutang requested changes
整体结构有了，但是建议很多细节需要完善，包含类的命名，网络组织结构，类的组织方式等

2022-05-31 07:51 UTC, shiyutang commented on paddleseg/cvlibs/config.py
> +import math
没有用到需要删去

2022-05-31 07:51 UTC, shiyutang commented on configs/psa/psa_hrnetv2_psa_cityscapes_1024x2048_520k.yml
> +_base_: '../_base_/cityscapes.yml'
没有使用到base config里的数据可以不用继承，同时 config的顺序可以调整为：
batch，trainset，valset，model， optimizer， lr——scheduler，loss

2022-05-31 07:51 UTC, shiyutang commented on paddleseg/cvlibs/config.py
> +            params.pop('power')
为什么要删去这两个

2022-05-31 07:51 UTC, shiyutang commented on paddleseg/models/backbones/__init__.py
> +from .ghostnet import *
不要修改这个

2022-05-31 07:51 UTC, shiyutang commented on paddleseg/models/backbones/hrnetv2_psa.py
> +class PSA_s(nn.Layer):
类命名采取驼峰命名方式，同时取名需要有意义

2022-05-31 07:51 UTC, shiyutang commented on paddleseg/models/backbones/hrnetv2_psa.py
> +class BasicBlock(nn.Layer):
这个和resnet的重名了

2022-05-31 07:51 UTC, shiyutang commented on paddleseg/models/backbones/__init__.py
> +from .hrnetv2_psa import *
只需要import  HRNETV2_PSA就可以

2022-05-31 07:51 UTC, shiyutang commented on paddleseg/models/backbones/hrnetv2_psa.py
> +class Bottleneck(nn.Layer):
是否可以直接利用这里的bottleneckBlock：https://github.com/PaddlePaddle/PaddleSeg/blob/9a358c0bc1e5e845e5127e1b7ad67df8cd4f1087/paddleseg/models/backbones/resnet_vd.py#L77

2022-05-31 07:51 UTC, shiyutang commented on paddleseg/models/backbones/hrnetv2_psa.py
> +        self.conv_v_left.inited = True
这四个重复的可以用循环写起来，另外为什么self。conv_up不需要init？

2022-05-31 07:51 UTC, shiyutang commented on paddleseg/models/layers/layer_libs.py
> +        return x
对于不常用的模块，可以直接放在models/psa.py中

2022-05-31 07:51 UTC, shiyutang commented on test_tipc/configs/psa/psa_cityscapes_1024x2048_520k.yml
> +    type: MscaleOCR
这个是什么？

2022-05-31 07:51 UTC, shiyutang commented on test_tipc/prepare.sh
> +        wget -nc -P $model_path https://bj.bcebos.com/paddleseg/dygraph/cityscapes/psa_hrnetv2_psa_cityscapes_1024x2048_520k/model.pdparams
这个模型已经上传了么？

2022-05-31 07:51 UTC, shiyutang commented on paddleseg/models/psa.py
> +class SpatialOCR_Module(nn.Layer):
类都需要使用驼峰命名的规范

2022-05-31 07:51 UTC, shiyutang commented on paddleseg/models/psa.py
> +        self.object_context_block = ObjectAttentionBlock(in_channels,
只有这一处用到了就不用写成一个类，不然太乱了

2022-05-31 07:51 UTC, shiyutang commented on paddleseg/models/psa.py
> +        return self.two_scale_forward(inputs)
目前模型写的太乱了，最好可以变成下面这样，把只用到了一次的模块变成类的静态方法，同时简单分为backbone，和head两个部分，在head里面再去做选择等。
<img width="642" alt="image" src="https://user-images.githubusercontent.com/34859558/171116891-15c98dac-e5d3-41c3-9af4-9537975fe70d.png">

2022-05-31 07:51 UTC, shiyutang commented on paddleseg/models/psa.py
> +class PSA(nn.Layer):
模型名字要完整，PSANet

2022-05-31 08:56 UTC, marshall-dteach commented on paddleseg/cvlibs/config.py
> +import math
您好，这个虽然看上去没用，但是在lr_lambda中加载的时候会用到math.ceil取整

2022-05-31 08:57 UTC, marshall-dteach commented on configs/psa/psa_hrnetv2_psa_cityscapes_1024x2048_520k.yml
> +_base_: '../_base_/cityscapes.yml'
收到

2022-05-31 08:58 UTC, marshall-dteach commented on paddleseg/cvlibs/config.py
> +            params.pop('power')
因为lambdadency里没有end_lr和power参数，如果不继承base，这里可以修改，免去删掉这两个

2022-05-31 08:59 UTC, marshall-dteach commented on paddleseg/models/backbones/__init__.py
> +from .ghostnet import *
这里是发生conflict了，等我把问题都弄懂之后，重新fork一下

2022-05-31 08:59 UTC, marshall-dteach commented on paddleseg/models/backbones/hrnetv2_psa.py
> +class PSA_s(nn.Layer):
收到

2022-05-31 08:59 UTC, marshall-dteach commented on paddleseg/models/backbones/hrnetv2_psa.py
> +class BasicBlock(nn.Layer):
收到，我会修改的

2022-05-31 09:12 UTC, marshall-dteach commented on paddleseg/models/psa.py
> +class PSA(nn.Layer):
收到

2022-05-31 09:13 UTC, marshall-dteach commented on paddleseg/models/psa.py
> +        return self.two_scale_forward(inputs)
好的，因为好多地方不是很懂，不太敢动，但我会尽量去改

2022-05-31 09:13 UTC, marshall-dteach commented on paddleseg/models/psa.py
> +        self.object_context_block = ObjectAttentionBlock(in_channels,
收到

2022-05-31 09:13 UTC, marshall-dteach commented on paddleseg/models/psa.py
> +class SpatialOCR_Module(nn.Layer):
收到

2022-05-31 09:13 UTC, marshall-dteach commented on test_tipc/prepare.sh
> +        wget -nc -P $model_path https://bj.bcebos.com/paddleseg/dygraph/cityscapes/psa_hrnetv2_psa_cityscapes_1024x2048_520k/model.pdparams
静态模型大于64M，直接加载没法加载，因此没上传，只修改了相应的文件

2022-05-31 09:14 UTC, marshall-dteach commented on test_tipc/prepare.sh
> +        wget -nc -P $model_path https://bj.bcebos.com/paddleseg/dygraph/cityscapes/psa_hrnetv2_psa_cityscapes_1024x2048_520k/model.pdparams
动态模型，我放在了百度网盘里，您需要的话分享给您

2022-05-31 09:14 UTC, marshall-dteach commented on test_tipc/configs/psa/psa_cityscapes_1024x2048_520k.yml
> +    type: MscaleOCR
这个文件好像是之前的，我记得删掉了，但不知为什么又给我push上来了，我删掉重新修改一下

2022-05-31 09:14 UTC, marshall-dteach commented on paddleseg/models/layers/layer_libs.py
> +        return x
收到

2022-05-31 09:16 UTC, marshall-dteach commented on paddleseg/models/backbones/hrnetv2_psa.py
> +        self.conv_v_left.inited = True
我改一下，这个conv_up的初始化我记得被注释了，我也好奇来着，我再看一下

2022-05-31 09:17 UTC, marshall-dteach commented on paddleseg/models/backbones/hrnetv2_psa.py
> +class Bottleneck(nn.Layer):
好的，我看一下

2022-05-31 09:17 UTC, marshall-dteach commented on paddleseg/models/backbones/__init__.py
> +from .hrnetv2_psa import *
收到

2022-05-31 09:22 UTC, marshall-dteach commented on paddleseg/models/backbones/hrnetv2_psa.py
> +        self.conv_v_left.inited = True
也可能是我改的时候误删了

2022-06-01 02:02 UTC, shiyutang commented on test_tipc/prepare.sh
> +        wget -nc -P $model_path https://bj.bcebos.com/paddleseg/dygraph/cityscapes/psa_hrnetv2_psa_cityscapes_1024x2048_520k/model.pdparams
没有上传这里就不用增加，链接是上传之后才有的

2022-06-01 02:13 UTC, shiyutang commented
修改完之后需要重新 re-request review或者微信提醒我 review， 从而进一步推进。

2022-06-01 02:15 UTC, shiyutang commented on paddleseg/cvlibs/config.py
> +import math
好的

2022-06-01 11:55 UTC, marshall-dteach commented on paddleseg/models/psa.py
> +        return self.two_scale_forward(inputs)
您好，我又看了下源代码，我的理解是涉及到多尺度，因此logits_list的内容涉及到相应的变化而并不是直接插值来的，我用_fwd函数区分了backbone和head两部分，如果直接改成实例代码类型forward中可能会更乱

2022-07-19 07:43 UTC, closed without merging