[Feature]Upernet
PaddlePaddle/PaddleSeg pull request #2175
Opened 2022-05-31 03:04 UTC by justld

添加upernet
resnet101 + upernet cityscapes 512x1024 miou 79.58%
参考实现mmsegmentation：https://github.com/open-mmlab/mmsegmentation/tree/master/configs/upernet
权重log vdl：链接：https://pan.baidu.com/s/1utlRZkDrw3ytB_GEUo7rKg 
提取码：lw0c

2022-05-31 04:10 UTC, justld commented
![image](https://user-images.githubusercontent.com/41244687/171090509-66ba1bb1-98b2-4aca-8f96-f4e66c52a17d.png)
![image](https://user-images.githubusercontent.com/41244687/171090525-888d217e-4f2f-45f1-b7cb-abd398e0ba9b.png)
![image](https://user-images.githubusercontent.com/41244687/171090833-3aeddd98-044b-418c-98c9-8e121b04d181.png)
![image](https://user-images.githubusercontent.com/41244687/171090873-027bc2e2-c519-4b3d-9ddb-56d9b77541c2.png)
![image](https://user-images.githubusercontent.com/41244687/171091085-e6fce421-7140-4bc8-a6b4-3645c21077ae.png)
tipc大概8分钟

2022-05-31 07:57 UTC, shiyutang requested changes
是否进行重新训练验证精度？如已经验证可以发给我模型日志和vdl用于上传，同时需要在这里增加tipc的文档说明：https://github.com/PaddlePaddle/PaddleSeg/blob/release%2F2.5/test_tipc/README.md

2022-05-31 07:57 UTC, shiyutang commented on paddleseg/models/upernet.py
> +        #     return logits_list
注释

2022-05-31 08:02 UTC, justld commented on paddleseg/models/upernet.py
> +        #     return logits_list
已修改，已添加

2022-05-31 08:05 UTC, justld commented
这是用PR的代码训练的结果，权重日志vdl均已发送。

2022-05-31 09:04 UTC, shiyutang approved these changes, later dismissed
LGTM

2022-06-01 02:14 UTC, juncaipeng commented on paddleseg/models/upernet.py
> +        fpn_inplanes = self.backbone.feat_channels
这里不能直接把feat_channels作为fpn_inplanes，万一backbone的feat_channels个数不是4个，或者改变了输入的backbone_indices。应该根据backbone_indices来选出fpn_inplanes。

2022-06-01 02:33 UTC, justld commented on paddleseg/models/upernet.py
> +        fpn_inplanes = self.backbone.feat_channels
已修改，feat_channels不是4可正常训练。

2022-06-01 02:40 UTC, LutaoChu commented on test_tipc/configs/upernet/train_infer_python.txt
> +--precision:fp32|int8|fp16
--enable_mkldnn:True
--cpu_threads:6
--batch_size:1
--use_trt:False
--precision:fp32
改成这样，减少运行时间

2022-06-01 02:40 UTC, LutaoChu commented on test_tipc/configs/upernet/train_infer_python.txt
> +--iters:lite_train_lite_infer=50|lite_train_whole_infer=50|whole_train_whole_infer=1000
改成这样
--iters:lite_train_lite_infer=20|lite_train_whole_infer=20|whole_train_whole_infer=1000

2022-06-01 02:42 UTC, LutaoChu commented
> ![image](https://user-images.githubusercontent.com/41244687/171090509-66ba1bb1-98b2-4aca-8f96-f4e66c52a17d.png) ![image](https://user-images.githubusercontent.com/41244687/171090525-888d217e-4f2f-45f1-b7cb-abd398e0ba9b.png) ![image](https://user-images.githubusercontent.com/41244687/171090833-3aeddd98-044b-418c-98c9-8e121b04d181.png) ![image](https://user-images.githubusercontent.com/41244687/171090873-027bc2e2-c519-4b3d-9ddb-56d9b77541c2.png) ![image](https://user-images.githubusercontent.com/41244687/171091085-e6fce421-7140-4bc8-a6b4-3645c21077ae.png) tipc大概8分钟

计时需要包括prepare.sh和test_train_inference_python.sh，这边没统计到prepare耗时，在10min中跑完

2022-06-01 05:17 UTC, justld commented
![image](https://user-images.githubusercontent.com/41244687/171332319-6a9c00a5-9db0-4e5c-b6b2-cd6e2c60b072.png)
![image](https://user-images.githubusercontent.com/41244687/171332350-17c62ccb-8c29-4055-88c4-8c272bed9121.png)
![image](https://user-images.githubusercontent.com/41244687/171332358-93f45c77-9fa3-4c39-bbc4-d36377fc759b.png)
![image](https://user-images.githubusercontent.com/41244687/171332742-20bd251b-0fb4-4a10-96ab-b32e70b15329.png)
![image](https://user-images.githubusercontent.com/41244687/171332753-f13bf0eb-912b-42d6-9441-c08bbbc3a2b8.png)
![image](https://user-images.githubusercontent.com/41244687/171332796-8099c318-9eff-4379-ab2d-41cc00d840b5.png)
不包含下载数据集时间，tipc7分钟左右

2022-06-01 05:17 UTC, justld commented on test_tipc/configs/upernet/train_infer_python.txt
> +--iters:lite_train_lite_infer=50|lite_train_whole_infer=50|whole_train_whole_infer=1000
已修改

2022-06-01 06:19 UTC, shiyutang approved these changes
已经检查要求修改部分，已经修改完成，LGTM

2022-06-01 06:34 UTC, juncaipeng approved these changes
LGTM

2022-06-01 10:33 UTC, justld commented on test_tipc/configs/upernet/train_infer_python.txt
> +--precision:fp32|int8|fp16
已修改

2022-06-02 07:12 UTC, merged