论文复现34再次修改后的
PaddlePaddle/PaddleSeg pull request #2182
Opened 2022-06-01 13:42 UTC by marshall-dteach

2022-06-02 06:53 UTC, marshall-dteach commented
1. 您昨天说的网络结构很乱，我看过了感觉不好改，我在_fwd里将head和backbone分开了，但是因为涉及到多尺度，返回的结果都是经过不同操作得来的，很难用列表推导式写在一块。
2. 用Resnet中的bottleck模块替代bottleck也不可取，因为我的那个bottleck涉及到了下采样，与Resnet中的不同，个人感觉如果用其替换还得一部分重构，没大有必要
3.  其余问题都已经解决

2022-06-02 07:04 UTC, marshall-dteach commented
另外，想探讨下：
1. paddleseg的lr_schedule.step()为什么是每个iter执行，而非epoch呢？
2. 对于lambdadecay的lr_lambda参数是否换种输入方式，是否更好呢？（直接输函数冒号与yml文件冲突）
3. 对于RMILoss，forward涉及到需要输入的参数，将其提到_init__输入是否更好？为便于直接用yml文件调用，类似的损失函数可以尽量把forward中的可选参数都移动到__Init__中呢？

2022-06-06 12:01 UTC, shiyutang requested changes
网络结构待运行后验证。

2022-06-06 12:01 UTC, shiyutang commented on configs/psa/psa_hrnetv2_psa_cityscapes_1024x2048_520k.yml
> +  lr_lambda: 'lambda iter, (1-math.ceil(iter/2975)/175)**2'
可以直接把这个变成一个固定的函数 （1-math.ceil(iter/len(dataset))/param)**2，然后用iter，len(dataset), param三个参数传入。

2022-06-06 12:01 UTC, shiyutang commented on paddleseg/cvlibs/config.py
> +import math
去除math

2022-06-06 12:01 UTC, shiyutang commented on paddleseg/cvlibs/config.py
> +            params['lr_lambda'] = eval(params['lr_lambda'].replace(',', ':'))
不使用eval，会带来安全风险，替换为参数化函数

2022-06-06 12:01 UTC, shiyutang commented on paddleseg/models/backbones/__init__.py
> +from .ghostnet import *
不要修改这个

2022-06-06 12:01 UTC, shiyutang commented on test_tipc/prepare.sh
> +    fi
为什么要增加这些

2022-06-06 12:01 UTC, shiyutang commented on test_tipc/prepare.sh
> +fi
不必要的修改最好去除，否则不够清晰，代码中还有其他几处也是同理

2022-06-06 12:01 UTC, shiyutang commented on test_tipc/configs/psa/train_infer_python.txt
> +--iters:lite_train_lite_infer=50|lite_train_whole_infer=50|whole_train_whole_infer=1000
改成：--iters:lite_train_lite_infer=20|lite_train_whole_infer=20|whole_train_whole_infer=1000

2022-06-06 12:01 UTC, shiyutang commented on test_tipc/configs/psa/psa_hrnetv2_psa_cityscapes_1024x2048_520k.yml
> +  lr_lambda: 'lambda iter, (1-math.ceil(iter/2975)/175)**2'
也替换一下～

2022-06-06 12:01 UTC, shiyutang commented on paddleseg/transforms/transforms.py
> +class RandomSizeAndCrop(object):
不用继承object

2022-06-06 12:01 UTC, shiyutang commented on paddleseg/transforms/transforms.py
> +        target_h, target_w = self.size  # ASSUME H, W
可以指定不同的data-format

2022-06-06 12:01 UTC, shiyutang commented on paddleseg/transforms/transforms.py
> +                target_h, target_w = shorter_side, shorter_side
这里的尺度和描述不符， 如果小，尺寸就变成了以图像短边形成的正方形，而不是变成合图像尺度一致

2022-06-06 12:01 UTC, shiyutang commented on paddleseg/transforms/transforms.py
> +@manager.TRANSFORMS.add_component
实现效果感觉和https://github.com/PaddlePaddle/PaddleSeg/blob/7ae2e866f2e5345e8631fe2444d83db3d967be27/paddleseg/transforms/transforms.py#L608 一致，建议直接复用

2022-06-06 12:01 UTC, shiyutang commented on paddleseg/transforms/transforms.py
> +        w, h = [int(i * scale_amt) for i in img.size]
最好尝试使用https://github.com/PaddlePaddle/PaddleSeg/blob/7ae2e866f2e5345e8631fe2444d83db3d967be27/paddleseg/transforms/transforms.py#L706
替换，二者逻辑相似，避免不必要的重复代码

2022-06-06 14:16 UTC, marshall-dteach commented on paddleseg/models/backbones/__init__.py
> +from .ghostnet import *
哈哈哈我没改这个，我就把冲突对应的 === 和>>>删掉，就显示我改了

2022-06-06 14:26 UTC, marshall-dteach commented on test_tipc/prepare.sh
> +    fi
这是解决conflict的时候增加的，好像是有人提了加这些的pr还是paddleseg已经更新了？我没弄明白

2022-06-06 14:26 UTC, marshall-dteach commented on paddleseg/models/backbones/__init__.py
> +from .ghostnet import *
哈哈哈我没改这个，我就把冲突对应的 === 和>>>删掉，就显示我改了

2022-06-07 02:16 UTC, juncaipeng reviewed
该模型实现是否有参考其他repo？如果实现类似，需要说明出处。

2022-06-07 02:16 UTC, juncaipeng commented on configs/psa/README.md
> +> Huajun Liu12, Fuqiang Liu2, Xinyi Fan1 and Dong Huang. "BiSeNet: Polarized Self-Attention: Towards High-quality Pixel-wise Regression." arXiv preprint arXiv:2107.00782v2 (2021).
删掉BiSeNet:

2022-06-07 02:16 UTC, juncaipeng commented on configs/psa/psa_hrnetv2_psa_cityscapes_1024x2048_520k.yml
> +      std: [0.229, 0.224, 0.225]
mean和std使用0.5

2022-06-07 02:16 UTC, juncaipeng commented on configs/psa/psa_hrnetv2_psa_cityscapes_1024x2048_520k.yml
> +      std: [0.229, 0.224, 0.225]
mean和std使用0.5

2022-06-07 02:16 UTC, juncaipeng commented on configs/psa/psa_hrnetv2_psa_cityscapes_1024x2048_520k.yml
> +iters: 520000
超参设置太奇怪，整个配置参考其他模型的配置进行修改。

2022-06-07 02:16 UTC, juncaipeng commented on paddleseg/cvlibs/config.py
> +            #将所需函数参数化
不要使用中文注释

2022-06-08 06:56 UTC, shiyutang commented
评估精度符合预期：
![image](https://user-images.githubusercontent.com/34859558/172549879-2ed45765-a2fa-4a09-aa5e-2111f09a3111.png)

2022-06-08 07:32 UTC, shiyutang commented on paddleseg/models/psanet.py
> +                 preteained=None):
pretrained

2022-06-08 07:49 UTC, shiyutang commented on paddleseg/models/psanet.py
> +            utils.load_entire_model(self, self.pretrained)
骨干网络也采取这样的加载方式，才能知道加载成功与否

2022-06-08 07:51 UTC, shiyutang commented on paddleseg/models/backbones/hrnetv2_psa.py
> +            self.load_dict(model_dict)
修改权重加载方式，按照util.load_entire_model或者迁移其中参数加载数量计数部分代码

2022-06-08 07:59 UTC, shiyutang requested changes
1. 不要删除README
2. 不要直接上传log
我交流的操作是在你自己的repo中，可以单独建立一个分支，而不要体现在PR中。

2022-06-08 08:14 UTC, marshall-dteach commented
> 1. 不要删除README
> 2. 不要直接上传log
>    我交流的操作是在你自己的repo中，可以单独建立一个分支，而不要体现在PR中。

我把log删了，把readme都重新上传上来了

2022-06-09 12:07 UTC, shiyutang requested changes
1.不要修改README：
<img width="387" alt="image" src="https://user-images.githubusercontent.com/34859558/172843003-57a2b7ee-0ba0-4c1d-91aa-fd2fd7680a5a.png">

2. 代码需要先用precommit进行格式修改，不然不能合入。参考：https://github.com/PaddlePaddle/PaddleSeg/blob/develop/docs/pr/pr/pr.md#4-use-pre-commit-hook

2022-06-13 09:12 UTC, shiyutang commented
@marshall-dteach 训练了四天后精度不达标，建议重新提交下你修改可以的代码：
<img width="799" alt="image" src="https://user-images.githubusercontent.com/34859558/173320730-ffcaf024-5532-4a23-931f-4b3d3cf880b4.png">

2022-07-19 07:43 UTC, closed without merging