add load model shufflenet
PaddlePaddle/PaddleSeg pull request #229
Opened 2020-04-29 12:06 UTC by wuyefeilin

2020-05-06 14:09 UTC, ZeyuChen requested changes
按照建议修改

2020-05-06 14:09 UTC, ZeyuChen commented on contrib/HumanSeg/deploy/python/README.md
> +1. 仅测试过Paddle1.6 和 1.7, 其它版本不支持
这一话术不合适，直接写明PaddlePaddle 1.7以上版本即可。

2020-05-06 14:09 UTC, ZeyuChen commented on contrib/HumanSeg/deploy/python/README.md
> +- Python 3.0+
应该是Python 3.6+

2020-05-06 14:09 UTC, ZeyuChen commented on contrib/HumanSeg/deploy/python/README.md
> +3. Python2上未测试
与前面Python 3.6+表意重复，没必要。

2020-05-06 14:09 UTC, ZeyuChen commented on contrib/HumanSeg/deploy/python/README.md
> +
可以去掉

2020-05-06 14:09 UTC, ZeyuChen commented on contrib/HumanSeg/deploy/python/README.md
> +然后在前面的预测命令中增加参数`--use_gpu 1`即可。
不应该是用--use_gpu 1, 可否改为bool变量

2020-05-06 14:09 UTC, ZeyuChen commented on contrib/HumanSeg/deploy/python/infer.py
> +def human_seg_track_fuse(track_cfd, dl_cfd, dl_weights, is_track):
human_seg -> humanseg

2020-05-06 14:09 UTC, ZeyuChen commented on contrib/HumanSeg/deploy/python/infer.py
> +def predict_image(seg, image_path):
建议函数名为 image_segment

2020-05-06 14:09 UTC, ZeyuChen commented on contrib/HumanSeg/deploy/python/infer.py
> +def predict_video(seg, video_path):
建议函数名为 video_segment

2020-05-06 14:09 UTC, ZeyuChen commented on contrib/HumanSeg/deploy/python/infer.py
> +def predict_camera(seg):
是否可以与video segment接口公用，通过新增一个参数开关选择是否使用摄像头？

2020-05-06 14:09 UTC, ZeyuChen commented on contrib/HumanSeg/deploy/python/infer_resizebylong.py
> +def human_seg_tracking(pre_gray, cur_gray, prev_cfd, dl_weights, disflow):
human_seg -> humanseg

2020-05-06 14:09 UTC, ZeyuChen commented on contrib/HumanSeg/models/humanseg.py
> +class HRNet(HumanSegMobile):
这一继承关系有点奇怪，为什么是HRNet基于HumanSegMobile？

2020-05-06 14:09 UTC, ZeyuChen commented on contrib/HumanSeg/tutorial/train_demo.py
> +data_dir = '/ssd1/chenguowei01/dataset/humanseg/supervise.ly'
后续改为相对路径，让用户在humanseg目录下可以闭环完成。

2020-05-06 14:09 UTC, ZeyuChen commented on contrib/HumanSeg/models/humanseg.py
> +        self.status = 'Normal'
Model Status作何解释？

2020-05-06 14:09 UTC, ZeyuChen commented on contrib/HumanSeg/deploy/python/infer_resizebylong.py
> +        predict_camera(seg)
应该把image_segment 和 video_segment这两个功能封装进基类。
model = HumanSeg(model_dir, mean, scale, long_size, use_gpu)
model.video_segment(xxxx),  如果path=None则默认打开摄像头

2020-05-07 03:17 UTC, wuyefeilin commented on contrib/HumanSeg/deploy/python/README.md
> +然后在前面的预测命令中增加参数`--use_gpu 1`即可。
可以

2020-05-07 03:25 UTC, wuyefeilin commented on contrib/HumanSeg/models/humanseg.py
> +        self.status = 'Normal'
selt.status是因为加载模型时，模型可能来自于导出模型，还有互训的量化模型等，这个变量7⃣️区别的作用，Normal表示正常训练保存的模型，Infer表示导出模型，quant表示量化模型，后续还会有裁剪模型，不同模型的加载有所不同

2020-05-07 03:30 UTC, wuyefeilin commented on contrib/HumanSeg/models/humanseg.py
> +class HRNet(HumanSegMobile):
这边将弄一个基类，后续所有的分割模型都直接继承自基类

2020-05-07 07:17 UTC, wuyefeilin commented on contrib/HumanSeg/deploy/python/infer_resizebylong.py
> +        predict_camera(seg)
已更改

2020-05-07 07:20 UTC, wuyefeilin commented on contrib/HumanSeg/tutorial/train_demo.py
> +data_dir = '/ssd1/chenguowei01/dataset/humanseg/supervise.ly'
这边只是初步的示例，后续将弄成数据集下载并启动训练的格式

2020-05-08 14:16 UTC, ZeyuChen approved these changes
LGTM

2020-05-08 14:17 UTC, merged