[Doc] add quick start
PaddlePaddle/PaddleSeg pull request #2306
Opened 2022-07-08 09:08 UTC by juncaipeng

2022-07-14 08:35 UTC, shiyutang requested changes

2022-07-14 08:35 UTC, shiyutang commented on docs/quick_start_cn.md
> +上述模型训练、评估、训练完后，就可以导出并部署预测模型了，具体请参考PaddleSeg的详细文档。
可以参见PaddleSeg readme，给出链接？

2022-07-14 08:35 UTC, shiyutang commented on docs/data/transform/transform_cn.md
> +## 1. 安装LabelMe
是否需要使用labelme标注，还是只推广使用EISeg的文档呢？

2022-07-14 08:35 UTC, shiyutang commented on docs/data/pre_data.md
> +
这部分是不是加到data-prepare 呢？https://github.com/shiyutang/PaddleSeg/blob/release%2F2.5/docs/data_prepare.md

2022-07-15 02:57 UTC, juncaipeng commented on docs/quick_start_cn.md
> +上述模型训练、评估、训练完后，就可以导出并部署预测模型了，具体请参考PaddleSeg的详细文档。
Quick start里面不提供链接了，让大家简单了解就好。

2022-07-15 02:58 UTC, juncaipeng commented on docs/data/transform/transform_cn.md
> +## 1. 安装LabelMe
两个都提供吧，分成两个文档了，EISeg的文档在readme中突显了。

2022-07-15 03:45 UTC, juncaipeng commented on docs/data/pre_data.md
> +
整合了两个文档

2022-07-15 06:29 UTC, merged