Optimize data clip and normalize method and add README.md for remote sensing
PaddlePaddle/PaddleSeg pull request #233
Opened 2020-05-06 13:40 UTC by LutaoChu

1 针对遥感数据优化了归一化方法，新增了数据范围裁剪功能。
2 新增遥感README

2020-05-06 14:12 UTC, ZeyuChen requested changes
文档和使用流程不清晰

2020-05-06 14:12 UTC, ZeyuChen commented on contrib/RemoteSensing/README.md
> +os.environ['CUDA_VISIBLE_DEVICES'] = "0"
这段使用说明太复杂了

2020-05-06 14:12 UTC, ZeyuChen commented on contrib/RemoteSensing/transforms/transforms.py
> +    def __init__(self, max_val=255.0, mean=[0.5, 0.5, 0.5], std=[0.5, 0.5,
多通道的情况下还能使用三通道的mean吗？

2020-05-06 14:12 UTC, ZeyuChen commented on contrib/RemoteSensing/README.md
> +也可以使用`RemoteSensing`目录下提供的api构建您自己的分割代码。
不合适，还是搞不明白怎么用。

2020-05-07 02:56 UTC, LutaoChu commented on contrib/RemoteSensing/README.md
> +os.environ['CUDA_VISIBLE_DEVICES'] = "0"
这里只有6个配置项，感觉已经很简单了。应该怎么改呢？

2020-05-07 02:56 UTC, LutaoChu commented on contrib/RemoteSensing/README.md
> +也可以使用`RemoteSensing`目录下提供的api构建您自己的分割代码。
我再补充一些api的使用说明

2020-05-07 02:56 UTC, LutaoChu commented on contrib/RemoteSensing/transforms/transforms.py
> +    def __init__(self, max_val=255.0, mean=[0.5, 0.5, 0.5], std=[0.5, 0.5,
3通道的mean是默认值。多通道情况会按main.py中传入的通道数，用多通道的mean

2020-05-07 12:27 UTC, LutaoChu commented on contrib/RemoteSensing/README.md
> +os.environ['CUDA_VISIBLE_DEVICES'] = "0"
添加了代码块说明，流程更清晰

2020-05-07 12:27 UTC, LutaoChu commented on contrib/RemoteSensing/README.md
> +也可以使用`RemoteSensing`目录下提供的api构建您自己的分割代码。
目前补充了transform的api说明，后续再补充其他的

2020-05-08 07:12 UTC, ZeyuChen requested changes
不要拆分standarize接口，没有这种说法。

2020-05-08 07:12 UTC, ZeyuChen commented on contrib/RemoteSensing/transforms/ops.py
> +def standardize(im, mean, std):
不用拆分函数，和normalize合在一起。

2020-05-11 08:50 UTC, ZeyuChen approved these changes
LGTM

2020-05-11 08:50 UTC, merged