[Fix][MedicalSeg] Fix MedicalSeg TIPC bugs
PaddlePaddle/PaddleSeg pull request #2424
Opened 2022-08-09 16:41 UTC by Bobholamovic

### 主要改动

重写了MedicalSeg部分的TIPC脚本，解决先前存在的如`${model_name}`提取行号不正确、大量配置文件选项被绕过且未给出任何警告、inference部分不记录执行状态等问题。

目前MedicalSeg部分的TIPC脚本与PaddleSeg主仓库TIPC脚本（只比较基础训推链条）存在的主要区别如下：
1. MedicalSeg的TIPC脚本不包含[`parse_extra_args()`](https://github.com/PaddlePaddle/PaddleSeg/blob/5aad8d59d2f34f1975d62507a743eaa53e6c5555/test_tipc/test_train_inference_python.sh#L133)功能；
2. MedicalSeg的TIPC脚本不支持AMP训练，因此配置文件中指定的`--precision`选项会被绕过，并给出一条警告；
3. 模型导出和推理使用的是`best_model/`子目录下的模型，而不是最后一次迭代对应的模型；
4. UNETR模型在训练时只使用单卡，推理时不使用CPU，也不启用MKL-DNN。

其中第2、3、4条是为了使修改后的脚本与修改前执行效果一致；第1条则是考虑到目前MedicalSeg的TIPC脚本还无需添加`parse_extra_args()`这样较为复杂的功能。

### 其它改动

修复了MedicalSeg中一部分脚本存在的格式问题。

### 待解决问题

在调试中发现UNETR的TIPC部分存在如下问题：
1. 验证时需要的内存太大，动态图跑eval的话1块16G的V100也不够用；
2. 无法支持MKL-DNN，若强行启用会报卷积输入形状错误。

2022-08-10 11:35 UTC, shiyutang requested changes
如果验证通过的话，能否提供训练、评估、导出、infer的截图呢？

2022-08-10 11:35 UTC, shiyutang commented on contrib/MedicalSeg/test_tipc/common_func.sh
> +
这个函数在哪里使用了呢？

2022-08-10 11:35 UTC, shiyutang commented on contrib/MedicalSeg/test_tipc/configs/unetr/train_infer_python.txt
> +--save_dir:./test_tipc//result/unetr/
//是否也修改下？

2022-08-10 11:35 UTC, shiyutang commented on contrib/MedicalSeg/test_tipc/common_func.sh
> +}
这个函数没有使用？

2022-08-10 14:03 UTC, Bobholamovic commented on contrib/MedicalSeg/test_tipc/common_func.sh
> +}
已删除，原因同`func_parser_value_cpp`。

2022-08-10 14:03 UTC, Bobholamovic commented on contrib/MedicalSeg/test_tipc/configs/unetr/train_infer_python.txt
> +--save_dir:./test_tipc//result/unetr/
done.

2022-08-10 14:03 UTC, Bobholamovic commented on contrib/MedicalSeg/test_tipc/common_func.sh
> +
拷贝Seg的脚本的时候忘记删除了~ 已删除。

2022-08-10 14:14 UTC, Bobholamovic commented
训练、评估、导出、推理截图分别如下：

![](https://user-images.githubusercontent.com/21275753/183922676-9b7a3207-baff-498a-b439-d64f513e155f.png)
![](https://user-images.githubusercontent.com/21275753/183923557-007f6e4a-8990-40a6-bf6a-424e6cb8d1ea.png)
![](https://user-images.githubusercontent.com/21275753/183923493-339d3d10-7f70-47a1-a171-bd3e98d98ac0.png)

2022-08-10 14:15 UTC, Bobholamovic commented
训练、评估、导出、推理截图分别如下：

![](https://user-images.githubusercontent.com/21275753/183922676-9b7a3207-baff-498a-b439-d64f513e155f.png)
![](https://user-images.githubusercontent.com/21275753/183923557-007f6e4a-8990-40a6-bf6a-424e6cb8d1ea.png)
![](https://user-images.githubusercontent.com/21275753/183923493-339d3d10-7f70-47a1-a171-bd3e98d98ac0.png)

2022-08-11 07:08 UTC, shiyutang approved these changes
LGTM

2022-08-11 07:08 UTC, merged