[Feature] Add TopFormer model
PaddlePaddle/PaddleSeg pull request #2472
Opened 2022-08-22 12:06 UTC by juncaipeng

2022-08-29 08:44 UTC, shiyutang requested changes

2022-08-29 08:44 UTC, shiyutang commented on configs/topformer/topformer_base_ade20k_512x512_160k.yml
> +batch_size: 8  # total is 16
# total is 16 ？

2022-08-29 08:44 UTC, shiyutang commented on configs/topformer/topformer_base_ade20k_512x512_160k.yml
> +      std: [0.229, 0.224, 0.225]
config file 各个模块之间有顺序要求，可以参考https://github.com/PaddlePaddle/PaddleSeg/blob/release%2F2.6/configs/_base_/cityscapes.yml

2022-08-29 08:44 UTC, shiyutang commented on paddleseg/models/backbones/top_transformer.py
> +from paddleseg.models.backbones.transformer_utils import Identity, DropPath
paddle 2.3已经支持Identity了

2022-08-29 08:44 UTC, shiyutang commented on paddleseg/models/backbones/top_transformer.py
> +                 lr_mult=1.0):
这里的bn没有使用syncbn，在多卡训练性能会存在差异。可以参考：https://github.com/PaddlePaddle/PaddleSeg/blob/5a154b7689b5963591cf8b0bce0669bfc8c7f53e/paddleseg/models/layers/layer_libs.py#L59

2022-08-29 08:44 UTC, shiyutang commented on paddleseg/models/backbones/top_transformer.py
> +        return out
没有使用？

2022-08-29 08:44 UTC, shiyutang commented on paddleseg/models/backbones/top_transformer.py
> +        return out
没有使用？

2022-08-29 08:44 UTC, shiyutang commented on paddleseg/transforms/functional.py
> +    rescaled_size = [round(i * scale) for i in img_size]
这样resize是最小缩放，却不是贴合某一边，输出结果是否是符合期望的？

2022-08-29 08:44 UTC, shiyutang commented on paddleseg/models/topformer.py
> +        x = self.backbone(x)  # len=3, 1/8,1/16,1/32
多余的注释

2022-08-29 08:44 UTC, shiyutang commented on paddleseg/models/topformer.py
> +            if output_h > input_h or output_w > output_h:
看不太出具体要实现的功能，感觉可以写点注释， 但是“output_w > output_h”这个对应是对的么？

2022-08-29 11:25 UTC, juncaipeng commented on configs/topformer/topformer_base_ade20k_512x512_160k.yml
> +      std: [0.229, 0.224, 0.225]
Done

2022-08-29 11:25 UTC, juncaipeng commented on paddleseg/models/topformer.py
> +        x = self.backbone(x)  # len=3, 1/8,1/16,1/32
这个留下以便注意差异，这个backbone只返回3个feature map

2022-08-29 11:25 UTC, juncaipeng commented on paddleseg/models/topformer.py
> +            if output_h > input_h or output_w > output_h:
删除了

2022-08-29 11:25 UTC, juncaipeng commented on paddleseg/transforms/functional.py
> +    rescaled_size = [round(i * scale) for i in img_size]
这个不必要贴合特定size

2022-08-29 11:25 UTC, juncaipeng commented on paddleseg/models/backbones/top_transformer.py
> +from paddleseg.models.backbones.transformer_utils import Identity, DropPath
为了支持paddle2.2，暂时先用我们自己实现的，后续统一替换。

2022-08-29 11:25 UTC, juncaipeng commented on paddleseg/models/backbones/top_transformer.py
> +                 lr_mult=1.0):
在train.py中多卡训练会统一进行转换bn为sync_bn： https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.6/train.py#L204

2022-08-29 11:25 UTC, juncaipeng commented on paddleseg/models/backbones/top_transformer.py
> +        return out
已经修改使用

2022-08-29 11:25 UTC, juncaipeng commented on paddleseg/models/backbones/top_transformer.py
> +        return out
同上

2022-08-30 07:03 UTC, shiyutang requested changes
有很多细节问题和repo的规范不一致。

2022-08-30 07:03 UTC, shiyutang commented on paddleseg/models/backbones/top_transformer.py
> +            [F.adaptive_avg_pool2d(inp, (H, W)) for inp in inputs], axis=1)
这里注释应该是解释这个模块，这部分说明放在这里有些奇怪，这个文件中还有许多其他的注释需要查看是否删除。

2022-08-30 07:03 UTC, shiyutang commented on paddleseg/models/backbones/top_transformer.py
> +                 ks,
这些命名都有些随意，变量可以用半驼峰或者下划线命名，该文件中许多类似的命名

2022-08-30 07:03 UTC, shiyutang commented on paddleseg/models/backbones/top_transformer.py
> +        self._is_cn = stride > 1
这个变量没有使用

2022-08-30 07:03 UTC, shiyutang commented on paddleseg/models/backbones/top_transformer.py
> +        self.expand_ratio = expand_ratio
这两个类变量也没有使用

2022-08-30 07:03 UTC, shiyutang commented on paddleseg/models/backbones/top_transformer.py
> +        assert stride in [1, 2]
没有报错信息

2022-08-30 07:03 UTC, shiyutang commented on paddleseg/models/backbones/top_transformer.py
> +        assert stride in [1, 2]
没有报错信息

2022-08-30 07:03 UTC, shiyutang commented on paddleseg/models/topformer.py
> +    return F.interpolate(input_data, size, scale_factor, mode, align_corners)
为什么需要写一个单独的函数

2022-08-30 08:28 UTC, juncaipeng reviewed
这个Backbone是参考官方源码实现，已经优化了输入参数的命名。

2022-08-30 08:28 UTC, juncaipeng commented on paddleseg/models/backbones/top_transformer.py
> +            [F.adaptive_avg_pool2d(inp, (H, W)) for inp in inputs], axis=1)
就是保留以便大家需要支持任意输入的模型。

2022-08-30 08:28 UTC, juncaipeng commented on paddleseg/models/backbones/top_transformer.py
> +            [F.adaptive_avg_pool2d(inp, (H, W)) for inp in inputs], axis=1)
其他无用注释已经删除。

2022-08-30 08:29 UTC, juncaipeng commented on paddleseg/models/topformer.py
> +    return F.interpolate(input_data, size, scale_factor, mode, align_corners)
已经修改。

2022-08-30 08:29 UTC, juncaipeng commented on paddleseg/models/backbones/top_transformer.py
> +        assert stride in [1, 2]
都添加了。

2022-08-30 08:29 UTC, juncaipeng commented on paddleseg/models/backbones/top_transformer.py
> +        self.expand_ratio = expand_ratio
无用变量删除了。

2022-08-30 09:47 UTC, shiyutang approved these changes
LGTM

2022-08-30 09:48 UTC, merged