[Enhancement] Check and sync the num_classes in Config class
PaddlePaddle/PaddleSeg pull request #2477
Opened 2022-08-23 13:30 UTC by juncaipeng

2022-08-24 07:17 UTC, shiyutang requested changes
需要再确认全局都已经没有config_check

2022-08-24 07:17 UTC, shiyutang commented on paddleseg/cvlibs/config.py
> +        if self.train_dataset_config:
上面已经排除了两个config都必须有，那么是否还需要这个if

2022-08-24 07:17 UTC, shiyutang commented on paddleseg/cvlibs/config.py
> +        if self.train_dataset_config and \
这里对config的检查同上意见，似乎不太需要？

2022-08-24 07:19 UTC, shiyutang requested changes

2022-08-24 07:19 UTC, shiyutang commented on contrib/MedicalSeg/train.py
>          cfg.model,
test/train/eval 都需要增加sync_infor确认信息同步。

2022-08-24 07:29 UTC, juncaipeng commented on paddleseg/cvlibs/config.py
> +        if self.train_dataset_config:
上面的if判断是必须提供一个train_dataset_config或者val_dataset_config，所以下面if是需要的。

2022-08-24 07:29 UTC, juncaipeng commented on paddleseg/cvlibs/config.py
> +        if self.train_dataset_config and \
同上

2022-08-24 07:29 UTC, juncaipeng commented on contrib/MedicalSeg/train.py
>          cfg.model,
我看了medicalseg中所有配置文件都提供了num_classes，而且medicalseg是使用自己定义的Config类，所以就没大改这里面的。

2022-08-24 10:24 UTC, wuyefeilin commented on paddleseg/cvlibs/config.py
> +            )
在matting里不存在num_classes概念，是否能正常运行呢

2022-08-24 10:24 UTC, wuyefeilin commented on paddleseg/cvlibs/config.py
> +                num_classes_set.add(self.val_dataset_config['num_classes'])
这里是否存在必须构建val_dataset或者train_dataset呢，如果存在的话，执行predict.py时当dataset_root不存在能否正常运行呢？原来是报FileNotFoundError时给个警告而非报错

2022-08-24 11:14 UTC, juncaipeng commented on paddleseg/cvlibs/config.py
> +                num_classes_set.add(self.val_dataset_config['num_classes'])
这里只考虑config文件中信息的同步，如果train_dataset和val_dataset构建不成功，那就会另外报错啊
<img width="519" alt="image" src="https://user-images.githubusercontent.com/52520497/186404517-5341be5e-b047-4171-95f4-c69abeaad1a3.png">

2022-08-24 11:14 UTC, juncaipeng commented on paddleseg/cvlibs/config.py
> +            )
matting中之前也没有调用config_check函数，所以现在修改后，matting下面的cfg示例没调用check_sync_info函数，所以不影响matting的代码。

2022-08-25 09:00 UTC, wuyefeilin commented on paddleseg/cvlibs/config.py
> +                num_classes_set.add(self.val_dataset_config['num_classes'])
predict.py不需要构建val_dataset或train_dataset就应正常预测，如果会报错的话，不符合预期。

2022-08-26 02:12 UTC, juncaipeng commented
> 需要再确认全局都已经没有config_check

已经全部检查了

2022-08-29 07:03 UTC, merged