【兴智杯-论文复现赛】SwinUnet
PaddlePaddle/PaddleSeg pull request #2561
Opened 2022-09-21 11:43 UTC by marshall-dteach

兴智杯SwinUnet的论文复现

2022-09-21 13:46 UTC, Bobholamovic requested changes
1. `contrib/MedicalSeg/configs`中的模型配置文件错误；
2. 配置文件目录需要调整结构；
3. 存在冗余代码需要消除；
4. 模型实现存在代码风格和整洁性方面问题。

请对照意见逐条修改并回复。

2022-09-21 13:46 UTC, Bobholamovic commented on contrib/MedicalSeg/configs/swinunet/README.md
> +# [Multi-Atlas Labeling](https://www.synapse.org/#!Synapse:syn3193805/wiki/89480/)
建议将`configs/transunet`目录修改为`configs/synapse`（考虑到`multi-atlas labeling`是数据集官网中正式的称呼，但学术论文中一般将此数据集称为`synapse`），然后把swinunet和transunet的配置文件都放在其中，以减小冗余。

2022-09-21 13:46 UTC, Bobholamovic commented on contrib/MedicalSeg/configs/swinunet/abdomen.yml
> +_base_: '../_base_/global_configs.yml'
同上，应该复用`synapse/abdomen.yml`。

2022-09-21 13:46 UTC, Bobholamovic commented on contrib/MedicalSeg/configs/swinunet/swinunet_abdomen_224_224_1_14k_5e-2.yml
> +_base_: 'abdomen.yml'
这个配置文件是transunet的

2022-09-21 13:46 UTC, Bobholamovic commented on contrib/MedicalSeg/test_tipc/prepare.sh
> +    elif [ ${model_name} = "SwinUNet" ]; then
一样的内容不需要另开一个`elif`分支，直接用`||`连接两个判断条件。

2022-09-21 13:46 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/inference_helpers/swinunet_inference_helper.py
> +import numpy as np
`SwinUNetInferenceHelper`和`TransUNetInferenceHelper`的实现基本完全相同，需要减小重复度。建议将`TransUNetInferenceHelper`更改为更通用的名称，然后同时适用于两个网络。

2022-09-21 13:46 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +#from ..model_zoo.vision_transformer import trunc_normal_, zeros_, ones_, to_2tuple, DropPath, Identity
去除没有用到的注释。

2022-09-21 13:46 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +MODEL_URLS = {
如果没有用到、也不计划在以后用到这些预训练权重，就应该去除之。

2022-09-21 13:46 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/models/backbones/__init__.py
> +from .swin_transformer import *
尽量减少`from module import *`的使用。最好明确列出需要导出的函数和类名称。

2022-09-21 13:46 UTC, Bobholamovic commented on contrib/MedicalSeg/test_tipc/configs/swinunet/swinunet_synapse.yml
> +      size: [ 1 ,224, 224 ]
`[1, 224, 224]`逗号前不空格，逗号后空格。

2022-09-21 13:46 UTC, Bobholamovic commented on contrib/MedicalSeg/test_tipc/configs/swinunet/swinunet_synapse.yml
> +      size: [1 ,224, 224]
[1, 224, 224]逗号前不空格，逗号后空格。

2022-09-21 13:46 UTC, Bobholamovic commented on contrib/MedicalSeg/test_tipc/configs/swinunet/swinunet_synapse.yml
> +      size: [1 ,224, 224]
[1, 224, 224]逗号前不空格，逗号后空格。

2022-09-21 13:46 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/models/swinunet.py
> +    r""" Swin Transformer Block.
注释有错误，这个不是swin transformer block

2022-09-21 13:46 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/models/swinunet.py
> +# copyright (c) 2021 PaddlePaddle Authors. All Rights Reserve.
2022

2022-09-21 13:46 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/models/backbones/transformer_utils.py
> +# copyright (c) 2021 PaddlePaddle Authors. All Rights Reserve.
2022

2022-09-21 13:46 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/models/backbones/transformer_utils.py
> +# copyright (c) 2021 PaddlePaddle Authors. All Rights Reserve.
其它地方也注意修改。

2022-09-21 13:46 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/models/swinunet.py
> +
无需空行。

2022-09-21 13:46 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/models/swinunet.py
> +from medicalseg.models.backbones.transformer_utils import *
减少`*`的使用，这样不知道到底哪些名字是从这个模块里导入的。

2022-09-21 13:46 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/models/swinunet.py
> +        image_size (int): Image size of input
所有的非必选参数都需要在注释里标明`optional`并给出默认参数。

2022-09-21 13:46 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/models/swinunet.py
> +        final_unsample (str): The fibal sample class
`fibal sample class`是什么意思

2022-09-21 13:46 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/models/swinunet.py
> +        pretrained: The path of pre-train model
`pre-train`->`pre-trained`

2022-09-21 13:46 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/models/swinunet.py
> +        use_checkpoint (bool): Whether to use checkpointing to save memory. Default: False
这个功能最后没有用到，应该去除。

2022-09-21 13:46 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/models/swinunet.py
> +        patch_norm (bool): If True, add normalization after patch embedding. Default: True
没有用到？

2022-09-21 13:46 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/models/swinunet.py
> +        ape (bool): If True, add absolute position embedding to the patch embedding. Default: False
ape的功能为何直接删除了

2022-09-21 13:46 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/models/swinunet.py
> +        #patches_resolution = self.backbone.patch_embed.patches_resolution
去除无用的注释

2022-09-21 13:46 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/models/swinunet.py
> +            print("---final upsample expand_first---")
这里应该不需要单独print信息，这个信息没表述清楚反而让人疑惑

2022-09-21 13:46 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/models/swinunet.py
> +        assert L == H * W, "input features has wrong size"
建议判断`if L != H*W`，然后`raise ValueError`。

2022-09-21 13:46 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/models/swinunet.py
> +                layer_up = PatchExpand(
综合下文来看，`self.concat_back_dim[0]`最终没有被使用。这样的话`i_layer=0`所对应的`PatchExpand`的逻辑并不适合放在for循环里，直接提到循环外面写就行。另外，后续的`forward_up_features()`中的内容也需要做相应修改。

2022-09-21 13:46 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/models/swinunet.py
> +        assert L == H * W, "input feature has wrong size"
同上

2022-09-21 13:46 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/models/swinunet.py
> +        use_checkpoint (bool): Whether to use checkpointing to save memory. Default: False
去除没有用到的功能。

2022-09-21 13:46 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/models/swinunet.py
> +        mlp_ratio (float): Ratio of mlp hidden dim to embedding dim
可选参数，意见同上。

2022-09-21 13:46 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/models/swinunet.py
> +        downsample (nn.Module | None, optional): Downsample layer at the end of the layer. Default: None
注释里写的是downsample，实际形参名称是upsample。

2022-09-21 13:46 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/models/swinunet.py
> +        huns = -100.0 * paddle.ones_like(attn_mask)
使用`paddle.full_like()`即可。

2022-09-21 13:46 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/models/swinunet.py
> +        assert L == H * W, "input feature has wrong size"
意见同上。

2022-09-21 13:46 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/models/swinunet.py
> +        if self.training:
为什么需要做这一判断？train和eval时候输入的数据不一样吗？

2022-09-21 13:46 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/models/swinunet.py
> +class FinalPatchExpand_X4(nn.Layer):
类名不符合命名规范。

2022-09-21 13:46 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/models/swinunet.py
> +class BasicLayer_up(nn.Layer):
类名不符合命名规范。

2022-09-21 13:46 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +        W (int): Width of image
注释和实际参数不匹配。

2022-09-21 13:46 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +    Args:
Args前面空一行。

2022-09-21 13:46 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +        self.scale = qk_scale or head_dim**-0.5
这个写法会导致潜在风险，建议修改为`if qk_scale is None`。

2022-09-21 13:46 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +    def eval(self, ):
为什么`eval()`方法里没有对子模块的递归处理？例如`self.proj_drop`这样的`nn.Dropout`模块，在train和eval时行为是不一样的。

2022-09-21 13:46 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +        if self.training or not hasattr(self, "relative_position_bias"):
根据上文，`not hasattr(self, "relative_position_bias")`这个情况应该不存在，请问这里设置这个判断是为了？

2022-09-21 13:46 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +        # x = (attn @ v).transpose(1, 2).reshape([B_, N, C])
这句和下一句的功能应该是一样的，如果没有用到请去除。

2022-09-21 13:46 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +    def flops(self, N):
没有计划使用的方法无需保留

2022-09-21 13:46 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +    def extra_repr(self):
没有计划使用的方法无需保留

2022-09-21 13:46 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +        window_size (int): Window size.
注意optional和默认值。

2022-09-21 13:46 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +        assert 0 <= self.shift_size < self.window_size, "shift_size must in 0-window_size"
must是情态动词，`shift_size` must be in 0-`window_size`

2022-09-21 13:46 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +        self.register_buffer("attn_mask", attn_mask)
确定如果attn_mask=None的情况下，这个操作也能正常工作吗？

2022-09-21 13:46 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +        assert L == H * W, "input feature has wrong size"
和`PatchExpand`中的建议相同。

2022-09-21 13:46 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +    def extra_repr(self):
意见同上。

2022-09-21 13:46 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +    def flops(self):
意见同上。

2022-09-21 13:46 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +        # TODO (littletomatodonkey), uncomment the line will cause failure of jit.save
这个是你加的么？

2022-09-21 13:46 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +    Args:
Args之前空一行。

2022-09-21 13:46 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/models/backbones/transformer_utils.py
> +class Identity(nn.Layer):
Paddle中已有原生实现，无需自己再定义。

2022-09-21 14:42 UTC, marshall-dteach commented on contrib/MedicalSeg/test_tipc/prepare.sh
> +    elif [ ${model_name} = "SwinUNet" ]; then
已解决

2022-09-21 14:45 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +#from ..model_zoo.vision_transformer import trunc_normal_, zeros_, ones_, to_2tuple, DropPath, Identity
已解决

2022-09-21 14:47 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/backbones/__init__.py
> +from .swin_transformer import *
这里是和paddleseg的backbone对准，需要调用的零碎小函数有很多，这样更简洁和方便~

2022-09-21 14:54 UTC, marshall-dteach commented on contrib/MedicalSeg/test_tipc/configs/swinunet/swinunet_synapse.yml
> +      size: [ 1 ,224, 224 ]
已修改，并把TransUNet的也修改

2022-09-21 14:56 UTC, marshall-dteach commented on contrib/MedicalSeg/test_tipc/configs/swinunet/swinunet_synapse.yml
> +      size: [1 ,224, 224]
已修改

2022-09-21 14:56 UTC, marshall-dteach commented on contrib/MedicalSeg/test_tipc/configs/swinunet/swinunet_synapse.yml
> +      size: [1 ,224, 224]
已修改

2022-09-21 14:56 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/swinunet.py
> +    r""" Swin Transformer Block.
已修改

2022-09-21 14:57 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/swinunet.py
> +# copyright (c) 2021 PaddlePaddle Authors. All Rights Reserve.
已修改

2022-09-21 14:57 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/backbones/transformer_utils.py
> +# copyright (c) 2021 PaddlePaddle Authors. All Rights Reserve.
已修改

2022-09-21 14:59 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/swinunet.py
> +
已修改

2022-09-21 15:00 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/swinunet.py
> +from medicalseg.models.backbones.transformer_utils import *
这里感觉使用*和paddleseg对齐更好一些，有很多零碎小东西

2022-09-21 15:02 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +MODEL_URLS = {
我想把swintransformer做一个可以通用模型，本次backbone是个自定义的tinyer，其余tiny、base啥的也可以使用，这些模型预训练模型都是可以用的，建议保留~

2022-09-21 15:03 UTC, marshall-dteach commented on contrib/MedicalSeg/configs/swinunet/swinunet_abdomen_224_224_1_14k_5e-2.yml
> +_base_: 'abdomen.yml'
已解决

2022-09-21 15:10 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/swinunet.py
> +        image_size (int): Image size of input
已解决

2022-09-21 15:10 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/swinunet.py
> +        final_unsample (str): The fibal sample class
最后的重构过程，
已解决

2022-09-21 15:11 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/swinunet.py
> +        pretrained: The path of pre-train model
已解决

2022-09-21 15:12 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/swinunet.py
> +        ape (bool): If True, add absolute position embedding to the patch embedding. Default: False
原文没用，我也就没用
已解决

2022-09-21 15:12 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/swinunet.py
> +        #patches_resolution = self.backbone.patch_embed.patches_resolution
已解决

2022-09-21 15:12 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/swinunet.py
> +            print("---final upsample expand_first---")
已解决

2022-09-21 15:14 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/swinunet.py
> +        assert L == H * W, "input features has wrong size"
已解决

2022-09-21 15:15 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/swinunet.py
> +        assert L == H * W, "input feature has wrong size"
已解决

2022-09-21 15:16 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/swinunet.py
> +        mlp_ratio (float): Ratio of mlp hidden dim to embedding dim
已解决

2022-09-21 15:18 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/swinunet.py
> +        use_checkpoint (bool): Whether to use checkpointing to save memory. Default: False
已解决

2022-09-21 15:18 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/swinunet.py
> +        downsample (nn.Module | None, optional): Downsample layer at the end of the layer. Default: None
已解决

2022-09-21 15:21 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/swinunet.py
> +        huns = -100.0 * paddle.ones_like(attn_mask)
已解决

2022-09-21 15:21 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/swinunet.py
> +        assert L == H * W, "input feature has wrong size"
已解决

2022-09-21 15:22 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/swinunet.py
> +class FinalPatchExpand_X4(nn.Layer):
已解决

2022-09-21 15:23 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/swinunet.py
> +class BasicLayer_up(nn.Layer):
已解决

2022-09-21 15:24 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +    Args:
已解决

2022-09-21 15:49 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +        self.scale = qk_scale or head_dim**-0.5
已解决

2022-09-21 15:49 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +    def eval(self, ):
这个是PaddleClass自带的，不太敢动~

2022-09-21 15:51 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +        if self.training or not hasattr(self, "relative_position_bias"):
这也是PaddleClass自带的，可以后面一并去掉？

2022-09-21 15:51 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +        # x = (attn @ v).transpose(1, 2).reshape([B_, N, C])
已解决

2022-09-21 15:52 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +    def extra_repr(self):
已解决

2022-09-21 16:05 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +        window_size (int): Window size.
已解决

2022-09-21 16:07 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +        assert 0 <= self.shift_size < self.window_size, "shift_size must in 0-window_size"
哈哈哈，已解决

2022-09-21 16:08 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +        self.register_buffer("attn_mask", attn_mask)
可以~

2022-09-21 16:08 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +        assert L == H * W, "input feature has wrong size"
已解决

2022-09-21 16:08 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +    def flops(self):
已解决

2022-09-21 16:09 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +        # TODO (littletomatodonkey), uncomment the line will cause failure of jit.save
已删掉
已解决

2022-09-21 16:09 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +    Args:
已解决

2022-09-21 16:10 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/backbones/transformer_utils.py
> +class Identity(nn.Layer):
这是从paddleseg直接复制过来的，我的感觉是和paddleseg保持一致（如果可以我可以两边都做一次重构）

2022-09-21 16:10 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +    def extra_repr(self):
已解决

2022-09-21 16:10 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +    def flops(self, N):
已解决

2022-09-21 16:12 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +        W (int): Width of image
这个是PaddleClass自带的，这个不匹配的意思我没太懂

2022-09-21 16:20 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/swinunet.py
> +                layer_up = PatchExpand(
这个没懂 为什么“i_layer=0所对应的PatchExpand的逻辑并不适合放在for循环里”

2022-09-21 16:20 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/swinunet.py
> +        patch_norm (bool): If True, add normalization after patch embedding. Default: True
好像是

2022-09-21 16:21 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/swinunet.py
> +        use_checkpoint (bool): Whether to use checkpointing to save memory. Default: False
已解决

2022-09-21 16:32 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/inference_helpers/swinunet_inference_helper.py
> +import numpy as np
我感觉这两个相似只是凑巧，如果单纯为了减少这两个的重复度，可能会对后面的模型非常不友好（比如Matting）

2022-09-21 16:32 UTC, marshall-dteach commented on contrib/MedicalSeg/configs/swinunet/abdomen.yml
> +_base_: '../_base_/global_configs.yml'
已暂时做了一次调整

2022-09-21 16:38 UTC, marshall-dteach commented on contrib/MedicalSeg/configs/swinunet/README.md
> +# [Multi-Atlas Labeling](https://www.synapse.org/#!Synapse:syn3193805/wiki/89480/)
已做了一次暂时调整，TransUNet README暂不做修改留作备份~

2022-09-22 03:20 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/models/backbones/transformer_utils.py
> +class Identity(nn.Layer):
建议两边都做一次重构~

2022-09-22 03:29 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/models/swinunet.py
> +        patch_norm (bool): If True, add normalization after patch embedding. Default: True
这样的话就去除吧

2022-09-22 04:05 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/inference_helpers/swinunet_inference_helper.py
> +import numpy as np
从功能上来看，这两个模型都是处理2D数据的，所以可以复用inferencehelper，建议命名可以从这方面考虑，例如叫做`2DDataInferenceHelper`。

2022-09-22 09:29 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +MODEL_URLS = {
好的，为了防止链接失效，请将链接更新如下：

2022-09-22 09:57 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/models/swinunet.py
> +                layer_up = PatchExpand(
我又琢磨了一下，这样写应该也有道理~

2022-09-22 10:09 UTC, Bobholamovic requested changes
1. 请逐条回复上次review和本次review的未resolved的conversation，并根据意见做出评论或修改。
2. config部分需要将swinunet_*.yml和transunet_abdomen*.yml都放在configs/synapse目录下，且合并几个README，可参考unet与vnet的自述文件。

2022-09-22 10:09 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +        if self.training or not hasattr(self, "relative_position_bias"):
嗯嗯，应该优化掉无效的分支。

2022-09-22 10:09 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +    def eval(self, ):
这个行为应该不正确，只是先前把dropout的rate调成0正好没暴露这个问题。请修复。

2022-09-22 15:01 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +MODEL_URLS = {
已更新，但是考虑到PaddleSeg现有模型与PaddleClass参数名称不一致，是否应该将原来的模型下载下来再上传，做一个更新呢？

2022-09-22 15:06 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/inference_helpers/swinunet_inference_helper.py
> +import numpy as np
已解决，由于命名原因，我将2D放到了后面

2022-09-22 15:31 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/swinunet.py
> +        patch_norm (bool): If True, add normalization after patch embedding. Default: True
已解决

2022-09-22 15:33 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/swinunet.py
> +        if self.training:
好像不一样，按照TransUNet来的
![00859a324e057fae4833b3db7991a96](https://user-images.githubusercontent.com/63546191/191790057-f3d133ce-fc31-4636-981a-192b195f4bb1.jpg)

2022-09-22 15:35 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +    def eval(self, ):
请问是eval的问题吗？我没搞懂

2022-09-22 15:35 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +        if self.training or not hasattr(self, "relative_position_bias"):
已解决

2022-09-22 15:39 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/backbones/transformer_utils.py
> +class Identity(nn.Layer):
已解决
paddleseg那边我看需要调整的太多了，怕出问题，比赛时间紧，我先把兴智杯弄完过几天我单独pr一次吧~

2022-09-22 16:24 UTC, marshall-dteach commented on contrib/MedicalSeg/configs/swinunet/README.md
> +# [Multi-Atlas Labeling](https://www.synapse.org/#!Synapse:syn3193805/wiki/89480/)
已再次调整

2022-09-22 16:25 UTC, marshall-dteach commented on contrib/MedicalSeg/configs/swinunet/abdomen.yml
> +_base_: '../_base_/global_configs.yml'
已调整

2022-09-23 03:00 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +MODEL_URLS = {
现在就是这么做的喔，这些是和PaddleClas一致的权重~

2022-09-23 03:02 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +    def eval(self, ):
需要调用`super().eval()`~

2022-09-23 03:04 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +        W (int): Width of image
注释中缺少对参数`C`的描述。

2022-09-23 03:04 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/models/swinunet.py
> +        if self.training:
ok

2022-09-23 05:50 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +        W (int): Width of image
已解决

2022-09-23 05:52 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +    def eval(self, ):
已解决

2022-09-23 06:46 UTC, Bobholamovic requested changes
1. 请逐条回复上次review和本次review的未resolved的conversation，并根据意见做出评论或修改。
2. 存在大量回复『已解决』且resolve的conversation却没有进行实际修改的情况。考虑到conversation数量较多，请务必保证**先修改、再回复**并resolve conversation，以减少返工、提高质量。

2022-09-23 06:46 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/inference_helpers/__init__.py
> +from .inference_helper_2D import InferenceHelper2D
文件命名应该是`inference_helper_2d.py`

2022-09-23 06:46 UTC, Bobholamovic commented on contrib/MedicalSeg/configs/synapse/README.md
>  3. Medical maintains a INFERENCE_HELPERS variable of type ComponentManager. You can add your custom InferenceHelper through the add_component method.
`add_component`属于代码，需用反引号包围。

2022-09-23 06:46 UTC, Bobholamovic commented on contrib/MedicalSeg/configs/synapse/README.md
> +1. Since the shape of the input and output data of the TransUnet and SwinUnet network is different from other networks, in order to make it compatible with the inference program, it is necessary to p
Since the shape of the input and output data of the TransUnet and SwinUnet networks is different from other networks, it is necessary to define special pre-process and post-process rules for these networks. This is achieved by `InferenceHelper`.

2022-09-23 06:46 UTC, Bobholamovic commented on contrib/MedicalSeg/configs/synapse/README.md
>  2. InferenceHelper is an abstract base class that contains two methods, preprocess and postprocess. If you need to add a new InferenceHelper to your own network, you need to customize the class in th
`InferenceHelper` is an abstract base class that contains two methods, `preprocess` and `postprocess`. If you need to add a new inference helper to your own network, you need to customize the class in the `medicalseg/inference_helpers` package and inherit the base `InferenceHelper` class.

2022-09-23 06:46 UTC, Bobholamovic commented on contrib/MedicalSeg/configs/synapse/README.md
>  3. Medical maintains a INFERENCE_HELPERS variable of type ComponentManager. You can add your custom InferenceHelper through the add_component method.
MedicalSeg maintains an `INFERENCE_HELPERS` variable of type `ComponentManager`. You can add your custom inference helper through the `add_component` method.

2022-09-23 06:46 UTC, Bobholamovic commented on contrib/MedicalSeg/configs/synapse/README.md
>  5. Finally you can reference your Inference helper in your yaml configuration file. This way
Finally you can reference your inference helper in your yaml configuration file. This way, the customized inference helper will be automatically constructed and invoked in the inference script.

2022-09-23 06:46 UTC, Bobholamovic commented on contrib/MedicalSeg/test_tipc/prepare.sh
> +    elif [ ${model_name} = "TransUNet" || "SwinUNet"]; then
这个写法是错误的，请注意区分bash中的`[[...]]`和`[...]`。如果要使用`[...]`，语法应该是`[ ${model_name} = "TransUNet" ] || [ ${model_name} = "SwinUNet" ]`。

2022-09-23 06:46 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +        qk_scale (float | None, optional): Override default qk scale of head_dim ** -0.5 if set
缺句号，另外没说默认值是什么。

2022-09-23 06:46 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +        B_, N, C = x.shape
虽然不是重要问题，但还是顺便问下，这里的`B_`为什么加下划线？（考虑到与其并列的`N`和`C`都没有加）

2022-09-23 06:46 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +        window_size (int): Window size. Default: 7
对于可选参数，需要添加optional并标明默认值。

2022-09-23 06:46 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +    def extra_repr(self):
这个方法没有用到，请去除。

2022-09-23 06:46 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +    def flops(self):
没有用到的方法请去除。

2022-09-23 06:46 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +        mlp_ratio (float): Ratio of mlp hidden dim to embedding dim.
可选参数需标注optional并注明默认值。

2022-09-23 06:46 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +    def extra_repr(self):
`extra_repr`和`flops`，没有用到的方法请去除。

2022-09-23 06:46 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +        img_size (int): Image size.  Default: 224.
可选参数需要注明optional。

2022-09-23 06:46 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +        #self.head = nn.Linear(
没有用到的注释请去除。

2022-09-23 06:46 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +    def flops(self):
没有用到的方法需要去除。

2022-09-23 06:46 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +        img_size (int | tuple(int)): Input image size. Default 224
可选参数需要标注optional。另外tuple类型应该表示为`tuple[int]`用`[...]`而不是`(...)`。其它地方也请注意修改。

2022-09-23 06:46 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +        qk_scale (float): Override default qk scale of head_dim ** -0.5 if set. Default: None
`qk`表意不清，应该写全称`query and key`。

2022-09-23 06:46 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +        use_checkpoint (bool): Whether to use checkpointing to save memory. Default: False
`use_checkpoint`功能没有用到，应该去除。请检查提交代码中的其它涉及`use_checkpoint`的部分，确保全部去除。

2022-09-23 06:46 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +        A PaddlePaddle impl of : `Swin Transformer: Hierarchical Vision Transformer using Shifted Windows`  -
`A PaddlePaddle implementation`

2022-09-23 06:46 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +        self.avgpool = nn.AdaptiveAvgPool1D(1)
这个好像没有用到呢

2022-09-23 06:46 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +        #x = self.avgpool(x.transpose([0, 2, 1]))  # B C 1
没有用到的部分请去除。

2022-09-23 06:46 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +    def forward(self, x):
如果`forward()`和`forward_features()`完全重合，我理解是不是只要写`forward()`就行？可以参考PaddleSeg的backbone是怎么做的。

2022-09-23 06:46 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +    def flops(self):
去除没有用到的函数。

2022-09-23 06:46 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +def _load_pretrained(pretrained, model, model_url, use_ssld=False):
这个函数没有实现加载预训练模型的功能，请完善。

2022-09-23 06:46 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +        **kwargs)
为什么这个架构没有预训练权重加载的部分？

2022-09-23 06:46 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +        self.apply(self._init_weights)
预训练权重加载部分请复用MedicalSeg已有的函数和类，遵照MedicalSeg模型的统一风格。

2022-09-23 06:46 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/models/swinunet.py
> +        qk_scale (float | None, optional): Override default qk scale of head_dim ** -0.5 if set. Default: None
`qk`写全称，`query and key`。

2022-09-23 06:46 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/models/swinunet.py
> +        depths: Block number of every encoder layer. Default: [2, 2, 2, 2]
没写类型

2022-09-23 06:46 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/models/swinunet.py
> +        path_size (int): Patch size of Patch Embed. Default: 4
**所有**的可选参数都要加optional，请自行检查所有提交的代码。

2022-09-23 06:46 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/models/swinunet.py
> +        final_unsample (bool): The fibal sample class. Default: True
`fibal`是否typo？

2022-09-23 06:46 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/models/swinunet.py
> +class BasicLayerUp(nn.Layer):
我记得`BasicUpLayer`是更好的名字。

2022-09-23 06:46 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/models/swinunet.py
> +        mlp_ratio (float): Ratio of mlp hidden dim to embedding dim
可选参数，需添加optinoal说明。

2022-09-23 07:20 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +    def extra_repr(self):
已解决

2022-09-23 07:22 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +        #self.head = nn.Linear(
这里是swintansformer的原模型的分类头，我想留着便于新手做一个区分，不然新人很难理解PaddleSeg是怎么用transformer的，前几天群里还有看到Paddleseg里的swin transformer在问为什么与PaddleClass的不一致

2022-09-23 07:22 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +    def flops(self):
已解决

2022-09-23 07:23 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +        self.avgpool = nn.AdaptiveAvgPool1D(1)
已解决

2022-09-23 07:23 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +        #x = self.avgpool(x.transpose([0, 2, 1]))  # B C 1
这里是swintansformer的原模型的分类头，我想留着便于新手做一个区分，不然新人很难理解PaddleSeg是怎么用transformer的，前几天群里还有看到Paddleseg里的swin transformer在问为什么与PaddleClass的不一致

2022-09-23 07:24 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +    def forward(self, x):
这里是forward_features 是区别swintansformer的原模型的分类头用的，我想留着便于新手做一个区分，不然新人很难理解PaddleSeg是怎么用transformer的，前几天群里还有看到Paddleseg里的swin transformer在问为什么与PaddleClass的不一致

2022-09-23 07:25 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +    def flops(self):
已解决

2022-09-23 07:26 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/swinunet.py
> +        assert L == H * W, "input features has wrong size"
raise 语法在export模型会报错，我暂时修改回assert了

2022-09-23 07:32 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/inference_helpers/__init__.py
> +from .inference_helper_2D import InferenceHelper2D
已修改

2022-09-23 07:36 UTC, marshall-dteach commented on contrib/MedicalSeg/configs/synapse/README.md
>  3. Medical maintains a INFERENCE_HELPERS variable of type ComponentManager. You can add your custom InferenceHelper through the add_component method.
已修改

2022-09-23 07:38 UTC, marshall-dteach commented on contrib/MedicalSeg/configs/synapse/README.md
> +1. Since the shape of the input and output data of the TransUnet and SwinUnet network is different from other networks, in order to make it compatible with the inference program, it is necessary to p
已修改

2022-09-23 07:38 UTC, marshall-dteach commented on contrib/MedicalSeg/configs/synapse/README.md
>  2. InferenceHelper is an abstract base class that contains two methods, preprocess and postprocess. If you need to add a new InferenceHelper to your own network, you need to customize the class in th
已修改

2022-09-23 07:38 UTC, marshall-dteach commented on contrib/MedicalSeg/configs/synapse/README.md
>  3. Medical maintains a INFERENCE_HELPERS variable of type ComponentManager. You can add your custom InferenceHelper through the add_component method.
已修改

2022-09-23 07:39 UTC, marshall-dteach commented on contrib/MedicalSeg/configs/synapse/README.md
>  5. Finally you can reference your Inference helper in your yaml configuration file. This way
已修改

2022-09-23 07:39 UTC, marshall-dteach commented on contrib/MedicalSeg/test_tipc/prepare.sh
> +    elif [ ${model_name} = "TransUNet" || "SwinUNet"]; then
已修改

2022-09-23 07:59 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +        self.apply(self._init_weights)
已修改

2022-09-23 08:00 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +    def extra_repr(self):
已解决

2022-09-23 08:02 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +        B_, N, C = x.shape
默认的，便于与Batchsize做区分吧

2022-09-23 08:02 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +    def flops(self):
已解决

2022-09-23 08:02 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +        qk_scale (float): Override default qk scale of head_dim ** -0.5 if set. Default: None
已解决

2022-09-23 08:04 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +        A PaddlePaddle impl of : `Swin Transformer: Hierarchical Vision Transformer using Shifted Windows`  -
已解决

2022-09-23 08:05 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +def _load_pretrained(pretrained, model, model_url, use_ssld=False):
已删除，替换成medicalseg.utils自带的load_pretrained_model

2022-09-23 08:06 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/swinunet.py
> +        qk_scale (float | None, optional): Override default qk scale of head_dim ** -0.5 if set. Default: None
已修改

2022-09-23 08:10 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/swinunet.py
> +        depths: Block number of every encoder layer. Default: [2, 2, 2, 2]
已修改

2022-09-23 08:11 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/swinunet.py
> +        final_unsample (bool): The fibal sample class. Default: True
已修改

2022-09-23 08:11 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/swinunet.py
> +        mlp_ratio (float): Ratio of mlp hidden dim to embedding dim
已修改

2022-09-23 08:14 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +        img_size (int | tuple(int)): Input image size. Default 224
全部已修改

2022-09-23 08:16 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +        img_size (int): Image size.  Default: 224.
全部已修改

2022-09-23 08:16 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +        mlp_ratio (float): Ratio of mlp hidden dim to embedding dim.
全部已修改

2022-09-23 08:17 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +        window_size (int): Window size. Default: 7
全部已修改

2022-09-23 08:17 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +        qk_scale (float | None, optional): Override default qk scale of head_dim ** -0.5 if set
已修改

2022-09-23 08:18 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +        use_checkpoint (bool): Whether to use checkpointing to save memory. Default: False
全部已修改

2022-09-23 08:18 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/swinunet.py
> +        path_size (int): Patch size of Patch Embed. Default: 4
全部已修改

2022-09-23 08:19 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/swinunet.py
> +class BasicLayerUp(nn.Layer):
已修改

2022-09-23 08:21 UTC, marshall-dteach commented
> 1. 请逐条回复上次review和本次review的未resolved的conversation，并根据意见做出评论或修改。
> 2. 存在大量回复『已解决』且resolve的conversation却没有进行实际修改的情况。考虑到conversation数量较多，请务必保证**先修改、再回复**并resolve conversation，以减少返工、提高质量。
> 3. 共性问题，如doc string中可选参数需要注明optional并给出默认值、未使用的函数应该去除等，review过程中无法一一标注，请自行检查所有提交代码。
>    4.backbone预训练权重加载部分未实现，如果计划提供该功能，请补充相关逻辑。
>    ![image](https://user-images.githubusercontent.com/21275753/191906051-a16dbbbe-1858-4b9d-9e0b-14fde6b78eb5.png)
> 4. 自定义的tinyer结构有何特殊之处？tinyer这个名称有何特殊含义？

这个tinyer是我自己命名的，通用的swintransformer tiny第三层有6个block，但是这个作者自定义了第三层只有2个block，为了区分，我将其命名为tinyer

2022-09-23 09:03 UTC, Bobholamovic commented
> > 1. 请逐条回复上次review和本次review的未resolved的conversation，并根据意见做出评论或修改。
> > 2. 存在大量回复『已解决』且resolve的conversation却没有进行实际修改的情况。考虑到conversation数量较多，请务必保证**先修改、再回复**并resolve conversation，以减少返工、提高质量。
> > 3. 共性问题，如doc string中可选参数需要注明optional并给出默认值、未使用的函数应该去除等，review过程中无法一一标注，请自行检查所有提交代码。
> >    4.backbone预训练权重加载部分未实现，如果计划提供该功能，请补充相关逻辑。
> >    ![image](https://user-images.githubusercontent.com/21275753/191906051-a16dbbbe-1858-4b9d-9e0b-14fde6b78eb5.png)
> > 4. 自定义的tinyer结构有何特殊之处？tinyer这个名称有何特殊含义？
> 
> 这个tinyer是我自己命名的，通用的swintransformer tiny第三层有6个block，但是这个作者自定义了第三层只有2个block，为了区分，我将其命名为tinyer

OK，不过按照英语语法，tiny的比较级应该是tinier，可以修改一下让命名含义更清晰~

2022-09-23 14:42 UTC, marshall-dteach commented
> > > 1. 请逐条回复上次review和本次review的未resolved的conversation，并根据意见做出评论或修改。
> > > 2. 存在大量回复『已解决』且resolve的conversation却没有进行实际修改的情况。考虑到conversation数量较多，请务必保证**先修改、再回复**并resolve conversation，以减少返工、提高质量。
> > > 3. 共性问题，如doc string中可选参数需要注明optional并给出默认值、未使用的函数应该去除等，review过程中无法一一标注，请自行检查所有提交代码。
> > >    4.backbone预训练权重加载部分未实现，如果计划提供该功能，请补充相关逻辑。
> > >    ![image](https://user-images.githubusercontent.com/21275753/191906051-a16dbbbe-1858-4b9d-9e0b-14fde6b78eb5.png)
> > > 4. 自定义的tinyer结构有何特殊之处？tinyer这个名称有何特殊含义？
> > 
> > 
> > 这个tinyer是我自己命名的，通用的swintransformer tiny第三层有6个block，但是这个作者自定义了第三层只有2个block，为了区分，我将其命名为tinyer
> 
> OK，不过按照英语语法，tiny的比较级应该是tinier，可以修改一下让命名含义更清晰~

已将tinyer修改为tinier（工地英语水平不过关，丢人啦~~~）

2022-09-26 03:01 UTC, Bobholamovic requested changes
1. 仍然发现存在回复『已修改』但实际未修改的情况，请在修改完之后再回复『已修改』。
2. TIPC的配置文件存在问题。
3. 其它一些小问题。

2022-09-26 03:01 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/inference_helpers/inference_helper_2D.py
文件名里不要大写，应该是`inference_helper_2d.py`。

2022-09-26 03:01 UTC, Bobholamovic commented on contrib/MedicalSeg/configs/synapse/README.md
> +from .transunet_inference_helper_2D import InferenceHelper2D
将`_2D`修改为`_2d`后这里也要对应修改。

2022-09-26 03:01 UTC, Bobholamovic commented on contrib/MedicalSeg/configs/synapse/README.md
> +| SwinTransformer-tinyer | 224x224    | 5e-2 | 14000          | 79.97% | [model]() \| [log]() \| [vdl]() |
`tinyer`->`tinier`

2022-09-26 03:01 UTC, Bobholamovic commented on contrib/MedicalSeg/test_tipc/configs/swinunet/swinunet_synapse.yml
> +  dataset_root: ./mini_synapse_dataset
这个地方是不是有问题

2022-09-26 03:01 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +        C (int): Channel of image
`Channel`->`Channels`

2022-09-26 03:01 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +        window_size (int): Window size. Default: 7
这个没添加optional

2022-09-26 03:01 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +        mlp_ratio (float, optional): Ratio of mlp hidden dim to embedding dim.
Default: 4.

2022-09-26 03:01 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +        self.apply(self._init_weights)
未修改？

2022-09-26 03:01 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/models/swinunet.py
> +        qk_scale (float | None, optional): Override default qk scale of head_dim ** -0.5 if set. Default: None
未修改？

2022-09-26 04:29 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/inference_helpers/inference_helper_2D.py
已修改

2022-09-26 04:29 UTC, marshall-dteach commented on contrib/MedicalSeg/configs/synapse/README.md
> +from .transunet_inference_helper_2D import InferenceHelper2D
已修改

2022-09-26 04:29 UTC, marshall-dteach commented on contrib/MedicalSeg/configs/synapse/README.md
> +| SwinTransformer-tinyer | 224x224    | 5e-2 | 14000          | 79.97% | [model]() \| [log]() \| [vdl]() |
已修改

2022-09-26 04:32 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +        C (int): Channel of image
已修改

2022-09-26 04:33 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +        window_size (int): Window size. Default: 7
已修改

2022-09-26 04:33 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +        mlp_ratio (float, optional): Ratio of mlp hidden dim to embedding dim.
已修改

2022-09-26 04:37 UTC, marshall-dteach commented on contrib/MedicalSeg/test_tipc/configs/swinunet/swinunet_synapse.yml
> +  dataset_root: ./mini_synapse_dataset
我检查了一下，应该没问题，和transunet是一致的

2022-09-26 04:38 UTC, marshall-dteach commented on contrib/MedicalSeg/test_tipc/configs/swinunet/swinunet_synapse.yml
> +  dataset_root: ./mini_synapse_dataset
训练用的config是删除的这种写法

2022-09-26 04:40 UTC, marshall-dteach commented
![Uploading image.png…]()
修改了，但是不知道为啥没有保持一致

2022-09-26 04:45 UTC, marshall-dteach commented
> 1. 仍然发现存在回复『已修改』但实际未修改的情况，请在修改完之后再回复『已修改』。
> 2. TIPC的配置文件存在问题。
> 3. 其它一些小问题。

![image](https://user-images.githubusercontent.com/63546191/192195568-9adbc4e3-c41d-4895-bcfd-15735f166694.png)
这里还是必须要把这几行注释删除吗？

2022-09-26 08:12 UTC, Bobholamovic commented
> > 1. 仍然发现存在回复『已修改』但实际未修改的情况，请在修改完之后再回复『已修改』。
> > 2. TIPC的配置文件存在问题。
> > 3. 其它一些小问题。
> 
> ![image](https://user-images.githubusercontent.com/63546191/192195568-9adbc4e3-c41d-4895-bcfd-15735f166694.png) 这里还是必须要把这几行注释删除吗？

这里需要添加和MedicalSeg/PaddleSeg其它backbone一致的预训练权重加载方式，例如：

2022-09-26 08:24 UTC, Bobholamovic reviewed
1. backbone加载预训练权重的方式修改为与PaddleSeg/MedicalSeg中其它模型风格一致；
2. 请确认对`inference_helper_2D`重命名的修改是否正确完成。

2022-09-26 08:24 UTC, Bobholamovic commented on contrib/MedicalSeg/test_tipc/configs/swinunet/swinunet_synapse.yml
> +  dataset_root: ./mini_synapse_dataset
ok

2022-09-26 08:24 UTC, Bobholamovic commented on contrib/MedicalSeg/configs/synapse/README.md
> +from .transunet_inference_helper_2D import InferenceHelper2D
![image](https://user-images.githubusercontent.com/21275753/192228316-0ada9f36-aa60-4931-be98-01e9c1629219.png)
不知道是我这边显示的问题还是你没有提交上，我这里好像还是这样的喔

2022-09-26 08:24 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/inference_helpers/inference_helper_2D.py
![image](https://user-images.githubusercontent.com/21275753/192228470-e0acd233-896f-4c92-b283-b4f6029ca3ad.png)
我这边看好像还没有修改

2022-09-26 08:42 UTC, Bobholamovic reviewed
接近完成。数据集文档中的`2D`->`2d`好像还没有修改。

2022-09-26 08:42 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/models/swinunet.py
> +        self._init_weights()
命名应该是`init_weights`，且`load_pretrained_model`的逻辑应该放在`init_weights`方法中，参考：
![image](https://user-images.githubusercontent.com/21275753/192232414-2fa026e9-159d-4434-81de-a842e8c5ef91.png)

2022-09-26 08:42 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/models/swinunet.py
> +        self._init_weights()
https://github.com/PaddlePaddle/PaddleSeg/blob/2eb0a42ebb39138e643d18796ffbcc130ead2ef0/paddleseg/models/backbones/stdcnet.py

2022-09-26 09:02 UTC, Bobholamovic approved these changes, later dismissed
LGTM. TIPC验证通过，运行时间满足要求。
![image](https://user-images.githubusercontent.com/21275753/192236763-73b5f7ba-cefc-4787-8fe8-e3e6d30caba3.png)

2022-09-27 07:11 UTC, Bobholamovic commented
精度验证：
![image](https://user-images.githubusercontent.com/21275753/192457950-6d0ba12c-0523-46e2-a096-76e954ea53cd.png)
高于原文精度79.13%。

[训练日志](https://github.com/marshall-dteach/SwinUNet/blob/main/log/log.txt)复核通过。

2022-09-27 07:19 UTC, shiyutang requested changes
整体完成度不错，但是需要进一步修改一些细节

2022-09-27 07:19 UTC, shiyutang commented on contrib/MedicalSeg/configs/synapse/README.md
> +If you want to get data suitable, you first need to download RawData.zip from [https://www.synapse.org/#!Synapse:syn3193805/files/](https://www.synapse.org/#!Synapse:syn3193805/files/). Then put it i
If you want to get data suitable - 》 To preprocess the synapse data

2022-09-27 07:19 UTC, shiyutang commented on contrib/MedicalSeg/configs/synapse/README.md
> +| SwinTransformer-tinier | 224x224    | 5e-2 | 14000          | 79.97% | [model]() \| [log]() \| [vdl]() |
模型、日志等链接需要补充

2022-09-27 07:19 UTC, shiyutang commented on contrib/MedicalSeg/configs/synapse/transunet_abdomen_224_224_1_14k_1e-2.yml
> +    - type: MixedLoss
为什么要修改transunet的yml呢

2022-09-27 07:19 UTC, shiyutang commented on contrib/MedicalSeg/medicalseg/models/swinunet.py
> +#Dencoder and Skip connection
注释也要有合理空行，是否跑过pre-commit？

2022-09-27 07:19 UTC, shiyutang commented on contrib/MedicalSeg/medicalseg/models/swinunet.py
> +        self._init_weights()
这里没有修改？

2022-09-27 07:19 UTC, shiyutang commented on contrib/MedicalSeg/medicalseg/models/backbones/transformer_utils.py
> +        ones_(layer.weight)
放入模型定义中

2022-09-27 07:19 UTC, shiyutang commented on contrib/MedicalSeg/medicalseg/models/backbones/transformer_utils.py
> +    return output
只有下面一个类使用的函数放入对应类中，保持代码的整体性

2022-09-27 07:19 UTC, shiyutang commented on contrib/MedicalSeg/medicalseg/models/backbones/transformer_utils.py
> +ones_ = paddle_init.Constant(value=1.)
同上，均放入initweight中

2022-09-28 07:41 UTC, Bobholamovic commented on contrib/MedicalSeg/medicalseg/models/backbones/transformer_utils.py
> +ones_ = paddle_init.Constant(value=1.)
考虑到`trunc_normal_`、`zeros_`和`ones_`三个方法其它的transformer模型在初始化时可能也可以复用，我觉得放在`transformer_utils.py`中是不是也可以？

2022-09-28 07:44 UTC, Bobholamovic commented on contrib/MedicalSeg/configs/synapse/transunet_abdomen_224_224_1_14k_1e-2.yml
> +    - type: MixedLoss
此处主要是考虑transunet和swinunet两个算法在配置上十分相似，都基于synapse数据集训练，因此对配置文件做了一些调整，减小冗余度，但保持transunet的配置功能不变。

2022-09-29 02:23 UTC, shiyutang requested changes
少量修改后可合入

2022-09-29 02:23 UTC, shiyutang commented on contrib/MedicalSeg/configs/synapse/transunet_abdomen_224_224_1_14k_1e-2.yml
> +    - type: MixedLoss
这里是如何减少冗余的呢？ 运行swinunet之需要swinunet.yml 和abdomen.yml 但是这里却增加了transunet的配置？

2022-09-29 02:23 UTC, shiyutang commented on contrib/MedicalSeg/medicalseg/models/backbones/transformer_utils.py
> +ones_ = paddle_init.Constant(value=1.)
如果这样的话，建议将文件这部分内容放入layers/init.py中

2022-09-29 02:23 UTC, shiyutang commented on contrib/MedicalSeg/medicalseg/models/backbones/transformer_utils.py
> +    return tuple([x] * 2)
这个只有对应模型使用，建议放入模型文件中

2022-09-29 03:23 UTC, Bobholamovic commented on contrib/MedicalSeg/configs/synapse/transunet_abdomen_224_224_1_14k_1e-2.yml
> +    - type: MixedLoss
即，将两个模型配置共同的部分（也是与数据集直接相关的部分，如dataset、transforms）放在`abdomen.yml`，将二者配置上不同的部分分别放入模型对应的配置文件。

2022-09-29 08:08 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/swinunet.py
> +        qk_scale (float | None, optional): Override default qk scale of head_dim ** -0.5 if set. Default: None
已再次修改

2022-09-29 08:08 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/backbones/swin_transformer.py
> +        self.apply(self._init_weights)
这里的self.apply是初始化一些预训练模型中没有的权重部分，第一次修改是针对预训练模型中有的，将其规范化了；经过实验来看，针对预训练模型中没有的（新定义的）部分进行这样的规范化对于结果有着明显的提升

2022-09-29 08:08 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/swinunet.py
> +        self._init_weights()
已修改

2022-09-29 08:08 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/swinunet.py
> +#Dencoder and Skip connection
跑过的~

2022-09-29 08:08 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/backbones/transformer_utils.py
> +        ones_(layer.weight)
这个是paddleseg自带的，需要把这个删掉不？

2022-09-29 08:08 UTC, marshall-dteach commented on contrib/MedicalSeg/configs/synapse/transunet_abdomen_224_224_1_14k_1e-2.yml
> +    - type: MixedLoss
这个模型的配置和transunet完全一样，合入的时候为了和transunet的统一格式，减少复杂度（和验收RD商量的）

2022-09-29 08:08 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/swinunet.py
> +#Dencoder and Skip connection
我修改一下

2022-09-29 08:08 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/swinunet.py
> +        self._init_weights()
改过的，应该是显示的之前的~

2022-09-29 08:08 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/backbones/transformer_utils.py
> +    return output
已修改

2022-09-29 08:08 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/backbones/transformer_utils.py
> +ones_ = paddle_init.Constant(value=1.)
已修改

2022-09-29 08:08 UTC, marshall-dteach commented on contrib/MedicalSeg/configs/synapse/README.md
> +If you want to get data suitable, you first need to download RawData.zip from [https://www.synapse.org/#!Synapse:syn3193805/files/](https://www.synapse.org/#!Synapse:syn3193805/files/). Then put it i
已修改

2022-09-29 08:08 UTC, marshall-dteach commented on contrib/MedicalSeg/configs/synapse/README.md
> +| SwinTransformer-tinier | 224x224    | 5e-2 | 14000          | 79.97% | [model]() \| [log]() \| [vdl]() |
ok

2022-09-29 08:08 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/backbones/transformer_utils.py
> +        ones_(layer.weight)
删掉了init_weight保留了zeros_等transformer的常用操作，便于接下来的transformer的合入

2022-09-29 08:08 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/backbones/transformer_utils.py
> +    return tuple([x] * 2)
这个虽然目前只有这个模型在用，但是几乎每个transformer都会用到，以后如果添加vit等backbone免不了要用~，建议留在这里

2022-09-29 08:08 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/backbones/transformer_utils.py
> +ones_ = paddle_init.Constant(value=1.)
我个人感觉，这几个都是transformer的小模块，如果移出去有三点不好：
* 1.代码整体性跨度太大，易读性差，对新人不友好 
* 2.如果添加新的transformer，需要来回导入的文件太多 
* 3.transformer_utils文件中的内容太少，显得虎头蛇尾了~

2022-09-29 11:48 UTC, shiyutang commented on contrib/MedicalSeg/medicalseg/models/backbones/transformer_utils.py
> +ones_ = paddle_init.Constant(value=1.)
这里主要需要遵循文件名称反映文件内容的规则，初始化函数不是transformer特有的话，就不应当出现在transformerutils里。

2022-09-29 11:49 UTC, shiyutang commented on contrib/MedicalSeg/configs/synapse/transunet_abdomen_224_224_1_14k_1e-2.yml
> +    - type: MixedLoss
好的～

2022-09-29 11:52 UTC, marshall-dteach commented on contrib/MedicalSeg/medicalseg/models/backbones/transformer_utils.py
> +ones_ = paddle_init.Constant(value=1.)
我想的跟您想的是一样的，我的考虑是： TruncatedNoraml目前确实是只有transformer会用，因此将这个初始化放到了transformer_utils里，考虑到初始化的时候往往并不只是truncatednormal初始化线性层，对于LayerNorm的初始化往往用0和1，为了完整性，我还是建议* 保持这部分不动

2022-09-30 02:09 UTC, Bobholamovic commented
有冲突需要解决

2022-09-30 02:17 UTC, marshall-dteach commented
> 有冲突需要解决

已解决

2022-09-30 02:22 UTC, shiyutang commented on contrib/MedicalSeg/medicalseg/models/backbones/transformer_utils.py
> +    return tuple([x] * 2)
好的

2022-09-30 03:17 UTC, shiyutang approved these changes
LGTM

2022-09-30 03:17 UTC, merged