[Feature]: add LPSNet
PaddlePaddle/PaddleSeg pull request #2818
Opened 2022-12-08 09:51 UTC by Asthestarsfalll

### PR types

New features

### PR changes

Models

### Description

reference: https://github.com/YihengZhang-CV/LPS-Net

2022-12-08 10:03 UTC, Asthestarsfalll commented on paddleseg/models/lpsnet.py
> +def _multipath_interaction(feats):
可适应任意多路的情况

2022-12-08 10:03 UTC, Asthestarsfalll commented on paddleseg/models/lpsnet.py
> +        super().__init__()
分支数量取决于scale_ratios的长度，无需为不同分支的模型单独写代码

2022-12-08 10:03 UTC, Asthestarsfalll commented on paddleseg/models/lpsnet.py
> +    def switch_to_deploy(self):
结构重参数化，或许可以直接添加作为layers.ConvBNReLU的方法

2022-12-09 10:25 UTC, juncaipeng commented on paddleseg/models/lpsnet.py
> +def lps_net_small(deploy=False, num_classes=19, pretrained=None):
不要使用函数来定义不同型号的模型（backbone除外），不同型号的模型需要有对应的yml文件，而且都需要进行训练。

2022-12-09 10:25 UTC, juncaipeng commented on paddleseg/models/lpsnet.py
> +_interpolate = partial(F.interpolate, mode="bilinear", align_corners=True)
所有interpolate都是使用align_corners=True？

2022-12-09 10:25 UTC, juncaipeng commented on paddleseg/models/lpsnet.py
> +            num_classes,
需要加入in_channels，参考指南：https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.7/docs/pr/pr/style_cn.md

2022-12-09 10:25 UTC, juncaipeng commented on paddleseg/models/lpsnet.py
> +    scale_ratios = [1, 1 / 4, 0]
scale_ratios中有一个数值为0？是不是1啊？

2022-12-09 10:25 UTC, juncaipeng commented on paddleseg/models/lpsnet.py
> +    def switch_to_deploy(self):
为什么需要融合conv+bn，如果单纯为了部署，这里可以不用考虑。

2022-12-09 10:25 UTC, juncaipeng commented on configs/lpsnet/lpsnet_cityscapes_1536x1024_200k.yml
> +  pretrained:
可以删掉 pretrained:

2022-12-09 10:25 UTC, juncaipeng commented on paddleseg/models/lpsnet.py
> +        size = feats[0].shape[-2:]
用paddle.shape()

2022-12-09 10:25 UTC, juncaipeng commented on paddleseg/models/lpsnet.py
> +    sizes = [x.shape[-2:] for x in feats]
paddle.shape

2022-12-09 10:28 UTC, Asthestarsfalll commented on paddleseg/models/lpsnet.py
> +def lps_net_small(deploy=False, num_classes=19, pretrained=None):
了解，复现要求仅为lpsnet-m

2022-12-09 10:28 UTC, Asthestarsfalll commented on paddleseg/models/lpsnet.py
> +_interpolate = partial(F.interpolate, mode="bilinear", align_corners=True)
是的

2022-12-09 10:28 UTC, Asthestarsfalll commented on paddleseg/models/lpsnet.py
> +            num_classes,
了解

2022-12-09 10:30 UTC, Asthestarsfalll commented on paddleseg/models/lpsnet.py
> +    scale_ratios = [1, 1 / 4, 0]
此处为官方仓库的写法，后面会进行过滤：
```python
 self.scale_ratios = list(filter(lambda x: x > 0, scale_ratios))
```

2022-12-09 10:30 UTC, Asthestarsfalll commented on configs/lpsnet/lpsnet_cityscapes_1536x1024_200k.yml
> +  pretrained:
需要使用预训练模型，但是不清楚上传到哪里，所以后面先空出来了

2022-12-09 10:31 UTC, Asthestarsfalll commented on paddleseg/models/lpsnet.py
> +    def switch_to_deploy(self):
融合后可以继续训练微调

2022-12-12 03:12 UTC, justld commented on configs/lpsnet/lpsnet_cityscapes_1536x1024_200k.yml
> +train_dataset:
配置文件里面各个模块的顺序可以参考https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.7/configs/_base_/cityscapes.yml 和其他配置

2022-12-12 03:12 UTC, justld commented on configs/lpsnet/lpsnet_cityscapes_1536x1024_200k.yml
> +_base_: '../_base_/cityscapes.yml'
文件名需要声明使用的是哪个模型

2022-12-12 03:12 UTC, justld commented on configs/lpsnet/lpsnet_cityscapes_1536x1024_200k.yml
> +    - type: Normalize
@juncaipeng 归一化参数要不要采用默认配置重新训练一次，还是使用这个参数

2022-12-12 03:12 UTC, justld commented on paddleseg/models/lpsnet.py
> +    def expand(cls, module, delta, expand_type, deploy=False):
这个函数的功能是什么

2022-12-12 03:12 UTC, justld commented on test_tipc/configs/lpsnet/lpsnet_cityscapes_1536x1024_200k.yml
> +model:
修改配置文件后，tipc的配置也要同步更改

2022-12-12 05:56 UTC, Asthestarsfalll commented on paddleseg/models/lpsnet.py
> +    def expand(cls, module, delta, expand_type, deploy=False):
参考论文和源代码中的expand，起到类似于搜索功能的作用，可以去掉。

2022-12-12 05:57 UTC, Asthestarsfalll commented on configs/lpsnet/lpsnet_cityscapes_1536x1024_200k.yml
> +    - type: Normalize
论文中是使用ImageNet的mean和std进行训练

2022-12-13 02:25 UTC, juncaipeng commented on configs/lpsnet/lpsnet_cityscapes_1536x1024_200k.yml
> +    - type: Normalize
可以使用这个参数。

2022-12-13 06:13 UTC, Asthestarsfalll commented on configs/lpsnet/lpsnet_cityscapes_1536x1024_200k.yml
> +train_dataset:
done

2022-12-13 06:13 UTC, Asthestarsfalll commented on configs/lpsnet/lpsnet_cityscapes_1536x1024_200k.yml
> +_base_: '../_base_/cityscapes.yml'
done

2022-12-13 06:13 UTC, Asthestarsfalll commented on test_tipc/configs/lpsnet/lpsnet_cityscapes_1536x1024_200k.yml
> +model:
done

2022-12-13 07:14 UTC, Asthestarsfalll commented on paddleseg/models/lpsnet.py
> +    def expand(cls, module, delta, expand_type, deploy=False):
已去除

2022-12-26 03:37 UTC, Bobholamovic requested changes
请参考意见修改文档，并更新模型权重、训练日志链接。

2022-12-26 03:37 UTC, Bobholamovic commented on configs/lpsnet/README.md
> +### ImageNet pretrained
这一部分并没有展示 ImageNet 数据集上的指标。我认为可以不用做一个单独的分节，当做备注或实验过程的文字描述即可。

2022-12-26 03:37 UTC, Bobholamovic commented on configs/lpsnet/README.md
> +Trained medium model of LPSNet on ImageNet dataset for 100 epochs, finally got top-1 accuracy **0.543** and top-5 accuracy **0.786**.
此句有2处语法错误：
1. 缺少主语；
2. 两个子句间缺少连词。

此外，有2处表达不准确：
1. `medium model`：之前未提到过对这个词的定义。如果来自论文，请标示来源；如果是自己创造的、需要说明某种架构，请解释该架构与文中的标准名称的对应关系（可通过同位语）。
2. 描述精度更常见的用法是`0.0543 accuracy`或`accuracy of 0.0543`，`accuracy 0.0543`的用法较少见。

2022-12-26 03:37 UTC, Bobholamovic commented on configs/lpsnet/README.md
> +| -            | lr:0.1                            | coeff:0.0001 |
考虑到`Optimizer`和`Regularizer`列的半数或以上行均为无效行（用`-`划掉），这里的表格的排版形式有些不妥，请考虑修改。或者，可以考虑不采用表格的形式体现超参数设置。

2022-12-26 03:37 UTC, Bobholamovic commented on configs/lpsnet/README.md
> +| Optimizer    | LR Schedular                      | Regularizer  |
typo：`schedular`

2022-12-26 03:37 UTC, Bobholamovic commented on configs/lpsnet/README.md
> +**Data augments**
`augment`只可以作为动词，此处作为名词使用是不合理的。

此外请考虑标题的每个首字母都需要大写。

2022-12-26 03:37 UTC, Bobholamovic commented on configs/lpsnet/README.md
> +| Model | Backbone | Resolution | Training Iters | mIoU | mIoU (flip) | mIoU (ms+flip) | Links |
按照 PaddleSeg 风格，并列的模型架构（如这里的 lpsnet_m、lpsnet_s 和 lpsnet_l）应该放在同一个表格中。此外，请注意统一`Model`列中模型名称和本文档中其它文字表述部分出现的模型名称，例如`LPSNet-m` vs `lpsnet_m`。

2022-12-26 03:37 UTC, Bobholamovic commented on configs/lpsnet/README.md
> +So the following performance are all trained with the first ImageNet pretrained weights.
这个文档面向的读者主要是希望查看 LPSNet 效果并快速上手使用的 PaddleSeg 用户，性质并非实验报告，因此我觉得『没有做』或者『做了发现无效』的内容不适合以这么长的篇幅放在这里讨论。我建议删除该小节，或缩短内容，让读者更多关注到他们感兴趣的信息。

2022-12-26 03:37 UTC, Bobholamovic commented on configs/lpsnet/README.md
> +To make up for the deficiencies of such a low-performance pretrained model, the following attempts are tested:
这里可能让读者感到一伙：`such a low-performance pretrained model` 是指哪个模型？

2022-12-26 03:37 UTC, Bobholamovic commented on configs/lpsnet/README.md
> +3. Decrease the threshold of **OhemCrossEntropyLoss.**
`.`应该放在`**`之后。

2022-12-26 03:37 UTC, Bobholamovic commented on configs/lpsnet/README.md
> +4. Appropriately increase the **learning rate**.
去掉`Appropriately`这样的主观描述。一是为了和前面3点在句式上对齐，二是增加客观性。

2022-12-26 03:37 UTC, Bobholamovic commented on configs/lpsnet/README.md
> +There are plenty of ways to perfect model performance. But with the limited time and computational resources, only a few have been tested. The result is, way 1 and 2 are proven to be valid.
参考之前的意见，我不认为这个文档有必要花这么长的文字讨论和最终展示的精度指标无关的实验设置。如果是考虑到严谨性或者是希望体现我们做过的尝试，我建议放在备注部分稍微说明一下我们还做过哪些没有成功的尝试。

我仍然坚持文档的主体部分需要突出读者感兴趣的内容，即：
1. 我们的模型效果如何；
2. 模型预训练权重和日志在哪；
3. 相比原作我们做了哪些比较大的改动，才得到的我们提供的结果。

2022-12-26 03:37 UTC, Bobholamovic commented on configs/lpsnet/lpsnet_l_cityscapes_1536x1024_200k.yml
> +_base_: '../_base_/cityscapes.yml'
LPSNet-l、LPSNet-m和 LPSNet-s 3个架构的配置文件冗余度过高，观察可知可复用部分其实很多。建议采用配置文件继承的方式复用公共部分，减少冗余。

2022-12-26 06:40 UTC, Asthestarsfalll commented on configs/lpsnet/README.md
> +### ImageNet pretrained
这里移动到后面了，希望能使读者首先关注到模型在Cityscapes上的表现。

2022-12-26 06:41 UTC, Asthestarsfalll commented on configs/lpsnet/README.md
> +Trained medium model of LPSNet on ImageNet dataset for 100 epochs, finally got top-1 accuracy **0.543** and top-5 accuracy **0.786**.
这里去除了

2022-12-26 06:42 UTC, Asthestarsfalll commented on configs/lpsnet/README.md
> +**Data augments**
已修改。

2022-12-26 06:42 UTC, Asthestarsfalll commented on configs/lpsnet/README.md
> +| Model | Backbone | Resolution | Training Iters | mIoU | mIoU (flip) | mIoU (ms+flip) | Links |
已修改

2022-12-26 06:43 UTC, Asthestarsfalll commented on configs/lpsnet/README.md
> +To make up for the deficiencies of such a low-performance pretrained model, the following attempts are tested:
添加了说明

2022-12-26 06:43 UTC, Asthestarsfalll commented on configs/lpsnet/README.md
> +4. Appropriately increase the **learning rate**.
已修改

2022-12-26 06:43 UTC, Asthestarsfalll commented on configs/lpsnet/lpsnet_l_cityscapes_1536x1024_200k.yml
> +_base_: '../_base_/cityscapes.yml'
这里添加了一个base config的文件，不清楚这样是否符合规范？

2022-12-26 06:46 UTC, Asthestarsfalll commented on configs/lpsnet/README.md
> +There are plenty of ways to perfect model performance. But with the limited time and computational resources, only a few have been tested. The result is, way 1 and 2 are proven to be valid.
这三点都在Cityscapes小节中体现，预训练过程移动至最后，如读者有兴趣可往下阅读

2022-12-27 04:11 UTC, Bobholamovic commented on configs/lpsnet/README.md
> +Note that: To make up for the deficiencies of low-performance pretrained(see [ImageNet](#ImageNet)) models, the following changes are applied:
```
Note that: Since the original paper does not provide all the implementation details, nor release the official training code, we first pre-trained the models on the ImageNet dataset, and then fine-tuned the models on the Cityscapes dataset. Specifically, compared with the experimental settings in the original paper, we made two significant changes during fine-tuning to obtain the above results:

1. Extend iterations to **200k**.
2. Adjust the parameters used in **color jittering**.

For the pre-training results of the models on the ImageNet dataset, please see the [ImageNet](#ImageNet) section, where we also have a discussion on the impact of the pre-trained model.
```

2022-12-27 04:11 UTC, Bobholamovic commented on configs/lpsnet/README.md
> +| Optimizer          | LR Schedular                       | Regularizer  |
`Schedular` -> `Scheduler`

2022-12-27 04:11 UTC, Bobholamovic commented on configs/lpsnet/README.md
> +With the pretrained model, lpsnet_m is able to obtain **74.28%** mIoU on CityScapes eval set, whose training settings followed description in the official paper.
`With the pre-trained model, lpsnet_m is able to obtain **74.28%** mIoU on Cityscapes val set under the same experimental settings as the original paper.`

2022-12-27 04:11 UTC, Bobholamovic commented on configs/lpsnet/README.md
>  Furthermore, in order to obtain the best performance of semantic segmentation and accelerate convergence speed, more complicated data augments are applied, for instance, **random erasing** and batch
这三段建议直接整合成一段：

```
Further more, we also tried more complicated data augmentation strategies, e.g. random erasing and batched mix-up. The performance of classification improved by a considerable margin: on the ImageNet dataset, the top-1 accuracy increased to **0.564** and the top-5 accuracy increased to **0.805**. However, we did not observe better segmentation performance of the model on the Cityscapes dataset using these pre-trained models. Therefore, these data augmentation strategies were not used.
```

2022-12-27 04:11 UTC, Bobholamovic commented on test_tipc/configs/lpsnet/_base_cityscapes_1536x1024_200k.yml
> +_base_: '../_base_/cityscapes.yml'
这个上次忘了提到，TIPC 只需要加一种模型配置即可，不用三种规格都加的。

2022-12-27 04:11 UTC, Bobholamovic commented on configs/lpsnet/_base_cityscapes_1536x1024_200k.yml
> +_base_: '../_base_/cityscapes.yml'
按照 PaddleSeg 已有配置文件的风格，这里可以考虑写一个完整的`lpsnet_m`的配置文件，其它两个配置文件继承它并复写一些配置项。

2022-12-27 08:07 UTC, Asthestarsfalll commented on configs/lpsnet/_base_cityscapes_1536x1024_200k.yml
> +_base_: '../_base_/cityscapes.yml'
已修改

2022-12-27 08:08 UTC, Asthestarsfalll commented on test_tipc/configs/lpsnet/_base_cityscapes_1536x1024_200k.yml
> +_base_: '../_base_/cityscapes.yml'
已去除

2022-12-27 08:08 UTC, Asthestarsfalll commented on configs/lpsnet/README.md
>  Furthermore, in order to obtain the best performance of semantic segmentation and accelerate convergence speed, more complicated data augments are applied, for instance, **random erasing** and batch
已修改

2022-12-27 08:08 UTC, Asthestarsfalll commented on configs/lpsnet/README.md
> +| Optimizer          | LR Schedular                       | Regularizer  |
已修改

2022-12-27 08:09 UTC, Asthestarsfalll commented on configs/lpsnet/README.md
> +Note that: To make up for the deficiencies of low-performance pretrained(see [ImageNet](#ImageNet)) models, the following changes are applied:
已修改

2022-12-27 11:18 UTC, Bobholamovic approved these changes
LGTM.

2022-12-28 03:07 UTC, juncaipeng approved these changes
LGTM

2022-12-28 03:07 UTC, merged