Get through the whole process of remote sensing
PaddlePaddle/PaddleSeg pull request #287
Opened 2020-06-05 14:52 UTC by LutaoChu

1 新增数据分析和数据校验工具
2 支持.tif, .img格式读取
3 适配新的多分类数据集
4 新增可视化模块

2020-06-05 15:15 UTC, ZeyuChen requested changes
存在大量非规范用法，需要修改

2020-06-05 15:15 UTC, ZeyuChen commented on contrib/RemoteSensing/tools/compute_normalization_coefficient.py
> +# copyright (c) 2020 PaddlePaddle Authors. All Rights Reserve.
License 格式不对

2020-06-05 15:15 UTC, ZeyuChen commented on contrib/RemoteSensing/tools/compute_normalization_coefficient.py
> +        # count clip value percentage
注释规范不对，一律按标准英文语法注释
# Calculate clip value percentage

2020-06-05 15:15 UTC, ZeyuChen commented on contrib/RemoteSensing/tools/compute_normalization_coefficient.py
> +    MEANS = [i / TOTAL_IMG_NUM for i in MEANS]
python 大写变量一般用于表示常量，这个gloabl用法不规范，不建议用global

2020-06-05 15:15 UTC, ZeyuChen commented on contrib/RemoteSensing/tools/compute_normalization_coefficient.py
> +# copyright (c) 2020 PaddlePaddle Authors. All Rights Reserve.
`# Copyright ...... All Right Reserved.`

2020-06-05 15:15 UTC, ZeyuChen commented on contrib/RemoteSensing/tools/compute_normalization_coefficient.py
> +    global MEANS, STDS, TOTAL_IMG_NUM, CLIP_MIN_VALUE, CLIP_MAX_VALUE
global用法不标准，不要小写变量，应该是传入, 这个接口应该是传入图片，返回均值反差，再上一层函数完成全局均值累计和方差计算。以接口方式考虑设计，不要以流程方式来设计。

2020-06-05 15:15 UTC, ZeyuChen commented on contrib/RemoteSensing/tools/data_analyse_and_check.py
> +    global IMG_VALUE_NUM, MEANS, STDS, TOTAL_IMG_NUM, CLIP_MIN_VALUE, CLIP_MAX_VALUE, IMG_MIN_VALUE, IMG_MAX_VALUE
非规范用法

2020-06-07 12:09 UTC, LutaoChu commented on contrib/RemoteSensing/tools/compute_normalization_coefficient.py
> +# copyright (c) 2020 PaddlePaddle Authors. All Rights Reserve.
已经修改

2020-06-07 12:10 UTC, LutaoChu commented on contrib/RemoteSensing/tools/compute_normalization_coefficient.py
> +        # count clip value percentage
已按标准英文语法注释

2020-06-07 12:10 UTC, LutaoChu commented on contrib/RemoteSensing/tools/compute_normalization_coefficient.py
> +    MEANS = [i / TOTAL_IMG_NUM for i in MEANS]
已移除所有global

2020-06-07 12:11 UTC, LutaoChu commented on contrib/RemoteSensing/tools/compute_normalization_coefficient.py
> +    global MEANS, STDS, TOTAL_IMG_NUM, CLIP_MIN_VALUE, CLIP_MAX_VALUE
已按照接口方式设计所有函数

2020-06-07 12:11 UTC, LutaoChu commented on contrib/RemoteSensing/tools/data_analyse_and_check.py
> +    global IMG_VALUE_NUM, MEANS, STDS, TOTAL_IMG_NUM, CLIP_MIN_VALUE, CLIP_MAX_VALUE, IMG_MIN_VALUE, IMG_MAX_VALUE
已移除global

2020-06-07 12:24 UTC, ZeyuChen requested changes
大部分OK，剩下几个函数名细节在改下就可以合入了

2020-06-07 12:24 UTC, ZeyuChen commented on contrib/RemoteSensing/readers/reader.py
>      """读取语分分割任务数据集，并对样本进行相应的处理。
语分分割？

2020-06-07 12:24 UTC, ZeyuChen commented on contrib/RemoteSensing/tools/compute_normalization_coefficient.py
> +# Copyright (c) 2020 PaddlePaddle Authors. All Rights Reserved.
python文件名精简为 cal_norm_coef.py
coef为coeffcient的缩写，通常python文件名一般会精简

2020-06-07 12:24 UTC, ZeyuChen commented on contrib/RemoteSensing/tools/compute_normalization_coefficient.py
> +def compute_normalize_coefficient(data_dir, separator, clip_min_value,
compute缩写为cal，其他可以保持不变。
compute没缩写形式，calcualte大部分情况缩写为cal

2020-06-07 12:24 UTC, ZeyuChen commented on contrib/RemoteSensing/tools/compute_normalization_coefficient.py
> +def compute_clip_percentage(pkl_path, clip_min_value, clip_max_value):
注释写calculate，为啥函数名要compute

2020-06-07 12:24 UTC, ZeyuChen commented on contrib/RemoteSensing/tools/compute_normalization_coefficient.py
> +    compute_normalize_coefficient(data_dir, separator, clip_min_value,
函数名精简

2020-06-07 13:06 UTC, LutaoChu commented on contrib/RemoteSensing/readers/reader.py
>      """读取语分分割任务数据集，并对样本进行相应的处理。
已去除

2020-06-07 13:08 UTC, LutaoChu commented on contrib/RemoteSensing/tools/compute_normalization_coefficient.py
> +# Copyright (c) 2020 PaddlePaddle Authors. All Rights Reserved.
已改成简写

2020-06-07 13:08 UTC, LutaoChu commented on contrib/RemoteSensing/tools/compute_normalization_coefficient.py
> +def compute_normalize_coefficient(data_dir, separator, clip_min_value,
已改成缩写形式

2020-06-07 13:08 UTC, LutaoChu commented on contrib/RemoteSensing/tools/compute_normalization_coefficient.py
> +def compute_clip_percentage(pkl_path, clip_min_value, clip_max_value):
统一改成cal了

2020-06-07 13:08 UTC, LutaoChu commented on contrib/RemoteSensing/tools/compute_normalization_coefficient.py
> +    compute_normalize_coefficient(data_dir, separator, clip_min_value,
已精简

2020-06-07 13:39 UTC, ZeyuChen approved these changes
LGTM

2020-06-07 13:39 UTC, merged