[Feature] Add SegNext Model
PaddlePaddle/PaddleSeg pull request #2925
Opened 2023-01-19 13:54 UTC by Asthestarsfalll

### PR types

New features
### PR changes

Models
### Description

Add SegNext Model

2023-01-28 12:30 UTC, Bobholamovic requested changes
整体完成度较高，但在代码风格等方面有一些意见和建议。

2023-01-28 12:30 UTC, Bobholamovic commented on configs/segnext/README.md
> +**Note: There are some potential errors that will cause training collapse when use multiple GPUs. Or you can train SegNeXt without customing learning rate and weight decay of each parameters. You als
这里好像有些不太看得明白，请问要表达的中文意思是什么样的呀？

2023-01-28 12:30 UTC, Bobholamovic commented on configs/segnext/README.md
> +> arXiv preprint arXiv:2207.13600 (2022).
这里格式是不是有点异常？citation 中一般不含空行

2023-01-28 12:30 UTC, Bobholamovic commented on configs/segnext/segnext_mscan_tiny_1024x1024_cityscapes_160k.yml
> +    pretrained: /root/paddlejob/workspace/code/PaddleSeg/paddle_mscan_t.pdparams
该路径在权重文件上传后需要修改

2023-01-28 12:30 UTC, Bobholamovic commented on configs/segnext/segnext_mscan_tiny_1024x1024_cityscapes_160k.yml
> +    align_corners: false
为统一风格，建议使用大写字母开头的`False`。

2023-01-28 12:30 UTC, Bobholamovic commented on paddleseg/models/backbones/mscan.py
> +def mscan_t(**kwargs):
mscan 系列 backbone 命名不符合规范。此处 callable 对象虽然实际是函数，但因为被注册为组件，因此仍按照 class 命名规则（不过有个规则可以宽松些：下划线后的后缀部分可自由选择用大写或小写字母开头）。可参考：https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.7/paddleseg/models/backbones/top_transformer.py

2023-01-28 12:30 UTC, Bobholamovic commented on paddleseg/models/layers/layer_libs.py
> +class ConvGNAct(nn.Layer):
讨论：是否有必要建立更通用的 conv-norm-act，因为 conv-gn-act 与 conv-bn-relu 都是其特例。

2023-01-28 12:30 UTC, Bobholamovic commented on paddleseg/models/layers/nmf_2d.py
> +    def __init__(self, args=dict()):
请勿使用 mutable objects 作为 default value

2023-01-28 12:30 UTC, Bobholamovic commented on paddleseg/models/layers/nmf_2d.py
> +class _MatrixDecomposition2DBase(nn.Layer):
因后续使用到`abc.abstractmethod`，请确认此类是否使用 abc.ABC 作为元类。

2023-01-28 12:30 UTC, Bobholamovic commented on paddleseg/models/segnext.py
> +            ham_kwargs=dict(), ):
同上。

2023-01-28 12:30 UTC, Bobholamovic commented on paddleseg/models/segnext.py
> +            ham_kwargs=dict(), ):
同上。

2023-01-28 12:30 UTC, Bobholamovic commented on paddleseg/models/segnext.py
> +    """The head implementation of HamNet based on PaddlePaddle.
doc string 与实际参数不匹配。

2023-01-28 12:30 UTC, Bobholamovic commented on paddleseg/transforms/transforms.py
> +class RandomCrop:
为何需要新建此变换算子？是否可复用已有算子？

2023-01-29 06:58 UTC, Asthestarsfalll commented on configs/segnext/README.md
> +**Note: There are some potential errors that will cause training collapse when use multiple GPUs. Or you can train SegNeXt without customing learning rate and weight decay of each parameters. You als
就是 多卡训练会有潜在的问题，如果想使用多卡训练可以去除参数自定义，并且把学习率扩大十倍

2023-01-29 06:59 UTC, Asthestarsfalll commented on configs/segnext/segnext_mscan_tiny_1024x1024_cityscapes_160k.yml
> +    pretrained: /root/paddlejob/workspace/code/PaddleSeg/paddle_mscan_t.pdparams
了解

2023-01-29 07:29 UTC, Asthestarsfalll commented on configs/segnext/README.md
> +> arXiv preprint arXiv:2207.13600 (2022).
已修改

2023-01-29 07:32 UTC, Asthestarsfalll commented on configs/segnext/segnext_mscan_tiny_1024x1024_cityscapes_160k.yml
> +    align_corners: false
已修改

2023-01-29 07:32 UTC, Asthestarsfalll commented on paddleseg/models/layers/nmf_2d.py
> +class _MatrixDecomposition2DBase(nn.Layer):
已修改

2023-01-29 07:32 UTC, Asthestarsfalll commented on paddleseg/models/backbones/mscan.py
> +def mscan_t(**kwargs):
已修改

2023-01-29 07:32 UTC, Asthestarsfalll commented on paddleseg/models/layers/nmf_2d.py
> +    def __init__(self, args=dict()):
已修改

2023-01-29 07:32 UTC, Asthestarsfalll commented on paddleseg/models/segnext.py
> +    """The head implementation of HamNet based on PaddlePaddle.
已修改

2023-01-29 07:35 UTC, Asthestarsfalll commented on paddleseg/transforms/transforms.py
> +class RandomCrop:
paddleseg中Crop相关的transorms都为center crop，这里希望做到在图片上的随机位置裁剪

2023-01-30 08:18 UTC, Bobholamovic commented on configs/segnext/README.md
> +**Note: There are some potential errors that will cause training collapse when use multiple GPUs. Or you can train SegNeXt without customing learning rate and weight decay of each parameters. You als
我们最终的配置文件是和原文一致么？这里的『学习率扩大十倍』是单指 backbone 的学习率还是整个模型？

2023-01-30 08:23 UTC, Bobholamovic commented on paddleseg/transforms/transforms.py
> +class RandomCrop:
对于第一个功能，`RandomPaddingCrop`是否已经满足需求？对于第二个功能，如果`RandomPaddingCrop`满足第一个需求的话，可以在此基础上新增附加功能，增强该算子。

2023-02-01 09:06 UTC, Asthestarsfalll commented on configs/segnext/README.md
> +**Note: There are some potential errors that will cause training collapse when use multiple GPUs. Or you can train SegNeXt without customing learning rate and weight decay of each parameters. You als
单卡训练是一致的，多卡训练需要将custom_cfg去除，再将整体学习率扩大十倍

2023-02-01 09:53 UTC, Asthestarsfalll commented on paddleseg/transforms/transforms.py
> +class RandomCrop:
已修改

2023-02-01 10:13 UTC, Asthestarsfalll commented on paddleseg/models/layers/layer_libs.py
> +class ConvGNAct(nn.Layer):
我认为加不加都行。ConvNormAct虽然比较通用，但是有些情况比较用起来比较臃肿，比如想使用 DepthwiseConvGNLeakyReLU，传入的参数将会相当复杂。我更倾向于使用`partial`或者函数来简化使用，比如：
```python
def get_depthwise_conv_gn_leakyrelu(*args,  **kwargs):
    return ConvNormAct(......)

ConvGNReLU = partial(ConvNormAct(norm_type='gn', act_type='relu'))
```
还有模型组件的名称，比如BatchNorm我更倾向于使用bn，GroupNorm使用gn，查看权重时更容易理解。
以及ConvBN、ConvReLu等是否也是ConvNormAct的特例。

2023-02-10 08:58 UTC, Bobholamovic reviewed
基本 OK，留了一些小意见

2023-02-10 08:58 UTC, Bobholamovic commented on configs/segnext/README.md
> +**Note: There are some potential errors that will cause training collapse when use multiple GPUs. Or you can train SegNeXt without customing learning rate and weight decay of each parameters. You als
请检查是否表达如下意思：

**Note: The above results were obtained with a model trained on a single GPU. In the current implementation, we found some potential issues that could cause training to crash when using multiple GPUs. As a work around for multi-card training, we recommend deleting the layer-wise custom configuration of learning rate and weight decay in the configuration file (i.e. the `custom_cfg` key-value pair in `optimizer`). At the same time, amplify the learning rate by 10 times. With this setup, we obtain the following results. Model training was performed on four GPUs.**

2023-02-10 08:58 UTC, Bobholamovic commented on paddleseg/models/layers/nmf_2d.py
> +        if not isinstance(args, dict):
根据此处逻辑，建议设置如下处理：

```
if args is None:
    args = dict()
elif not isinstance(args, dict):
    raise TypeError("`args` must be a dict, but got {}".foramt(args.__class__.__name__))
```

2023-02-10 08:58 UTC, Bobholamovic commented on paddleseg/models/segnext.py
> +    Args:
`Args`前面加一个空行

2023-02-10 08:58 UTC, Bobholamovic commented on paddleseg/models/backbones/mscan.py
> +        mlp_ratio (float): Ratio of mlp hidden dim to embedding dim. Default: 4.
docstring 与实际不符，此外可选参数需要添加 `optional`。请一并检查代码其他地方。

2023-02-10 08:58 UTC, Bobholamovic commented on paddleseg/models/backbones/mscan.py
> +# copyright (c) 2020 PaddlePaddle Authors. All Rights Reserve.
时间修改为2023。请一并检查代码其他地方。

2023-02-13 08:00 UTC, Asthestarsfalll commented on configs/segnext/README.md
> +**Note: There are some potential errors that will cause training collapse when use multiple GPUs. Or you can train SegNeXt without customing learning rate and weight decay of each parameters. You als
要不要说明一下总batch size数保持一致？

2023-02-13 12:55 UTC, Asthestarsfalll commented on paddleseg/models/layers/nmf_2d.py
> +        if not isinstance(args, dict):
已修改

2023-02-13 12:56 UTC, Asthestarsfalll commented on paddleseg/models/segnext.py
> +    Args:
已修改

2023-02-13 12:56 UTC, Asthestarsfalll commented on paddleseg/models/backbones/mscan.py
> +        mlp_ratio (float): Ratio of mlp hidden dim to embedding dim. Default: 4.
已修改

2023-02-13 12:56 UTC, Asthestarsfalll commented on paddleseg/models/backbones/mscan.py
> +# copyright (c) 2020 PaddlePaddle Authors. All Rights Reserve.
已修改

2023-02-16 09:03 UTC, Bobholamovic submitted a review, later dismissed

2023-02-16 09:03 UTC, Bobholamovic commented on configs/segnext/README.md
> +**Note: There are some potential errors that will cause training collapse when use multiple GPUs. Or you can train SegNeXt without customing learning rate and weight decay of each parameters. You als
可以的，说明一下。

Note: The above results were obtained with a model trained on a single GPU. In the current implementation, we found some potential issues that could cause training to crash when using multiple GPUs. As a work around for multi-card training, we recommend deleting the layer-wise custom configuration of learning rate and weight decay in the configuration file (i.e. the custom_cfg key-value pair in optimizer). At the same time, amplify the learning rate by 10 times. We also note that the total batch size across all GPUs should be kept the same as in single-card training. With this setup, we obtain the following results. Model training was performed on four GPUs.

2023-02-20 03:38 UTC, juncaipeng reviewed
参考文档：https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.7/docs/pr/pr/style_cn.md

尤其注意不要在transforms中引入bug。

2023-02-20 03:38 UTC, juncaipeng commented on configs/segnext/README.md
> +| SegNeXt | MSCAN_T  | 1024x1024  |     160000     | 80.25% |   80.58%    |     80.75%     | [model]() \| [log]() \| [vdl]() |
只训练了一个型号的模型，原文还有S B L的模型

2023-02-20 03:38 UTC, juncaipeng commented on configs/segnext/segnext_mscan_tiny_1024x1024_cityscapes_160k.yml
> +
这个yml文件的命名格式错误

2023-02-20 03:38 UTC, juncaipeng commented on paddleseg/models/layers/nmf_2d.py
> +class NMF2D(_MatrixDecomposition2DBase):
这个模块是否是通用的？
建议注释说明这个模块的论文出处，便于后续同学学习。

2023-02-20 03:38 UTC, juncaipeng commented on paddleseg/models/segnext.py
> +    def __init__(self, backbone, decoder_cfg, num_classes, pretrained=None):
需要使用backbone_indices来标明使用backbone的输出feature，便于backbone的替换

2023-02-20 03:38 UTC, juncaipeng commented on paddleseg/transforms/transforms.py
> +        if img_shape[0] == self.crop_size[0] and img_shape[1] == self.crop_size[
img_shape是(h, w), crop_size是(w, h)，对应错误

2023-02-20 03:38 UTC, juncaipeng commented on paddleseg/transforms/transforms.py
> +        pad_height = max(self.crop_size[0] - img_shape[0], 0)
img_shape是(h, w), crop_size是(w, h)，对应错误

2023-02-20 03:38 UTC, juncaipeng commented on configs/segnext/segnext_mscan_tiny_1024x1024_cityscapes_160k.yml
> +    - type: Padding
不需要padding了吧

2023-02-20 03:38 UTC, juncaipeng commented on paddleseg/transforms/transforms.py
> +        margin_h = max(origin_size[0] - self.crop_size[0], 0)
img_shape是(h, w), crop_size是(w, h)，对应错误

2023-02-20 05:16 UTC, Asthestarsfalll commented on paddleseg/transforms/transforms.py
> +        if img_shape[0] == self.crop_size[0] and img_shape[1] == self.crop_size[
已修改

2023-02-20 05:16 UTC, Asthestarsfalll commented on paddleseg/models/segnext.py
> +    def __init__(self, backbone, decoder_cfg, num_classes, pretrained=None):
已修改

2023-02-20 05:16 UTC, Asthestarsfalll commented on paddleseg/models/layers/nmf_2d.py
> +class NMF2D(_MatrixDecomposition2DBase):
来源于论文Is Attention Better Than Matrix Decomposition，个人认为是一个通用的模块。

2023-02-20 05:16 UTC, Asthestarsfalll commented on configs/segnext/segnext_mscan_tiny_1024x1024_cityscapes_160k.yml
> +
已修改

2023-02-27 08:45 UTC, Asthestarsfalll commented on configs/segnext/README.md
> +| SegNeXt | MSCAN_T  | 1024x1024  |     160000     | 80.25% |   80.58%    |     80.75%     | [model]() \| [log]() \| [vdl]() |
已添加

2023-02-28 09:06 UTC, Bobholamovic approved these changes, later dismissed
上一轮 review 意见已修改完成。另外做了一些文本上的修改。

2023-03-01 03:11 UTC, Asthestarsfalll commented
导出时必须指定形状
![2023-03-01_11-08](https://user-images.githubusercontent.com/72954905/222035361-9aaec242-aa4e-4706-9ed1-fce49eb73a7d.png)
推理结果
![2023-03-01_11-09](https://user-images.githubusercontent.com/72954905/222035370-142d2318-23f9-48fd-845b-0ce3fee4c2c8.png)

2023-03-02 09:58 UTC, juncaipeng submitted a review, later dismissed
LGTM

2023-03-02 10:02 UTC, juncaipeng approved these changes

2023-03-02 11:54 UTC, merged