Aim
PaddlePaddle/PaddleSeg pull request #2941
Opened 2023-02-01 05:37 UTC by PommesPeter

### PR types

New features

### PR changes

Models, APIs

### Description

added AIM to ppmatting

2023-02-02 12:40 UTC, Bobholamovic requested changes
留了一些意见，请修改后回复 done 或回复不同意见。

2023-02-02 12:40 UTC, Bobholamovic commented on .gitignore
> +data
请问修改这里的理由是？

2023-02-02 12:40 UTC, Bobholamovic commented on Matting/configs/aim/aim-resnet34_mp.yml
> +  dataset_root: /home/aistudio/data/data184700
请勿使用绝对路径

2023-02-02 12:40 UTC, Bobholamovic commented on Matting/configs/aim/aim-resnet34_mp.yml
> +  dataset_root: /home/aistudio/data/data176745/matting_datasets
请勿使用绝对路径

2023-02-02 12:40 UTC, Bobholamovic commented on Matting/configs/aim/aim-resnet34_mp.yml
> +#   backbone:
请问这里是有意留下的注释还是忘记移除的无效配置？

2023-02-02 12:40 UTC, Bobholamovic commented on Matting/ppmatting/datasets/matting_dataset.py
> +                trimap_path = os.path.join(self.dataset_root, fg_bg_file[2])
请说明修改此行为的原因

2023-02-02 12:40 UTC, Bobholamovic commented on Matting/ppmatting/datasets/__init__.py
> +from .hybrid_dataset import HybridDataset
缺少对 `AIM500` 的 import

2023-02-02 12:40 UTC, Bobholamovic commented on Matting/ppmatting/transforms/transforms.py
> +    Resize the image for different testing strategy.
1. `for` -> `using`
2. `strategy` -> `strategies`

2023-02-02 12:40 UTC, Bobholamovic commented on Matting/ppmatting/transforms/transforms.py
> +        if_hybrid (bool): Enable hybird test strategy. Default: False
可选参数需添加 `optional`。

2023-02-02 12:40 UTC, Bobholamovic commented on Matting/ppmatting/transforms/transforms.py
> +        global_ratio (float, optional): The scale ratio of global. Default: 0.25.
这里的`global`和`local`分别是指？

2023-02-02 12:40 UTC, Bobholamovic commented on Matting/ppmatting/transforms/transforms.py
> +                "Type of global_ratio or local_ratio is invalid. It should be float, now is {}, {}"
`now is` -> `but now it is`。下同。

2023-02-02 12:40 UTC, Bobholamovic commented on Matting/ppmatting/models/aim.py
> +        # for m in self.modules():
无用注释请去除

2023-02-02 12:40 UTC, Bobholamovic commented on Matting/ppmatting/datasets/hybrid_dataset.py
> +class HybridDataset(MattingDataset):
建议在 docstring 中说明这个数据集是由哪些数据集组成（或者怎么样准备这个数据集），其中的处理 pipeline 出自哪篇论文，以及该数据集接口是否可以复用。

2023-02-02 12:40 UTC, Bobholamovic commented on Matting/ppmatting/datasets/aim_500.py
> +                    "When `mode` is 'val' or 'trainval', `val_file must be provided!"
`val_file`缺少右半边反引号

2023-02-02 12:40 UTC, Bobholamovic commented on Matting/ppmatting/datasets/hybrid_dataset.py
> +class HybridDataset(MattingDataset):
这个类重写了大量`MattingDataset`的方法。请考虑能否尽可能复用父类的方法。

2023-02-02 12:40 UTC, Bobholamovic commented on Matting/ppmatting/models/aim.py
> +from skimage.transform import resize
`numpy`和`skimage`同属第三方库，按照代码风格规范，应该放在一个 block。

2023-02-02 12:40 UTC, Bobholamovic commented on Matting/ppmatting/models/aim.py
> +        resnet = resnet34_mp()
若 backbone 部分可复用，建议剥离后实现在 `Matting/ppmatting/models/backbone`中。

2023-02-02 12:40 UTC, Bobholamovic commented on Matting/ppmatting/models/aim.py
> +    __constants__ = ['downsample']
未使用

2023-02-02 12:40 UTC, Bobholamovic commented on Matting/ppmatting/models/aim.py
> +
无需空行

2023-02-10 07:05 UTC, Bobholamovic reviewed
留了一些小意见。

2023-02-10 07:05 UTC, Bobholamovic commented on Matting/ppmatting/datasets/matting_dataset.py
> -
此处不应该去除空行

2023-02-10 07:05 UTC, Bobholamovic commented on Matting/ppmatting/datasets/hybrid_dataset.py
> +class HybridDataset(paddle.io.Dataset):
1. 请说明该类不继承自`MattingDataset`的原因。
2. `__init__()`部分与 `MattingDataset` 的 `__init__()` 有很大的重合。
3. 请为此类补充 docstring 或在 docs 中添加说明文档。
4. 如果 `HyBridDataset` 类型的数据集需要用户自行手动制作，我们可能需要在 `tools` 中提供相关的数据集制作脚本。

2023-02-10 07:05 UTC, Bobholamovic commented on Matting/ppmatting/models/backbone/__init__.py
> +from .resnet_mp import *
此处无需插入一个额外的空行

2023-02-10 07:05 UTC, Bobholamovic commented on Matting/ppmatting/models/backbone/resnet_mp.py
> +def resnet34_mp(**kwargs):
这个函数好像没有用到。此外，请勿硬编码绝对路径。

2023-02-10 07:05 UTC, Bobholamovic commented on Matting/ppmatting/models/backbone/resnet_mp.py
> +def ResNet34_mp(**args):
请问`ResNet_mp`的 `mp` 表示？

2023-02-10 07:05 UTC, Bobholamovic commented on Matting/ppmatting/datasets/aim_500.py
> +class AIM500(paddle.io.Dataset):
请说明该类不继承自 `MattingDataset` 的原因。

2023-02-10 07:05 UTC, Bobholamovic commented on Matting/ppmatting/datasets/hybrid_dataset.py
> +            # k_size = random.choice(range(2, 5))
无用的注释请去除，后同。

2023-02-10 07:05 UTC, Bobholamovic commented on Matting/ppmatting/datasets/hybrid_dataset.py
> +    def gen_trimap(alpha, mode='train', eval_kernel=7):
这个函数有点儿 hard-coding，请问是否能提供使用当前这套参数和方法的 reference？

2023-02-10 07:05 UTC, Bobholamovic commented on Matting/ppmatting/models/aim.py
> +
import 语句与类定义之间空两行。

2023-02-10 07:05 UTC, Bobholamovic commented on Matting/ppmatting/transforms/transforms.py
> +        global_ratio (float, optional): The scale ratio of global down-sampling. Default: 0.25.
`scale ratio` -> `scaling ratio`，后同。

2023-02-10 07:05 UTC, Bobholamovic commented on Matting/ppmatting/transforms/transforms.py
> +        max_size (list|tuple, optional): The maxiumn size of image. index 0 means height of image, and index 1 means width of image. Default: [1600, 1600].
`The maxiumn size of image. index 0 means height of image, and index 1 means width of image.`
-> `The maxiumn size of image in [height, width] format.`。

此外，已有的 transforms 中的 `Resize` 似乎是使用 [width, height] 的顺序（与 OpenCV 一致），请尽可能保证套件内部各 transform 参数风格一致。

2023-02-10 07:05 UTC, Bobholamovic commented on Matting/ppmatting/transforms/transforms.py
> +                    max_size=[1600, 1600],
[请勿使用 mutable objects 作为参数默认值](https://florimond.dev/en/posts/2018/08/python-mutable-defaults-are-the-source-of-all-evil/)。建议将 list 替换为 tuple。

2023-02-10 07:05 UTC, Bobholamovic commented on Matting/ppmatting/transforms/transforms.py
> +        if_hybrid (bool, optional): Enable hybrid-resolution test strategy. Default: False
遗漏了句号。

2023-02-10 07:05 UTC, Bobholamovic commented on Matting/ppmatting/models/aim.py
> +class AIM(nn.Layer):
缺少 docstring

2023-02-16 08:59 UTC, Bobholamovic commented on Matting/ppmatting/datasets/hybrid_dataset.py
> +    Prepare a hybrid dataset, use `create_hybrid_list.py` to generate `train.txt`.
`To prepare a hybrid dataset`

2023-02-16 09:14 UTC, Bobholamovic commented on Matting/tools/data/create_hybrid_list.py
> +DIM_DATASET_ROOT_PATH = osp.join(dataset_root, "Composition-1k")
在后续过程中，需要 RD 同学添加对 Distinctions646 数据集的混入支持。

2024-03-04 08:33 UTC, shiyutang commented
将不再支持新增数据集。

2024-03-04 08:33 UTC, closed without merging