[Feature] Support set device id in predict
PaddlePaddle/PaddleSeg pull request #3347
Opened 2023-06-30 11:39 UTC by Asthestarsfalll

### PR types

New features
### PR changes

Others
### Description

Support set device id in predict

2023-07-03 03:23 UTC, shiyutang commented on tools/predict.py
> +    device = f"{args.device}:{args.device_id}"
因为不是所有的设备都可以指定device_id，建议增加下面这行代码：
if args.device =='gpu':

2023-07-03 03:25 UTC, shiyutang requested changes
详细修改在评论中

2023-07-03 04:55 UTC, Asthestarsfalll commented on tools/predict.py
> +    device = f"{args.device}:{args.device_id}"
已修改

2023-07-04 01:31 UTC, shiyutang approved these changes
LGTM

2023-07-04 01:32 UTC, merged