[Feature] Add MobileSAM
PaddlePaddle/PaddleSeg pull request #3349
Opened 2023-06-30 13:36 UTC by Asthestarsfalll

### PR types

### PR changes

### Description

2023-07-04 01:41 UTC, shiyutang requested changes
需要验证加载相同参数情况下，前向推理随机数输入和图片输入均和mobileSAM对齐。另外模型参数可以给我链接上传。

2023-07-04 01:41 UTC, shiyutang commented on contrib/SegmentAnything/scripts/amg_paddle.py
> +    "https://bj.bcebos.com/paddleseg/dygraph/paddlesegAnything/vit_t/model.pdparams",
这个链接没有办法下载任何模型

2023-07-04 01:41 UTC, shiyutang commented on contrib/SegmentAnything/scripts/amg_paddle.py
> +    help="The type of model to load, in ['vit_h', 'vit_l', 'vit_b', 'vit_l']", )
vit_l键值重复

2023-07-04 01:41 UTC, shiyutang commented on contrib/SegmentAnything/scripts/promt_predict.py
> +    "https://bj.bcebos.com/paddleseg/dygraph/paddlesegAnything/vit_t/model.pdparams",
同上

2023-07-04 01:41 UTC, shiyutang commented on contrib/SegmentAnything/scripts/text_to_sam_clip.py
> +    "https://bj.bcebos.com/paddleseg/dygraph/paddlesegAnything/vit_t/model.pdparams",
同上

2023-07-04 01:41 UTC, shiyutang commented on contrib/SegmentAnything/segment_anything/modeling/tiny_vit_sam.py
> +        )
需要验证和mobilesam的前向对齐。

2023-07-05 13:10 UTC, Asthestarsfalll commented on contrib/SegmentAnything/scripts/amg_paddle.py
> +    help="The type of model to load, in ['vit_h', 'vit_l', 'vit_b', 'vit_l']", )
fixed

2023-07-10 03:37 UTC, shiyutang commented
如果修改好可以re-request review。

2023-07-28 11:39 UTC, shiyutang requested changes
代码验证完成，需要修改一些code style，并替换vit-t为下面的模型链接：https://paddleseg.bj.bcebos.com/dygraph/paddlesegAnything/vit_t/model.pdparam

2023-07-28 11:39 UTC, shiyutang commented on contrib/SegmentAnything/scripts/amg_paddle.py
> +    "https://bj.bcebos.com/paddleseg/dygraph/paddlesegAnything/vit_t/model.pdparams",
https://paddleseg.bj.bcebos.com/dygraph/paddlesegAnything/vit_t/model.pdparam

2023-07-30 12:45 UTC, shiyutang approved these changes, later dismissed
有一些小改动，其他没有问题

2023-07-30 12:45 UTC, shiyutang commented on contrib/SegmentAnything/segment_anything/modeling/tiny_vit_sam.py
> +        #         nn.init.constant_(m.weight, 1.0)
删除不必要的注释

2023-07-30 12:45 UTC, shiyutang commented on contrib/SegmentAnything/segment_anything/modeling/tiny_vit_sam.py
>                  assert hasattr(p, "lr_scale"), p.param_name
这个函数没有用到是否应该删除？

2023-07-31 13:24 UTC, shiyutang commented
<img width="246" alt="image" src="https://github.com/PaddlePaddle/PaddleSeg/assets/34859558/e2ed5b1d-128f-4ed5-9099-ebd4122ce6cd">

pre-commit版本：3.31

2023-07-31 13:44 UTC, shiyutang approved these changes
LGTM

2023-07-31 13:45 UTC, merged