[Bug] Fix image read error
PaddlePaddle/PaddleSeg pull request #3377
Opened 2023-07-13 09:12 UTC by Asthestarsfalll

### PR types

Bug fixes
### PR changes

Others
### Description

fix #3376

2023-07-13 10:01 UTC, shiyutang requested changes
有逻辑需要修改。

2023-07-13 10:01 UTC, shiyutang commented on paddleseg/transforms/transforms.py
> +            data['img'] = img.astype('float32')
这个修改会导致一个不兼容问题，目前eg1800和supervisely在调用compose时传入的是传入image，而不是string，因此这样修改会导致漏掉对image的判None操作，建议：
1. 同步修改eg1800和supervisely传入path而不是image。
2. 加入assert指令保证img为string类型。
3. 删除if isinstance(data['img'], str)

从而所有传入的都是sting，并在加载string后进行判断是否None，不为None则astype。

2023-07-13 12:08 UTC, Asthestarsfalll commented on paddleseg/transforms/transforms.py
> +            data['img'] = img.astype('float32')
eg1800和supervisely的逻辑似乎不太方便修改为只传入string，因此多加了一个判断

2023-07-13 12:13 UTC, shiyutang submitted a review, later dismissed
LGTM

2023-07-17 02:20 UTC, shiyutang approved these changes
LGTM

2023-07-17 02:21 UTC, merged