[Fix]: auc_roc in predict
PaddlePaddle/PaddleSeg pull request #3446
Opened 2023-08-10 07:04 UTC by Asthestarsfalll

### PR types

Bug fixes

### PR changes

Others

### Description

fix #3415

2023-08-10 09:23 UTC, shiyutang requested changes
建议统一在config配置中修改

2023-08-10 09:23 UTC, shiyutang commented on tools/predict.py
> +
建议不要在主体代码中修改，可以在predict.py中的merge_test_config修改。例如下面代码加入对应函数～
```
  if 'auc_roc' in test_config:
      test_config.pop('auc_roc')
```

2023-08-10 09:44 UTC, Asthestarsfalll commented on tools/predict.py
> +
已修改

2023-08-14 02:58 UTC, shiyutang approved these changes
LGTM

2023-08-14 02:59 UTC, merged