【Hackathon 5th No.68】轻量语义分割网络PIDNet
PaddlePaddle/PaddleSeg pull request #3548
Opened 2023-10-29 03:27 UTC by flytocc

### PR types

New features

### PR changes

Task https://github.com/PaddlePaddle/Paddle/issues/57262
RPC https://github.com/PaddlePaddle/community/pull/722

### Description

1. 添加了`PIDNet`网络
2. 新增了一种edge生成方法 `AddEdgeLabel` transform
3. 修复了 `CrossEntropyLoss` 的一个bug
4. 为`OhemCrossEntropyLoss`增加了对 weight 的支持

#### used [AI Studio](https://aistudio.baidu.com/) for training. Thanks a lot!

2023-10-30 02:49 UTC, shiyutang requested changes
感谢贡献，1. 有一些细节问题，同时2. 需要在configs目录下补充readme；另外3. 辛苦确认训练参数、transform等配置，如果确认，我们在我们这边进行训练。（4. 训练之前可以提供下backbone的预训练权重。）

2023-10-30 02:49 UTC, shiyutang commented on configs/pidnet/pidnet_s_cityscapes_1024x1024_120k.yml
> +    #   hue_range: 18
不需要的数据增强（注释）可以删除。

2023-10-30 02:49 UTC, shiyutang commented on configs/pidnet/pidnet_s_cityscapes_1024x1024_120k.yml
> +                 1.0865, 1.0955, 1.0865, 1.1529, 1.0507]
这个weight是怎么计算的呢，还是参照的论文？可以在readme中给出权重计算的方式。

2023-10-30 02:49 UTC, shiyutang commented on paddleseg/models/backbones/pidnet.py
> +from ..ddrnet import BasicBlock, Bottleneck
建议不要通过这样的相对路径增加，建议直接从layerlib中导入。如果layerlib中没有可以添加，我记得应该有。

2023-10-30 02:49 UTC, shiyutang commented on paddleseg/models/backbones/pidnet.py
> +    "PIDNet_Small"
可以把PIDNet-S | PIDNet-M | PIDNet-L的代码结构和配置文件都补充上。

2023-10-30 02:49 UTC, shiyutang commented on paddleseg/models/losses/cross_entropy_loss.py
> +        if self.avg_non_ignore and self.weight is not None:
感觉加在这里逻辑不对？ 无论是否有avg_non_ignore都会存在mask，因此这里的条件应该只和weight有关。

看上去应该是无论是否有weight，都不使用weight加入到损失的归一化计算中，为什么需要这样呢？

2023-10-30 02:49 UTC, shiyutang commented on paddleseg/models/losses/ohem_cross_entropy_loss.py
>          label = label.reshape((n, 1, h, w))
可以对weight在forward函数中添加一个类似的判断
```
        if self.weight is not None and logit.shape[channel_axis] != len(
                self.weight):
            raise ValueError(
                'The number of weights = {} must be the same as the number of classes = {}.'
                .format(len(self.weight), logit.shape[channel_axis]))
```

2023-10-30 02:49 UTC, shiyutang commented on paddleseg/transforms/transforms.py
> +        self.func = self.pidnet_method if method == 'pidnet' else self.mmseg_method
这里是否有提供两种方法的必要呢？

2023-10-30 11:56 UTC, flytocc commented on paddleseg/transforms/transforms.py
> +        self.func = self.pidnet_method if method == 'pidnet' else self.mmseg_method
已删除未使用的方法

2023-10-30 11:56 UTC, flytocc commented on paddleseg/models/losses/ohem_cross_entropy_loss.py
>          label = label.reshape((n, 1, h, w))
已增加对weight长度的判断

2023-10-30 11:57 UTC, flytocc commented on configs/pidnet/pidnet_s_cityscapes_1024x1024_120k.yml
> +                 1.0865, 1.0955, 1.0865, 1.1529, 1.0507]
参照论文和官方的代码，已在yml中备注说明

2023-10-30 11:59 UTC, flytocc commented on configs/pidnet/pidnet_s_cityscapes_1024x1024_120k.yml
> +    #   hue_range: 18
已删除未使用的数据增强

2023-10-30 12:17 UTC, flytocc commented on paddleseg/models/backbones/pidnet.py
> +from ..ddrnet import BasicBlock, Bottleneck
在pidnet.py中添加BasicBlock和Bottleneck

2023-10-30 12:29 UTC, flytocc commented on paddleseg/models/losses/cross_entropy_loss.py
> +        if self.avg_non_ignore and self.weight is not None:
当`avg_non_ignore==False`时，avg factor (mask * coef)应该是一个ones tensor，所以我觉得原来的逻辑有问题。
当`avg_non_ignore==True`时，avg factor (mask * coef)中ignore label应该为0，并且应该考虑weight的影响，只有这样，计算结果才能和F.cross_entropy(..., reduction='mean')相同。

2023-10-30 12:45 UTC, flytocc commented on paddleseg/models/backbones/pidnet.py
> +    "PIDNet_Small"
已添加

2023-10-30 14:26 UTC, flytocc commented
这里是imagenet_pretrained weights和2xb6-120k_1024x1024-cityscapes weights

[百度网盘](https://pan.baidu.com/s/15HZ46FAJCNes8sxUDj36lQ?pwd=gvg9)

2023-11-01 08:29 UTC, shiyutang commented
> 这里是imagenet_pretrained weights和2xb6-120k_1024x1024-cityscapes weights
> 
> [百度网盘](https://pan.baidu.com/s/15HZ46FAJCNes8sxUDj36lQ?pwd=gvg9)

![image](https://github.com/PaddlePaddle/PaddleSeg/assets/34859558/73e53bb9-cf75-4ed4-9800-20ec8cacb4f0)

2023-11-01 08:32 UTC, flytocc commented
> > 这里是imagenet_pretrained weights和2xb6-120k_1024x1024-cityscapes weights
> > [百度网盘](https://pan.baidu.com/s/15HZ46FAJCNes8sxUDj36lQ?pwd=gvg9)
> 
> ![image](https://user-images.githubusercontent.com/34859558/279618318-73e53bb9-cf75-4ed4-9800-20ec8cacb4f0.png)

现在应该有了

2023-11-01 08:51 UTC, shiyutang reviewed
模型权重有点问题，你重新给我提交下吧，我把链接给你～

2023-11-01 08:51 UTC, shiyutang commented on paddleseg/transforms/transforms.py
> +        data['edge'] = edge
这个比mask_to_binary_edge快，因为是没有使用到onehot的步骤。
但是这样获得的edge是每个类别的edge么，因为lable是0-18？

2023-11-01 08:51 UTC, shiyutang commented on paddleseg/models/losses/cross_entropy_loss.py
> +        if self.avg_non_ignore and self.weight is not None:
嗯嗯，好的，我理解了～

2023-11-01 09:05 UTC, flytocc commented
> 模型权重有点问题，你重新给我提交下吧，我把链接给你～

什么问题

2023-11-01 09:10 UTC, flytocc commented on paddleseg/transforms/transforms.py
> +        data['edge'] = edge
mask_to_binary_edge先生成onehot，再从onehot生成edge，但是最后又把全部类别的edge和在一起了，那似乎生成onehot就没有必要了。

2023-11-01 11:14 UTC, shiyutang commented
> > 模型权重有点问题，你重新给我提交下吧，我把链接给你～
> 
> 什么问题

没事，我先验证下。

2023-11-01 16:01 UTC, flytocc commented
我使用2张V100进行了一次训练，`mIoU`为`78.34%`，官方权重的`mIoU`为`78.74%`，误差大约`0.4%`

当前的实现和官方有如下区别：

1. label不同：PaddleSeg使用`*_labelTrainIds.png`，PIDNet使用`*_labelIds.png`，二者有细微区别
2. 数据增强padding_value不同： PaddleSeg填充`127.5`，PIDNet填充`0`
3. 数据增强img resize不同： PaddleSeg中img为`float32`，PIDNet中img为`uint8`。这个差异较小，应该不影响训练
4. BatchNorm不同：PaddleSeg使用`SyncBatchNorm`，PIDNet使用的是普通的`BatchNorm2d`

另外，我也尝试了使用RandomDistort增强，基本没有提升(`78.35`)。

如果，你要进行训练，可以把padding_value设置为`0`：

```
train_dataset:
  transforms:
    - type: AddEdgeLabel
    - type: ResizeStepScaling
      min_scale_factor: 0.5
      max_scale_factor: 2.1
      scale_step_size: 0.1
    - type: RandomPaddingCrop
      crop_size: [1024, 1024]
      im_padding_value: 0   # <---------- here
    - type: RandomHorizontalFlip
    - type: Normalize
      mean: *mean
      std: *std
```

2023-11-02 02:52 UTC, shiyutang commented
好，我在paddle=0，四卡基础上训练下，你那边能否看看标签的影响呢？

2023-11-02 04:02 UTC, shiyutang commented
https://paddleseg.bj.bcebos.com/dygraph/pidnet/pidnet_small_2xb6-120k_1024x1024-cityscapes.pdparams
https://paddleseg.bj.bcebos.com/dygraph/pidnet/pidnet_small_imagenet1k.pdparams
https://paddleseg.bj.bcebos.com/dygraph/pidnet/pidnet_medium_2xb6-120k_1024x1024-cityscapes.pdparams
https://paddleseg.bj.bcebos.com/dygraph/pidnet/pidnet_medium_imagenet1k.pdparams
https://paddleseg.bj.bcebos.com/dygraph/pidnet/pidnet_large_2xb6-120k_1024x1024-cityscapes.pdparams
https://paddleseg.bj.bcebos.com/dygraph/pidnet/pidnet_large_imagenet1k.pdparams

2023-11-02 07:42 UTC, flytocc commented
> 好，我在paddle=0上训练下。你那边能否看看标签的影响呢？另外我看标签不应该是影响，labelID是完整的33类数据，但是PID源码是19类的模型，辛苦看看如果没有转换，那模型和数据的类别是怎么匹配上的

需要把33类的`*_labelIds.png`转换成19类。

https://github.com/mcordts/cityscapesScripts/blob/a7ac7b4062d1a80ed5e22d2ea2179c886801c77d/cityscapesscripts/helpers/labels.py#L62-L99

参考PIDNet的实现：
``` python
def convert_label(label: np.ndarray, ignore_label: int = 255) -> np.ndarray:
    label_mapping = {-1: ignore_label, 0: ignore_label, 
                     1: ignore_label, 2: ignore_label, 
                     3: ignore_label, 4: ignore_label, 
                     5: ignore_label, 6: ignore_label, 
                     7: 0, 8: 1, 9: ignore_label, 
                     10: ignore_label, 11: 2, 12: 3, 
                     13: 4, 14: ignore_label, 15: ignore_label, 
                     16: ignore_label, 17: 5, 18: ignore_label, 
                     19: 6, 20: 7, 21: 8, 22: 9, 23: 10, 24: 11,
                     25: 12, 26: 13, 27: 14, 28: 15, 
                     29: ignore_label, 30: ignore_label, 
                     31: 16, 32: 17, 33: 18}

    temp = label.copy()
    for v, k in label_mapping.items():
        temp[label == k] = v
    return temp
```

`*_labelIds.png`是数据集自带的，我不太清楚它具体是怎样生成的，换成成19类后，和`*_labelTrainIds.png`有细微的差别。

> 如果可以匹配也可以用labelID训练下，探究下这方面的影响。https://www.cnblogs.com/dotman/p/cityscapes_dataset_tips.html ![image](https://user-images.githubusercontent.com/34859558/279861545-3803eb4f-8fb3-4a3e-afa5-52dc07496ee2.png)

我正在用转换后的`*_labelIds.png`进行训练。

2023-11-02 07:47 UTC, flytocc commented
> 模型链接如下，另外你可以发下你的训练日志给我么？

 https://pan.baidu.com/s/15HZ46FAJCNes8sxUDj36lQ?pwd=gvg9

2023-11-03 02:44 UTC, shiyutang commented
替换padding=0后训练：
![image](https://github.com/PaddlePaddle/PaddleSeg/assets/34859558/dff68e10-e4c9-476d-a821-20cabf5b8a88)

2023-11-03 06:05 UTC, flytocc commented
> 替换padding=0后训练，精度还是有些差距。我在padding ！=0重新训练一下。 ![image](https://user-images.githubusercontent.com/34859558/280174384-dff68e10-e4c9-476d-a821-20cabf5b8a88.png)

`77.74%`确实有点低啊，`padding=127.5`我一共跑了三次，分别是`78.32`,`78.34`,`78.35`。

2023-11-06 06:14 UTC, shiyutang commented
使用pad=128重新训练了一下，精度差距缩小。
<img width="870" alt="image" src="https://github.com/PaddlePaddle/PaddleSeg/assets/34859558/dc8b091b-4d79-4e00-89f7-6b16004fcf85">

2023-11-06 06:18 UTC, shiyutang reviewed
精度结果基本满足预期，完成下列修改可合入：
1. 对small模型的模型参数和日志都加上吧（
vdl：https://paddlepaddle.org.cn/paddle/visualdl/service/app?id=57dda9c34cd06a4b2996118df03583c9
model：
log：
），可行的话也加上medium和large的。
3. 同时加一下tipc：https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.8/test_tipc/docs/test_train_inference_python.md#22-%E5%8A%9F%E8%83%BD%E6%B5%8B%E8%AF%95 lite_tran_lite_infer模式即可，用于加入CI测试。

2023-11-06 06:18 UTC, shiyutang commented on configs/pidnet/README.md
> +|PIDNet|PIDNet-Large |1024x1024|120000|80.89%|82.37%| |
这几个模型对应的参数和日志都加上吧。

2023-11-06 06:18 UTC, shiyutang commented on configs/pidnet/pidnet_large_cityscapes_1024x1024_120k.yml
> +  pretrained: pidnet_large_imagenet1k.pdparams  # TODO
三个yml中模型的链接也替换一下。

2023-11-06 06:41 UTC, shiyutang commented on paddleseg/models/losses/ohem_cross_entropy_loss.py
> +            axis=1)
这里的修改和之前具有等效性么？ 缺少了一个softmax的操作。

2023-11-06 08:03 UTC, flytocc commented on configs/pidnet/pidnet_large_cityscapes_1024x1024_120k.yml
> +  pretrained: pidnet_large_imagenet1k.pdparams  # TODO
好的

2023-11-06 08:03 UTC, flytocc commented on configs/pidnet/README.md
> +|PIDNet|PIDNet-Large |1024x1024|120000|80.89%|82.37%| |
small的model放官方的权重还是你训练的权重？

2023-11-06 08:09 UTC, flytocc commented on paddleseg/models/losses/ohem_cross_entropy_loss.py
> +            axis=1)
等效！它们内部都是调用的`_C_ops.cross_entropy_with_softmax`，参数也都相同，结果也相同。

2023-11-06 09:50 UTC, flytocc commented
tipc有点问题

在paddle2.5.1版本下，export.py会报错：

```python
Traceback (most recent call last):
  File "/home/flytocc/workspaces/PaddleSeg/tools/export.py", line 121, in <module>
    main(args)
  File "/home/flytocc/workspaces/PaddleSeg/tools/export.py", line 89, in main
    paddle.jit.save(model, os.path.join(args.save_dir, save_name))
  File "/home/flytocc/anaconda3/envs/pd25/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/flytocc/anaconda3/envs/pd25/lib/python3.10/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/flytocc/anaconda3/envs/pd25/lib/python3.10/site-packages/paddle/jit/api.py", line 752, in wrapper
    func(layer, path, input_spec, **configs)
  File "/home/flytocc/anaconda3/envs/pd25/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/flytocc/anaconda3/envs/pd25/lib/python3.10/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/flytocc/anaconda3/envs/pd25/lib/python3.10/site-packages/paddle/fluid/dygraph/base.py", line 75, in __impl__
    return func(*args, **kwargs)
  File "/home/flytocc/anaconda3/envs/pd25/lib/python3.10/site-packages/paddle/jit/api.py", line 1043, in save
    static_func.concrete_program_specify_input_spec(
  File "/home/flytocc/anaconda3/envs/pd25/lib/python3.10/site-packages/paddle/jit/dy2static/program_translator.py", line 709, in concrete_program_specify_input_spec
    concrete_program, _ = self.get_concrete_program(
  File "/home/flytocc/anaconda3/envs/pd25/lib/python3.10/site-packages/paddle/jit/dy2static/program_translator.py", line 589, in get_concrete_program
    concrete_program, partial_program_layer = self._program_cache[
  File "/home/flytocc/anaconda3/envs/pd25/lib/python3.10/site-packages/paddle/jit/dy2static/program_translator.py", line 1249, in __getitem__
    self._caches[item_id] = self._build_once(item)
  File "/home/flytocc/anaconda3/envs/pd25/lib/python3.10/site-packages/paddle/jit/dy2static/program_translator.py", line 1193, in _build_once
    concrete_program = ConcreteProgram.from_func_spec(
  File "/home/flytocc/anaconda3/envs/pd25/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/flytocc/anaconda3/envs/pd25/lib/python3.10/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/flytocc/anaconda3/envs/pd25/lib/python3.10/site-packages/paddle/fluid/dygraph/base.py", line 75, in __impl__
    return func(*args, **kwargs)
  File "/home/flytocc/anaconda3/envs/pd25/lib/python3.10/site-packages/paddle/jit/dy2static/program_translator.py", line 1070, in from_func_spec
    error_data.raise_new_exception()
  File "/home/flytocc/anaconda3/envs/pd25/lib/python3.10/site-packages/paddle/jit/dy2static/error.py", line 452, in raise_new_exception
    raise new_exception from None
ValueError: In transformed code:

    File "/home/flytocc/workspaces/PaddleSeg/paddleseg/deploy/export.py", line 26, in forward
        outs = self.model(x)
    File "/home/flytocc/workspaces/PaddleSeg/paddleseg/models/pidnet.py", line 69, in forward
        feat = self.backbone(x)
    File "/home/flytocc/workspaces/PaddleSeg/paddleseg/models/backbones/pidnet.py", line 681, in forward
        # stage 0-2
        x = self.stem(x)
        ~~~~~~~~~~~~~~~~ <--- HERE

        # stage 3

    File "/home/flytocc/anaconda3/envs/pd25/lib/python3.10/site-packages/paddle/jit/dy2static/convert_call_func.py", line 222, in convert_call
        if is_builtin(func) or is_unsupported(func):
    File "/home/flytocc/anaconda3/envs/pd25/lib/python3.10/site-packages/paddle/jit/dy2static/convert_call_func.py", line 122, in is_unsupported
        func_in_dict = func == v

    ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (6,) + inhomogeneous part.
```

在paddle2.5.2版本下，export.py没报错，但infer.py会报错：

```python
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/lib/python3.8/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
  File "/usr/lib/python3.8/multiprocessing/synchronize.py", line 110, in __setstate__
    self._semlock = _multiprocessing.SemLock._rebuild(*state)
FileNotFoundError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "deploy/python/infer.py", line 396, in <module>
    main(args)
  File "deploy/python/infer.py", line 384, in main
    predictor.run(imgs_list)
  File "deploy/python/infer.py", line 219, in run
    self.predictor.run()
ValueError: (InvalidArgument) Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [1, 32, 128, 256] and the shape of Y = [1, 32, 128, 128]. Received [256] in X is not equal to [128] in Y at i:3.
  [Hint: Expected x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1 == true, but received x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1:0 != true:1.] (at ../paddle/phi/kernels/funcs/common_shape.h:86)
  [operator < elementwise_mul > error]
```

2023-11-06 10:10 UTC, flytocc commented
> 如果可以匹配也可以用labelID训练下，探究下这方面的影响。

我训练完成了，mIoU `78.40%`，比`labelTrainIds`高`0.05%`，基本没什么影响

2023-11-07 02:17 UTC, shiyutang requested changes
导出和推理在paddle develop上重新尝试下？ 看上去是形状不匹配，应该是动转静过程中的问题。

另外readme需要补充下。

2023-11-07 02:17 UTC, shiyutang commented on configs/pidnet/README.md
> +|PIDNet|PIDNet-Large |1024x1024|120000|80.89%|82.37%|[model](https://paddleseg.bj.bcebos.com/dygraph/pidnet/pidnet_large_2xb6-120k_1024x1024-cityscapes.pdparams)|
这两个都是转换的模型而非训练模型，最好做一下区分。

2023-11-07 02:17 UTC, shiyutang commented on configs/pidnet/README.md
> +|PIDNet|PIDNet-Small |1024x1024|120000|78.74%|80.87%|[model](https://paddleseg.bj.bcebos.com/dygraph/pidnet/pidnet_small_cityscapes_1024x1024_120k/model.pdparams) \| [log](https://paddleseg.bj.bcebos
这个表格中的精度需要修改，即填写现有模型做评估，和ms+flip的评估后的精度。

2023-11-07 02:17 UTC, shiyutang commented on configs/pidnet/pidnet_small_cityscapes_1024x1024_120k.yml
> +weight: &weight [0.8373, 0.9180, 0.8660, 1.0345, 1.0166, 0.9969, 0.9754,
这一点建议在readme中注明，对于不同数据需要重新计算权重，不然不是最优效果～

2023-11-07 02:17 UTC, shiyutang commented on configs/pidnet/README.md
> +|PIDNet|PIDNet-Large |1024x1024|120000|80.89%|82.37%| |
都应该是训练的权重

2023-11-07 02:18 UTC, shiyutang commented
> paddle2.5.1版本下，export.py没报错

这两个都是2.5.1？

2023-11-07 06:50 UTC, flytocc commented on configs/pidnet/README.md
> +|PIDNet|PIDNet-Large |1024x1024|120000|80.89%|82.37%|[model](https://paddleseg.bj.bcebos.com/dygraph/pidnet/pidnet_large_2xb6-120k_1024x1024-cityscapes.pdparams)|
m和l的模型都没训练，我先空着？

2023-11-07 06:51 UTC, flytocc commented on configs/pidnet/pidnet_small_cityscapes_1024x1024_120k.yml
> +weight: &weight [0.8373, 0.9180, 0.8660, 1.0345, 1.0166, 0.9969, 0.9754,
好的

2023-11-07 06:52 UTC, flytocc commented
> > paddle2.5.1版本下，export.py没报错
> 
> 这两个都是2.5.1？

写错了，2.5.1版本下export.py报错，2.5.2版本下infer.py报错，稍后我试试develop

2023-11-07 12:53 UTC, flytocc commented on configs/pidnet/README.md
> +|PIDNet|PIDNet-Small |1024x1024|120000|78.74%|80.87%|[model](https://paddleseg.bj.bcebos.com/dygraph/pidnet/pidnet_small_cityscapes_1024x1024_120k/model.pdparams) \| [log](https://paddleseg.bj.bcebos
好的

2023-11-08 05:14 UTC, shiyutang commented on configs/pidnet/README.md
> +|PIDNet|PIDNet-Large |1024x1024|120000|80.89%|82.37%|[model](https://paddleseg.bj.bcebos.com/dygraph/pidnet/pidnet_large_2xb6-120k_1024x1024-cityscapes.pdparams)|
嗯嗯，可以训练下加入。

2023-11-08 05:15 UTC, shiyutang approved these changes
LGTM

2023-11-08 05:15 UTC, merged

2024-04-25 17:57 UTC, pobi123 commented
我在使用paddleseg训练的时候，选用的是pp_liteseg_stdc1_camvid_960x720_10k。训练发生报错：
ValueError: (InvalidArgument) Broadcast dimension mismatch.
 Operands could not be broadcast together with the shape of X = [20, 4147200] and the shape of Y = [12441600]. 
Received [4147200] in X is not equal to [12441600] in Y at i:1.
请问是什么原因？

2024-04-26 05:20 UTC, flytocc commented
@pobi123  这是PIDNet的pr，pp_liteseg有什么问题建议直接提issue

> 我在使用paddleseg训练的时候，选用的是pp_liteseg_stdc1_camvid_960x720_10k。训练发生报错： ValueError: (InvalidArgument) Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [20, 4147200] and the shape of Y = [12441600]. Received [4147200] in X is not equal to [12441600] in Y at i:1. 请问是什么原因？

2024-06-16 06:59 UTC, Yana990 commented
500/500 [==============================] - 54s 107ms/step - batch_cost: 0.1071 - reader cost: 0.0861
Traceback (most recent call last):
  File "train.py", line 230, in &lt;module&gt;
    main(args)
  File "train.py", line 206, in main
    train(
  File "/home/PaddleSeg-release-2.5/paddleseg/core/train.py", line 285, in train
    mean_iou, acc, _, _, _ = evaluate(
  File "/home/PaddleSeg-release-2.5/paddleseg/core/val.py", line 223, in evaluate
    acc, class_precision, class_recall = metrics.class_measurement(
  File "/home/PaddleSeg-release-2.5/paddleseg/utils/metrics.py", line 226, in class_measurement
    return mean_acc, np.array(class_precision), np.array(class_recall)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (19,) + inhomogeneous part.

请问以上的报错怎么解决呢？