Add UNet3+ model
PaddlePaddle/PaddleSeg pull request #851
Opened 2021-03-01 03:04 UTC by geoyee

参考github-pytorch代码（https://github.com/ZJUGiveLab/UNet-Version），经过测试（修改bisenet_optic_disc_512x512_1k.yml中的model的type），可以train的起来

2021-03-01 03:04 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/PaddleSeg?pullRequest=851) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/PaddleSeg?pullRequest=851) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: nepeplwu<br/>:x: geoyee<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/PaddleSeg?pullRequest=851) it.</sub>

2021-03-01 04:05 UTC, michaelowenliu requested changes
提了一些review意见

2021-03-01 04:05 UTC, michaelowenliu commented on paddleseg/models/unet_3plus.py
> +class UNet_3Plus(nn.Layer):
类命名 首字母大写，无其他符号

2021-03-01 04:05 UTC, michaelowenliu commented on paddleseg/models/unet_3plus.py
> +        in_channels (int): The channel number of input image.  Default: 3.
注释规范，如果有默认值，则应该写（int, optional）

2021-03-01 04:05 UTC, michaelowenliu commented on paddleseg/models/unet_3plus.py
> +        ## -------------Encoder--------------
组网方式的可读性不高，拆解成组件化，Encoder和Decoder

2021-03-01 04:05 UTC, michaelowenliu commented on paddleseg/models/layers/layer_libs.py
> +class unetConv2(nn.Layer):
不在内置库里面添加新方式，放在自定义模型文件里，class命名方式参考下面review意见。

2021-03-01 04:05 UTC, michaelowenliu commented on paddleseg/models/unet_3plus.py
> +class UNet_3Plus_DeepSup(nn.Layer):
同样存在命名规范问题

2021-03-01 04:05 UTC, michaelowenliu commented on paddleseg/models/unet_3plus.py
> +        in_channels (int): The channel number of input image.  Default: 3.
注释规范问题

2021-03-01 04:05 UTC, michaelowenliu commented on paddleseg/models/unet_3plus.py
> +        ## -------------Encoder--------------
组网可读性问题

2021-03-01 04:37 UTC, geoyee commented
收到，非常感谢回复和指导，这是我第一次在开源项目中提交PR，下面我将在我的空闲时间中根据建议继续完善！


On 3/1/2021 12:05，Liu Yi<notifications@github.com> wrote：

@michaelowenliu requested changes on this pull request.

提了一些review意见

In paddleseg/models/unet_3plus.py:

> +# distributed under the License is distributed on an "AS IS" BASIS,

+# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.

+# See the License for the specific language governing permissions and

+# limitations under the License.

+

+import paddle

+import paddle.nn as nn

+import paddle.nn.functional as F

+

+from paddleseg.cvlibs import manager

+from paddleseg.models.layers.layer_libs import unetConv2, SyncBatchNorm

+from paddleseg.cvlibs.param_init import kaiming_normal_init

+

+

+@manager.MODELS.add_component

+class UNet_3Plus(nn.Layer):



类命名 首字母大写，无其他符号

In paddleseg/models/unet_3plus.py:

> +from paddleseg.cvlibs import manager

+from paddleseg.models.layers.layer_libs import unetConv2, SyncBatchNorm

+from paddleseg.cvlibs.param_init import kaiming_normal_init

+

+

+@manager.MODELS.add_component

+class UNet_3Plus(nn.Layer):

+    """

+    The UNet3+ implementation based on PaddlePaddle.

+

+    The original article refers to

+    Huang H , Lin L , Tong R , et al. UNet 3+: A Full-Scale Connected UNet for Medical Image Segmentation[J]. arXiv, 2020.

+    (https://arxiv.org/ftp/arxiv/papers/2004/2004.08790.pdf).

+

+    Args:

+        in_channels (int): The channel number of input image.  Default: 3.



注释规范，如果有默认值，则应该写（int, optional）

In paddleseg/models/unet_3plus.py:

> +        num_classes (int): The unique number of target classes.  Default: 2.

+        feature_scale (int): The feature map scale.  Default: 4.

+        is_deconv (bool): A bool value indicates whether using deconvolution in upsampling.

+            If False, use resize_bilinear. Default: True.

+        is_batchnorm (bool): use batchnorm after conv or not.  Default: True.

+        end_sigmoid (bool): use sigmoid for results or not. Default: False.

+    """

+    def __init__(self, in_channels=3, num_classes=2, feature_scale=4, is_deconv=True, is_batchnorm=True, end_sigmoid=False):

+        super(UNet_3Plus, self).__init__()

+        self.is_deconv = is_deconv

+        self.in_channels = in_channels

+        self.is_batchnorm = is_batchnorm

+        self.feature_scale = feature_scale

+        self.end_sigmoid = end_sigmoid

+        filters = [64, 128, 256, 512, 1024]

+        ## -------------Encoder--------------



组网方式的可读性不高，拆解成组件化，Encoder和Decoder

In paddleseg/models/layers/layer_libs.py:

> @@ -165,3 +165,37 @@ def forward(self, x):

         x = self.dropout(x)

         x = self.conv(x)

         return x

+

+

+class unetConv2(nn.Layer):



不在内置库里面添加新方式，放在自定义模型文件里，class命名方式参考下面review意见。

In paddleseg/models/unet_3plus.py:

> +        hd2_UT_hd1 = self.hd2_UT_hd1_relu(self.hd2_UT_hd1_bn(self.hd2_UT_hd1_conv(self.hd2_UT_hd1(hd2))))

+        hd3_UT_hd1 = self.hd3_UT_hd1_relu(self.hd3_UT_hd1_bn(self.hd3_UT_hd1_conv(self.hd3_UT_hd1(hd3))))

+        hd4_UT_hd1 = self.hd4_UT_hd1_relu(self.hd4_UT_hd1_bn(self.hd4_UT_hd1_conv(self.hd4_UT_hd1(hd4))))

+        hd5_UT_hd1 = self.hd5_UT_hd1_relu(self.hd5_UT_hd1_bn(self.hd5_UT_hd1_conv(self.hd5_UT_hd1(hd5))))

+        hd1 = self.relu1d_1(self.bn1d_1(self.conv1d_1(

+            paddle.concat([h1_Cat_hd1, hd2_UT_hd1, hd3_UT_hd1, hd4_UT_hd1, hd5_UT_hd1], 1)))) # hd1->320*320*UpChannels

+        d1 = self.outconv1(hd1)  # d1->320*320*num_classes

+        if self.end_sigmoid:

+            out = [F.sigmoid(d1)]

+        else:

+            out = [d1]

+        return out

+

+

+@manager.MODELS.add_component

+class UNet_3Plus_DeepSup(nn.Layer):



同样存在命名规范问题

In paddleseg/models/unet_3plus.py:

> +        else:

+            out = [d1]

+        return out

+

+

+@manager.MODELS.add_component

+class UNet_3Plus_DeepSup(nn.Layer):

+    """

+    The UNet3+ with deep supervision implementation based on PaddlePaddle.

+

+    The original article refers to

+    Huang H , Lin L , Tong R , et al. UNet 3+: A Full-Scale Connected UNet for Medical Image Segmentation[J]. arXiv, 2020.

+    (https://arxiv.org/ftp/arxiv/papers/2004/2004.08790.pdf).

+

+    Args:

+        in_channels (int): The channel number of input image.  Default: 3.



注释规范问题

In paddleseg/models/unet_3plus.py:

> +        num_classes (int): The unique number of target classes.  Default: 2.

+        feature_scale (int): The feature map scale.  Default: 4.

+        is_deconv (bool): A bool value indicates whether using deconvolution in upsampling.

+            If False, use resize_bilinear. Default: True.

+        is_batchnorm (bool): use batchnorm after conv or not.  Default: True.

+        end_sigmoid (bool): use sigmoid for results or not. Default: False.

+    """

+    def __init__(self, in_channels=3, num_classes=2, feature_scale=4, is_deconv=True, is_batchnorm=True, end_sigmoid=False):

+        super(UNet_3Plus_DeepSup, self).__init__()

+        self.is_deconv = is_deconv

+        self.in_channels = in_channels

+        self.is_batchnorm = is_batchnorm

+        self.feature_scale = feature_scale

+        self.end_sigmoid = end_sigmoid

+        filters = [64, 128, 256, 512, 1024]

+        ## -------------Encoder--------------



组网可读性问题

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

2021-03-01 12:10 UTC, haoyuying commented
> 收到，非常感谢回复和指导，这是我第一次在开源项目中提交PR，下面我将在我的空闲时间中根据建议继续完善！ On 3/1/2021 12:05，Liu Yi<notifications@github.com> wrote： @michaelowenliu requested changes on this pull request. 提了一些review意见 In paddleseg/models/unet_3plus.py:
> +# distributed under the License is distributed on an "AS IS" BASIS,
> +# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. +# See the License for the specific language governing permissions and +# limitations under the License. + +import paddle +import paddle.nn as nn +import paddle.nn.functional as F + +from paddleseg.cvlibs import manager +from paddleseg.models.layers.layer_libs import unetConv2, SyncBatchNorm +from paddleseg.cvlibs.param_init import kaiming_normal_init + + +@manager.MODELS.add_component +class UNet_3Plus(nn.Layer): 类命名 首字母大写，无其他符号 In paddleseg/models/unet_3plus.py:
> +from paddleseg.cvlibs import manager
> +from paddleseg.models.layers.layer_libs import unetConv2, SyncBatchNorm +from paddleseg.cvlibs.param_init import kaiming_normal_init + + +@manager.MODELS.add_component +class UNet_3Plus(nn.Layer): + """ + The UNet3+ implementation based on PaddlePaddle. + + The original article refers to + Huang H , Lin L , Tong R , et al. UNet 3+: A Full-Scale Connected UNet for Medical Image Segmentation[J]. arXiv, 2020. + (https://arxiv.org/ftp/arxiv/papers/2004/2004.08790.pdf). + + Args: + in_channels (int): The channel number of input image. Default: 3. 注释规范，如果有默认值，则应该写（int, optional） In paddleseg/models/unet_3plus.py:
> + num_classes (int): The unique number of target classes. Default: 2.
> + feature_scale (int): The feature map scale. Default: 4. + is_deconv (bool): A bool value indicates whether using deconvolution in upsampling. + If False, use resize_bilinear. Default: True. + is_batchnorm (bool): use batchnorm after conv or not. Default: True. + end_sigmoid (bool): use sigmoid for results or not. Default: False. + """ + def __init__(self, in_channels=3, num_classes=2, feature_scale=4, is_deconv=True, is_batchnorm=True, end_sigmoid=False): + super(UNet_3Plus, self).__init__() + self.is_deconv = is_deconv + self.in_channels = in_channels + self.is_batchnorm = is_batchnorm + self.feature_scale = feature_scale + self.end_sigmoid = end_sigmoid + filters = [64, 128, 256, 512, 1024] + ## -------------Encoder-------------- 组网方式的可读性不高，拆解成组件化，Encoder和Decoder In paddleseg/models/layers/layer_libs.py:
> @@ -165,3 +165,37 @@ def forward(self, x):
> x = self.dropout(x) x = self.conv(x) return x + + +class unetConv2(nn.Layer): 不在内置库里面添加新方式，放在自定义模型文件里，class命名方式参考下面review意见。 In paddleseg/models/unet_3plus.py:
> + hd2_UT_hd1 = self.hd2_UT_hd1_relu(self.hd2_UT_hd1_bn(self.hd2_UT_hd1_conv(self.hd2_UT_hd1(hd2))))
> + hd3_UT_hd1 = self.hd3_UT_hd1_relu(self.hd3_UT_hd1_bn(self.hd3_UT_hd1_conv(self.hd3_UT_hd1(hd3)))) + hd4_UT_hd1 = self.hd4_UT_hd1_relu(self.hd4_UT_hd1_bn(self.hd4_UT_hd1_conv(self.hd4_UT_hd1(hd4)))) + hd5_UT_hd1 = self.hd5_UT_hd1_relu(self.hd5_UT_hd1_bn(self.hd5_UT_hd1_conv(self.hd5_UT_hd1(hd5)))) + hd1 = self.relu1d_1(self.bn1d_1(self.conv1d_1( + paddle.concat([h1_Cat_hd1, hd2_UT_hd1, hd3_UT_hd1, hd4_UT_hd1, hd5_UT_hd1], 1)))) # hd1->320*320*UpChannels + d1 = self.outconv1(hd1) # d1->320*320*num_classes + if self.end_sigmoid: + out = [F.sigmoid(d1)] + else: + out = [d1] + return out + + +@manager.MODELS.add_component +class UNet_3Plus_DeepSup(nn.Layer): 同样存在命名规范问题 In paddleseg/models/unet_3plus.py:
> + else:
> + out = [d1] + return out + + +@manager.MODELS.add_component +class UNet_3Plus_DeepSup(nn.Layer): + """ + The UNet3+ with deep supervision implementation based on PaddlePaddle. + + The original article refers to + Huang H , Lin L , Tong R , et al. UNet 3+: A Full-Scale Connected UNet for Medical Image Segmentation[J]. arXiv, 2020. + (https://arxiv.org/ftp/arxiv/papers/2004/2004.08790.pdf). + + Args: + in_channels (int): The channel number of input image. Default: 3. 注释规范问题 In paddleseg/models/unet_3plus.py:
> + num_classes (int): The unique number of target classes. Default: 2.
> + feature_scale (int): The feature map scale. Default: 4. + is_deconv (bool): A bool value indicates whether using deconvolution in upsampling. + If False, use resize_bilinear. Default: True. + is_batchnorm (bool): use batchnorm after conv or not. Default: True. + end_sigmoid (bool): use sigmoid for results or not. Default: False. + """ + def __init__(self, in_channels=3, num_classes=2, feature_scale=4, is_deconv=True, is_batchnorm=True, end_sigmoid=False): + super(UNet_3Plus_DeepSup, self).__init__() + self.is_deconv = is_deconv + self.in_channels = in_channels + self.is_batchnorm = is_batchnorm + self.feature_scale = feature_scale + self.end_sigmoid = end_sigmoid + filters = [64, 128, 256, 512, 1024] + ## -------------Encoder-------------- 组网可读性问题 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

请问这个模型自己在我们提供的数据集上训练过吗，可以达到多少精度呢？

2021-03-01 12:34 UTC, geoyee commented
没有，我尝试一下使用快速入门中的案例进行测试


On 3/1/2021 20:10，haoyuying<notifications@github.com> wrote：

收到，非常感谢回复和指导，这是我第一次在开源项目中提交PR，下面我将在我的空闲时间中根据建议继续完善！ On 3/1/2021 12:05，Liu Yinotifications@github.com wrote： @michaelowenliu requested changes on this pull request. 提了一些review意见 In paddleseg/models/unet_3plus.py:
+# distributed under the License is distributed on an "AS IS" BASIS,
+# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. +# See the License for the specific language governing permissions and +# limitations under the License. + +import paddle +import paddle.nn as nn +import paddle.nn.functional as F + +from paddleseg.cvlibs import manager +from paddleseg.models.layers.layer_libs import unetConv2, SyncBatchNorm +from paddleseg.cvlibs.param_init import kaiming_normal_init + + +@manager.MODELS.add_component +class UNet_3Plus(nn.Layer): 类命名 首字母大写，无其他符号 In paddleseg/models/unet_3plus.py:
+from paddleseg.cvlibs import manager
+from paddleseg.models.layers.layer_libs import unetConv2, SyncBatchNorm +from paddleseg.cvlibs.param_init import kaiming_normal_init + + +@manager.MODELS.add_component +class UNet_3Plus(nn.Layer): + """ + The UNet3+ implementation based on PaddlePaddle. + + The original article refers to + Huang H , Lin L , Tong R , et al. UNet 3+: A Full-Scale Connected UNet for Medical Image Segmentation[J]. arXiv, 2020. + (https://arxiv.org/ftp/arxiv/papers/2004/2004.08790.pdf). + + Args: + in_channels (int): The channel number of input image. Default: 3. 注释规范，如果有默认值，则应该写（int, optional） In paddleseg/models/unet_3plus.py:

num_classes (int): The unique number of target classes. Default: 2.
feature_scale (int): The feature map scale. Default: 4. + is_deconv (bool): A bool value indicates whether using deconvolution in upsampling. + If False, use resize_bilinear. Default: True. + is_batchnorm (bool): use batchnorm after conv or not. Default: True. + end_sigmoid (bool): use sigmoid for results or not. Default: False. + """ + def init(self, in_channels=3, num_classes=2, feature_scale=4, is_deconv=True, is_batchnorm=True, end_sigmoid=False): + super(UNet_3Plus, self).init() + self.is_deconv = is_deconv + self.in_channels = in_channels + self.is_batchnorm = is_batchnorm + self.feature_scale = feature_scale + self.end_sigmoid = end_sigmoid + filters = [64, 128, 256, 512, 1024] + ## -------------Encoder-------------- 组网方式的可读性不高，拆解成组件化，Encoder和Decoder In paddleseg/models/layers/layer_libs.py:
@@ -165,3 +165,37 @@ def forward(self, x):
x = self.dropout(x) x = self.conv(x) return x + + +class unetConv2(nn.Layer): 不在内置库里面添加新方式，放在自定义模型文件里，class命名方式参考下面review意见。 In paddleseg/models/unet_3plus.py:
hd2_UT_hd1 = self.hd2_UT_hd1_relu(self.hd2_UT_hd1_bn(self.hd2_UT_hd1_conv(self.hd2_UT_hd1(hd2))))
hd3_UT_hd1 = self.hd3_UT_hd1_relu(self.hd3_UT_hd1_bn(self.hd3_UT_hd1_conv(self.hd3_UT_hd1(hd3)))) + hd4_UT_hd1 = self.hd4_UT_hd1_relu(self.hd4_UT_hd1_bn(self.hd4_UT_hd1_conv(self.hd4_UT_hd1(hd4)))) + hd5_UT_hd1 = self.hd5_UT_hd1_relu(self.hd5_UT_hd1_bn(self.hd5_UT_hd1_conv(self.hd5_UT_hd1(hd5)))) + hd1 = self.relu1d_1(self.bn1d_1(self.conv1d_1( + paddle.concat([h1_Cat_hd1, hd2_UT_hd1, hd3_UT_hd1, hd4_UT_hd1, hd5_UT_hd1], 1)))) # hd1->320320UpChannels + d1 = self.outconv1(hd1) # d1->320320num_classes + if self.end_sigmoid: + out = [F.sigmoid(d1)] + else: + out = [d1] + return out + + +@manager.MODELS.add_component +class UNet_3Plus_DeepSup(nn.Layer): 同样存在命名规范问题 In paddleseg/models/unet_3plus.py:
else:
out = [d1] + return out + + +@manager.MODELS.add_component +class UNet_3Plus_DeepSup(nn.Layer): + """ + The UNet3+ with deep supervision implementation based on PaddlePaddle. + + The original article refers to + Huang H , Lin L , Tong R , et al. UNet 3+: A Full-Scale Connected UNet for Medical Image Segmentation[J]. arXiv, 2020. + (https://arxiv.org/ftp/arxiv/papers/2004/2004.08790.pdf). + + Args: + in_channels (int): The channel number of input image. Default: 3. 注释规范问题 In paddleseg/models/unet_3plus.py:
num_classes (int): The unique number of target classes. Default: 2.
feature_scale (int): The feature map scale. Default: 4. + is_deconv (bool): A bool value indicates whether using deconvolution in upsampling. + If False, use resize_bilinear. Default: True. + is_batchnorm (bool): use batchnorm after conv or not. Default: True. + end_sigmoid (bool): use sigmoid for results or not. Default: False. + """ + def init(self, in_channels=3, num_classes=2, feature_scale=4, is_deconv=True, is_batchnorm=True, end_sigmoid=False): + super(UNet_3Plus_DeepSup, self).init() + self.is_deconv = is_deconv + self.in_channels = in_channels + self.is_batchnorm = is_batchnorm + self.feature_scale = feature_scale + self.end_sigmoid = end_sigmoid + filters = [64, 128, 256, 512, 1024] + ## -------------Encoder-------------- 组网可读性问题 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

请问这个模型自己在我们提供的数据集上训练过吗，可以达到多少精度呢？

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

2021-03-01 13:03 UTC, haoyuying commented
感谢您对paddlehub的贡献，如果您能够提供一个较优的预训练模型结果，将对我们的repo更具有价值和意义。

2021-03-01 13:24 UTC, geoyee commented
参考paddleseg的入门指南（https://gitee.com/paddlepaddle/PaddleSeg/blob/release/v2.0.0-rc/docs/quick_start.md），只在配置中改了一下模型，其他参数保持不变训练的过程及结果在此项目中（https://aistudio.baidu.com/aistudio/projectdetail/1591568）


On 3/1/2021 21:04，haoyuying<notifications@github.com> wrote：

感谢您对paddlehub的贡献，如果您能够提供一个较优的预训练模型结果，将对我们的repo更具有价值和意义。

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

2021-03-18 07:06 UTC, haoyuying commented on paddleseg/models/unet_3plus.py
> +# Copyright (c) 2020 PaddlePaddle Authors. All Rights Reserved.
改成2021吧

2021-03-18 07:06 UTC, haoyuying commented on paddleseg/models/unet_3plus.py
> +        # final = torch.einsum("ijk,ij->ijk", [seg, cls])  # replace it with the following three lines
把这个删掉吧

2021-03-18 07:07 UTC, haoyuying commented on paddleseg/models/unet_3plus.py
> +    def forward(self, inputs):
空一行

2021-03-18 07:07 UTC, haoyuying commented on paddleseg/models/unet_3plus.py
> +        '''stage 4d'''
每个stage 空一行吧，不然显得代码太长

2021-03-18 07:08 UTC, haoyuying commented on paddleseg/models/unet_3plus.py
> +    def forward(self, inputs):
类里面的函数每个要空一行

2021-03-18 07:11 UTC, haoyuying commented on paddleseg/models/layers/layer_libs.py
>  # See the License for the specific language governing permissions and
最好拉一下paddleseg最新的代码，再将您的代码添加到新拉的代码中，最好不要对seg内置的代码进行更改，以防对seg的整体功能产生影响。

2021-03-18 14:10 UTC, closed without merging